// Original prerequisite bridges. `after` identifies the existing h3; the reader
// inserts the bridge immediately after that heading, before its exposition.
const s = String.raw;
const mechanics = {title:'TU Delft · Central forces and polar coordinates',url:'https://qiweb.tudelft.nl/mecharela/central_forces/'};
const oscillations = {title:'MIT · Operators, undetermined coefficients, and resonance',url:'https://ocw.mit.edu/courses/18-03-differential-equations-spring-2010/resources/mit18_03s10_c15/'};
const waves = {title:'MIT · The wave equation',url:'https://ocw.mit.edu/ans7870/18/18.013a/textbook/HTML/chapter29/section04.html'};
const weakGravity = {title:'David Tong · When gravity is weak, §5.2',url:'https://davidtong.org/pdfs/teaching/general-relativity/gr5.pdf'};
const blackHoles = {title:'David Tong · Black holes, §§6.1.3–6.1.5',url:'https://davidtong.org/pdfs/teaching/general-relativity/gr6.pdf'};
const stokes = {title:'MIT · Measures on surfaces and Stokes’ theorem',url:'https://ocw.mit.edu/ans7870/18/18.013a/textbook/HTML/chapter22/section02.html'};
const thermodynamics = {title:'Robert Wald · The thermodynamics of black holes',url:'https://arxiv.org/abs/gr-qc/9912119'};
const thermalTime = {title:'Marc Kamionkowski · Finite-temperature field theory',url:'https://kamion.pha.jhu.edu/Ph236/finiteT.pdf'};

export const bridgeLessons = [
 {
  id:'orbit-conservation',chapter:16,
  after:'16.6 Mercury: a resonant correction that slowly rotates an ellipse',
  title:'Why an orbit keeps its angular momentum',
  question:'What stays fixed while a planet changes both its speed and its direction?',
  intuition:s`A force directed toward the origin can speed up or slow down a planet without twisting its motion about that origin. We will make “twisting” precise using a two-by-two determinant. Start with Newtonian motion in a plane: $(x(t),y(t))$, with $t$ in seconds and distances in metres.`,
  visual:null,
  steps:[
   {title:'Find a quantity whose derivative cancels',body:s`Define the **specific angular momentum** $h=x\dot y-y\dot x$. “Specific” means per unit mass; $h$ has units $\mathrm{m^2/s}$. For a central acceleration $(\ddot x,\ddot y)=a(r)(x,y)/r$ at $r>0$, differentiate with the product rule. The velocity products cancel; the acceleration terms cancel because the acceleration is radial.`,tex:s`\dot h=x\ddot y-y\ddot x=\frac{a(r)}r(xy-yx)=0.`,reason:'The determinant of two parallel arrows is zero. No inverse-square law was needed for this conservation result.'},
   {title:'Translate the determinant into polar coordinates',body:s`Substitute $x=r\cos\phi$ and $y=r\sin\phi$, differentiate, and collect terms. The terms containing $\dot r$ cancel and $\sin^2\phi+\cos^2\phi=1$ leaves $h=r^2\dot\phi$. During a short interval, the radius sweeps out a triangle of signed area $\tfrac12r^2d\phi$.`,tex:s`h=r^2\dot\phi,\qquad \frac{dA}{dt}=\frac h2.`,reason:'Equal swept areas in equal times are a consequence of angular-momentum conservation. Constant angular momentum does not mean constant angular speed.'},
   {title:'Turn radial acceleration into an orbit equation',body:s`The radial unit arrow is $\mathbf e_r=(\cos\phi,\sin\phi)$ and the perpendicular arrow is $\mathbf e_\phi=(-\sin\phi,\cos\phi)$. Their derivatives with respect to $\phi$ are $\mathbf e_\phi$ and $-\mathbf e_r$. Differentiating $\mathbf r=r\mathbf e_r$ twice therefore gives radial acceleration $\ddot r-r\dot\phi^2$. For gravity it equals $-G_NM/r^2$. If $h\ne0$, use $u=1/r$ and a prime for $d/d\phi$. The chain rule gives $\dot r=-hu'$ and $\ddot r=-h^2u^2u''$.`,tex:s`-h^2u^2u''-h^2u^3=-G_NM u^2\quad\Longrightarrow\quad u''+u=\frac{G_NM}{h^2}.`,reason:'Changing the independent variable from time to angle turns the problem into a differential equation for the shape of the orbit. This step excludes purely radial motion, where h is zero.'},
   {title:'Carry the symmetry into relativity',body:s`For an equatorial timelike Schwarzschild geodesic, use the quadratic geodesic Lagrangian $L=\tfrac12g_{\mu\nu}\dot x^\mu\dot x^\nu$ with proper time $\tau$ as parameter. Here dots mean $d/d\tau$. The metric has no explicit $\phi$ dependence and $g_{\phi\phi}=r^2$, so the Euler–Lagrange equation conserves $\partial L/\partial\dot\phi=r^2\dot\phi$. We call this constant $\ell$.`,tex:s`\frac{d}{d\tau}\frac{\partial L}{\partial\dot\phi}=\frac{\partial L}{\partial\phi}=0,\qquad \ell=r^2\frac{d\phi}{d\tau}.`,reason:'Rotational symmetry still supplies the conserved quantity. The time parameter and radial equation change; Chapter 17 derives their relativistic form.'}
  ],
  formal:s`The Newtonian solution is $u=p^{-1}[1+e\cos(\phi-\phi_0)]$, where $p=h^2/(G_NM)$, $e$ is a dimensionless shape parameter, and $\phi_0$ sets the direction of closest approach. Substitution verifies the solution directly. For $0\le e<1$ it describes an ellipse (a circle at $e=0$); other values describe different conic orbits. The relativistic equation below adds a small term to this familiar starting point. It is derived in §17.5, not inferred from conservation alone.`,
  requires:[{label:'Newton’s law and energy',href:'chapter-0.html#0-5-the-mechanics-we-will-use'},{label:'The geodesic action',href:'chapter-5.html#5-5-deriving-the-geodesic-equation-one-operation-at-a-time'}],
  practice:{prompt:s`A planet in a central-force orbit moves from radius $r$ to $2r$. What happens to its angular speed?`,choices:[{text:s`It becomes $\dot\phi/4$.`,correct:true,feedback:s`Yes. Conservation of $r^2\dot\phi$ requires $(2r)^2\dot\phi_{\rm new}=r^2\dot\phi_{\rm old}$.`},{text:s`It becomes $\dot\phi/2$.`,correct:false,feedback:s`That would conserve $r\dot\phi$, the tangential speed. The conserved quantity contains $r^2$.`},{text:s`It stays unchanged because angular momentum is conserved.`,correct:false,feedback:s`Angular speed and angular momentum are different quantities. The larger lever arm changes their relationship.`}],hint:s`Write the same constant $h$ at the two positions before canceling anything.`},
  transfer:{prompt:s`At one instant a particle has $(x,y)=(3,4)\,\mathrm m$ and $(\dot x,\dot y)=(-2,1)\,\mathrm{m/s}$. Compute its signed specific angular momentum about the origin.`,answer:11,tolerance:0.001,unit:s`$\mathrm{m^2/s}$`,hint:s`Use the determinant $h=x\dot y-y\dot x$; no conversion to polar coordinates is needed.`,solution:s`$h=3(1)-4(-2)=11\,\mathrm{m^2/s}$. The positive sign means the motion sweeps area counterclockwise in these oriented axes.`},
  sources:[mechanics],takeaway:'Rotational symmetry conserves angular momentum; the force law determines the orbit’s shape.'
 },
 {
  id:'phase-drift',chapter:16,
  after:'16.6 Mercury: a resonant correction that slowly rotates an ellipse',
  title:'A tiny frequency change can rotate an entire orbit',
  question:'Why does a small correction grow into a measurable shift after many cycles?',
  intuition:s`A sine wave returns to its starting value after its phase advances by $2\pi$. If radial motion completes its cycle at an angle slightly different from $2\pi$, the next closest approach points in a different direction. We need an oscillation measured against **orbital angle**, not clock time.`,
  visual:null,
  steps:[
   {title:'Recognize the unforced oscillation',body:s`Twice differentiating $\cos\phi$ returns $-\cos\phi$; the same holds for $\sin\phi$. Thus $y''+y=0$ has solutions $A\cos\phi+B\sin\phi$. In an orbit, $y$ is the oscillating part of reciprocal radius. The constants are fixed by the initial position and direction.`,tex:s`\left(\frac{d^2}{d\phi^2}+1\right)\cos\phi=0.`,reason:'The same elementary differential equation describes many oscillations, even when the independent variable is an angle.'},
   {title:'See why a matching forcing term is special',body:s`Suppose a small correction gives $y''+y=C\cos\phi$. A trial proportional to $\cos\phi$ produces zero on the left and cannot work. Try $y=(C/2)\phi\sin\phi$ instead: its first derivative is $(C/2)(\sin\phi+\phi\cos\phi)$; a second derivative plus $y$ leaves $C\cos\phi$.`,tex:s`\left(\frac{d^2}{d\phi^2}+1\right)(\phi\sin\phi)=2\cos\phi.`,reason:'The forcing has the same angular frequency as the unforced motion. This is resonance in the orbit-shape equation, not an external periodic force supplying orbital energy.'},
   {title:'Read the growing term as a phase correction',body:s`Taylor-expand $\cos(\phi-\delta\phi)$ in the small phase shift $\delta\phi$. Its correction is $\delta\phi\sin\phi$. That is exactly the form above. A growing correction to a truncated series can signal a slightly shifted frequency, rather than an orbit whose radius grows without limit.`,tex:s`\cos[(1-\delta)\phi]=\cos\phi+\delta\phi\sin\phi+O((\delta\phi)^2).`,reason:'The expanded expression is reliable only while the accumulated phase shift is small. Retaining the shifted phase packages repeated cycles more usefully.'},
   {title:'Convert a phase shift into a perihelion advance',body:s`Let $m=G_NM/c^2$ and $p=\ell^2/(G_NM)$. The perturbative calculation below gives $\delta=3m/p\ll1$. In the shifted-frequency approximation, one radial cycle requires $(1-\delta)\Delta\phi_{\rm cycle}=2\pi$. Subtract the full turn $2\pi$ to obtain the advance.`,tex:s`\Delta\phi_{\rm advance}\simeq2\pi\delta=\frac{6\pi G_NM}{pc^2}.`,reason:'Keep only the order justified by the orbit calculation. The expression is a weak-field, small-correction prediction, not an exact strong-field formula.'}
  ],
  formal:s`For $u_0=p^{-1}(1+e\cos\phi)$, the first-order correction contains $3mu_0^2$. Expanding the square and using $\cos^2\phi=(1+\cos2\phi)/2$ reveals a constant term, a $\cos2\phi$ term, and the resonant term $6me\cos\phi/p^2$. The latter produces $3me\phi\sin\phi/p^2$, matching the phase shift $\delta=3m/p$. The constant and double-frequency terms change the shape at this order without producing the same accumulating phase drift. For an exactly circular orbit, a direction of perihelion is undefined; the small-eccentricity frequency limit remains meaningful.`,
  requires:[{label:'Taylor approximation',href:'chapter-0.html#0-8-approximation-is-a-skill-not-an-apology'},{label:'Orbit conservation',href:'chapter-16.html#orbit-conservation'}],
  practice:{prompt:s`Why should we hesitate to use $\cos\phi+\delta\phi\sin\phi$ for arbitrarily many revolutions?`,choices:[{text:s`The neglected terms depend on $\delta\phi$, which eventually need not be small.`,correct:true,feedback:s`Yes. A small frequency difference can accumulate a large phase difference. The expansion parameter for this Taylor series is the accumulated phase.`},{text:s`Every resonant correction means the planet gains unlimited energy.`,correct:false,feedback:s`Here the equation describes reciprocal radius as a function of angle. Its resonant term need not represent a physical energy input.`},{text:s`Taylor expansions cannot be used for trigonometric functions.`,correct:false,feedback:s`They can; the issue is the size of the quantity expanded, not whether the function is trigonometric.`}],hint:s`Read the argument of the remainder term in the displayed Taylor expansion.`},
  transfer:{prompt:s`A toy orbit has reciprocal radius proportional to $1+0.2\cos(0.98\phi)$. What is its exact angular advance beyond $2\pi$ between successive maxima of reciprocal radius? Give radians.`,answer:2*Math.PI*(1/0.98-1),tolerance:0.0005,unit:s`$\mathrm{rad}$`,hint:s`The cosine’s phase, $0.98\phi$, must increase by $2\pi$. This toy expression is specified exactly, so do not replace the answer by its first-order estimate.`,solution:s`One radial cycle takes $\Delta\phi=2\pi/0.98$. Its advance is $2\pi(1/0.98-1)\simeq0.12823\,\mathrm{rad}$.`},
  sources:[oscillations],takeaway:'A small frequency correction can accumulate into a large, observable phase difference.'
 },
 {
  id:'waves-and-retarded-time',chapter:18,
  after:'18.1 Linearization is a controlled approximation, not a different theory',
  title:'Read a wave before reading its complex notation',
  question:'How does an equation say that information travels at a definite speed?',
  intuition:s`Imagine a pulse with a shape $F$ moving toward increasing $z$ without changing shape. At time $t$, its profile is $F(z-ct)$. Keeping the pulse’s argument fixed gives $z=ct+\text{constant}$: the pulse moves at speed $c$. No complex numbers are needed.`,
  visual:null,
  steps:[
   {title:'Check the wave equation with the chain rule',body:s`For $h(t,z)=F(z-ct)$, differentiating twice in time gives $\partial_t^2h=c^2F''$, while differentiating twice in space gives $\partial_z^2h=F''$. Therefore every twice-differentiable shape of this form obeys the same wave equation. $G(z+ct)$ describes propagation in the opposite direction.`,tex:s`-\frac1{c^2}\frac{\partial^2h}{\partial t^2}+\frac{\partial^2h}{\partial z^2}=0.`,reason:'A partial differential equation relates changes at neighboring places and times. Its allowed solutions carry the propagation speed.'},
   {title:'Turn crests into frequency and wavelength',body:s`For a sinusoid $h=A\cos(kz-\omega t)$, increasing $z$ by $2\pi/k$ or time by $2\pi/\omega$ repeats the phase. Thus wavelength $\lambda=2\pi/k$, period $P=2\pi/\omega$, and frequency $f=1/P$. Substitution in the wave equation gives $\omega^2=c^2k^2$; choose positive $k,\omega$ for propagation toward increasing $z$.`,tex:s`\omega=ck,\qquad f\lambda=c.`,reason:'The coordinate z is a length, k has inverse-length units, and omega has inverse-time units. The phase is dimensionless.'},
   {title:'Introduce the delayed source time',body:s`A signal received at time $t$ from a source a distance $R$ away left at $t-R/c$. This is **retarded time**. In flat three-dimensional space, each source location $\mathbf x'$ has its own distance $R=|\mathbf x-\mathbf x'|$. A retarded field integral samples each source contribution at its corresponding departure time. The factor $1/R$ in the later solution describes spherical spreading; it is not part of the time delay.`,tex:s`t_{\rm ret}=t-\frac{|\mathbf x-\mathbf x'|}{c}.`,reason:'Selecting the retarded solution is a physical boundary condition: the measured response follows the source. The differential equation also permits added free waves.'},
   {title:'Treat complex notation as an optional abbreviation',body:s`Define $i^2=-1$ and use $e^{i\psi}=\cos\psi+i\sin\psi$. This identity packages two real functions together; taking the real part recovers the cosine. Differentiation multiplies $e^{i(kz-\omega t)}$ by $ik$ or $-i\omega$, making linear equations easier to solve. A complex amplitude $A=a+ib$ gives the real field $a\cos\psi-b\sin\psi$, so it also stores phase.`,tex:s`h=\operatorname{Re}\!\left[Ae^{i(kz-\omega t)}\right].`,reason:'The measured strain is real. Complex notation is a calculation tool; no imaginary displacement has been introduced.'}
  ],
  formal:s`In three spatial dimensions, $\nabla^2=\partial_x^2+\partial_y^2+\partial_z^2$ and $\Box=-c^{-2}\partial_t^2+\nabla^2$. The linearized Einstein equation applies this operator to each component of a suitable metric perturbation. A plane-wave phase can be written $k_\mu x^\mu$, with $x^0=ct$ and $k_\mu=(-\omega/c,k_x,k_y,k_z)$. Substitution gives $-\omega^2/c^2+|\mathbf k|^2=0$: the wave covector is null. This establishes the propagation law in the approximation. Gauge constraints and geodesic deviation are still needed to identify the two measurable polarizations.`,
  requires:[{label:'Partial derivatives',href:'chapter-0.html#0-2-partial-derivatives-change-one-input-at-a-time'},{label:'Differential equations and initial data',href:'chapter-0.html#0-4-a-differential-equation-needs-a-starting-story'}],
  practice:{prompt:s`Which profile moves toward increasing $z$ at speed $c>0$?`,choices:[{text:s`$F(z-ct)$`,correct:true,feedback:s`A fixed feature has $z-ct=\text{constant}$, hence $dz/dt=c$.`},{text:s`$F(z+ct)$`,correct:false,feedback:s`A fixed feature now has $z+ct=\text{constant}$, so $dz/dt=-c$.`},{text:s`$F(z)\cos(ct)$`,correct:false,feedback:s`This keeps the spatial shape fixed while its amplitude changes. It does not generally describe a translating profile; moreover, ct alone has length units and cannot be the argument of a cosine.`}],hint:s`Follow a particular crest by setting its argument equal to a constant.`},
  transfer:{prompt:s`A source is $9.0\times10^8\,\mathrm m$ away in a flat-space model with $c=3.0\times10^8\,\mathrm{m/s}$. A signal arrives at $t=12\,\mathrm s$. At what source time was it emitted?`,answer:9,tolerance:0.001,unit:s`$\mathrm s$`,hint:s`Compute the travel time first, then subtract it from the arrival time.`,solution:s`$R/c=3\,\mathrm s$, so $t_{\rm ret}=12-3=9\,\mathrm s$. In a curved spacetime the travel time must instead follow the appropriate null path.`},
  sources:[waves,weakGravity],takeaway:'Real wave profiles teach propagation; complex exponentials abbreviate the same real solutions.'
 },
 {
  id:'horizon-directions',chapter:17,
  after:'17.3 Repairing the horizon with Eddington–Finkelstein coordinates',
  title:'At a horizon, ask which directions lead into the future',
  question:'Can a future-directed light ray point outward and still lose areal radius?',
  intuition:s`At an event, a light cone gives the possible directions of light and the allowed directions of massive travelers. In this radial diagram, left and right measure **areal radius** $r$: a symmetry sphere has area $4\pi r^2$. Upward means increasing plot time. The horizon is $r=r_s=2G_NM/c^2$. Compare an event outside, on, and inside it; the directions are computed from the metric, not drawn to resemble a funnel.`,
  visual:'horizon',
  steps:[
   {title:'Use a chart that survives horizon crossing',body:s`Set $f=1-r_s/r$. Schwarzschild radial light obeys $c\,dt=\pm dr/f$. Introduce $r_*=r+r_s\ln|r/r_s-1|$, whose derivative is $1/f$, and the advanced time $v=t+r_*/c$ in seconds. Substituting $dt=dv-dr/(cf)$ cancels the divergent radial terms. The time-radial metric block has determinant $-c^2$, including at the horizon.`,tex:s`ds^2=-fc^2dv^2+2c\,dv\,dr+r^2d\Omega^2.`,reason:'The new metric stays finite and nondegenerate at the horizon. The old chart failed there; the geometry did not.'},
   {title:'Find both light directions without dividing one away',body:s`Radial light has $d\Omega=0$ and $ds^2=0$. Factoring gives $c\,dv(-fc\,dv+2dr)=0$. One family has $dv=0$: future ingoing light has decreasing $r$. The other family has $dr/dv=cf/2$. Keep the first family before dividing by $dv$, or half the light cone disappears from the calculation.`,tex:s`dv=0\quad\text{or}\quad \frac{dr}{dv}=\frac c2\left(1-\frac{r_s}{r}\right).`,reason:'A product vanishes when either factor vanishes. The two solutions are the two radial null directions.'},
   {title:'Translate the directions into the displayed axes',body:s`Use dimensionless radius $\rho=r/r_s$ and dimensionless plot time $\tau_{\rm plot}=cv/r_s-\rho$. This $\tau_{\rm plot}$ is a coordinate, **not a traveler’s proper time**. For outgoing light, divide $d\rho/d(cv/r_s)=f/2$ by $d\tau_{\rm plot}/d(cv/r_s)=1-f/2$. For ingoing light, $dv=0$ gives $d\tau_{\rm plot}=-d\rho$.`,tex:s`\left.\frac{d\rho}{d\tau_{\rm plot}}\right|_{\rm out}=\frac{\rho-1}{\rho+1},\qquad \left.\frac{d\rho}{d\tau_{\rm plot}}\right|_{\rm in}=-1.`,reason:'Both plotted directions rise toward the future. Their slopes are coordinate rates, not the speed a local observer measures.'},
   {title:'Read the permitted futures',body:s`At $\rho=3$, outgoing light has positive slope $1/2$. At $\rho=1$, its slope is zero: it follows the horizon. At $\rho=1/2$, even the outgoing slope is $-1/3$. Future radial timelike directions lie strictly between the null directions. Angular motion narrows the allowed radial projection further. Thus every massive future traveler inside this black-hole region moves toward smaller areal radius.`,tex:s`0<\rho<1\quad\Longrightarrow\quad -1<\frac{d\rho}{d\tau_{\rm plot}}<\frac{\rho-1}{\rho+1}<0\quad\text{(radial timelike)}.`,reason:'Increasing thrust changes which allowed timelike direction is followed. It cannot move that direction outside the local light cone.'}
  ],
  formal:s`This diagram describes the future-horizon extension of the stationary Schwarzschild solution for $r>0$. Its local cone calculation must be distinguished from the **global definition** of a black hole: in an asymptotically flat spacetime, a black-hole event cannot send any future causal signal to future null infinity, the ideal destination of light that escapes forever. The event horizon is the boundary of that region. It depends on the entire future geometry. The surface $r=r_s$ has this role in the specified Schwarzschild black-hole spacetime; a local “cone tilt” test is not a general horizon detector in arbitrary evolving spacetimes. At $r_s$ the curvature invariant is $12/r_s^4$, finite for $M>0$. At $r=0$ it diverges. A regular horizon and a curvature singularity are different geometric facts.`,
  requires:[{label:'Null curves',href:'chapter-5.html#5-7-null-curves-zero-clock-time-does-not-mean-zero-geometry'},{label:'The Schwarzschild solution',href:'chapter-17.html#17-1-solving-spherical-vacuum-where-schwarzschild-comes-from'},{label:'Coordinate failure versus curvature',href:'chapter-17.html#17-2-two-alarming-radii-two-very-different-problems'}],
  practice:{prompt:s`Inside this Schwarzschild black hole, why can an outward-fired light pulse have decreasing $r$?`,choices:[{text:s`“Outward” labels the less inward null direction; both future radial null directions have decreasing areal radius.`,correct:true,feedback:s`Yes. The two null directions remain distinct. Their radial coordinate rates are both negative inside this horizon.`},{text:s`Its locally measured speed has fallen below $c$.`,correct:false,feedback:s`A local freely falling observer still measures the light pulse’s speed as $c$. The negative quantity in the diagram is a coordinate rate.`},{text:s`An infinite curvature wall pushes it back at $r_s$.`,correct:false,feedback:s`The Schwarzschild horizon is regular. The divergent curvature invariant occurs at $r=0$, not at $r_s$.`}],hint:s`Compare the two null slopes at $\rho=1/2$ and keep local measurement separate from coordinate slope.`},
  transfer:{prompt:s`At $r=3r_s/4$, calculate the outgoing light slope $d\rho/d\tau_{\rm plot}$.`,answer:-1/7,tolerance:0.0005,unit:'dimensionless',hint:s`Insert $\rho=3/4$ into $(\rho-1)/(\rho+1)$.`,solution:s`The slope is $(-1/4)/(7/4)=-1/7\simeq-0.142857$. This negative coordinate slope says the outgoing light ray still moves toward smaller areal radius.`},
  sources:[blackHoles],takeaway:'The horizon is a boundary of causal escape, not a place where local light slows down.'
 },
 {
  id:'kruskal-and-causal-maps',chapter:17,
  after:'17.6 An event horizon knows about the future',
  title:'Build a global causal map one coordinate change at a time',
  question:'How can a finite diagram include infinity without distorting who can signal whom?',
  intuition:s`An ordinary road map preserves useful routes while changing distances. A causal diagram preserves the possible routes of signals. First choose coordinates in which radial light rays are straight. Then compress each null coordinate with a strictly increasing function. The resulting picture answers causal questions; its ruler does not measure proper distance or elapsed time.`,
  visual:null,
  steps:[
   {title:'Exponentiate the troublesome null coordinates',body:s`Begin in the right Schwarzschild exterior, $\rho=r/r_s>1$. Define $q=ct/r_s$, $\rho_*=\rho+\ln(\rho-1)$, $\bar u=q-\rho_*$ and $\bar v=q+\rho_*$. Constant $\bar u$ and constant $\bar v$ describe radial light. Define $U=-e^{-\bar u/2}$ and $V=e^{\bar v/2}$. Multiplying eliminates $q$ and identifies the radius.`,tex:s`UV=-(\rho-1)e^\rho,\qquad U<0,\ V>0\quad\text{in the right exterior}.`,reason:'These exponentials make the horizon occur at a finite null-coordinate value. Their sign definitions here cover one exterior, not all four regions.'},
   {title:'Extend the metric, not an invalid exterior formula',body:s`Differentiating gives $d\bar u=-2dU/U$ and $d\bar v=2dV/V$. Substituting in $ds^2_{\rm radial}=-r_s^2f\,d\bar u\,d\bar v$ cancels the zero of $f$. The result below stays regular at $\rho=1$. It defines an extension to real $U,V$ with $UV<1$, where $\rho>0$ is fixed implicitly by their product. One does not keep $U=-e^{-\bar u/2}$ with real exterior Schwarzschild coordinates inside every region.`,tex:s`ds^2=-\frac{4r_s^2e^{-\rho}}{\rho}\,dU\,dV+r^2d\Omega^2.`,reason:'A smooth, nondegenerate metric is the object being extended. A coordinate expression valid only in the exterior must not be mistaken for a universal definition.'},
   {title:'Identify the regions by their signs',body:s`With future chosen so that both $U$ and $V$ increase along radial timelike curves, $(U<0,V>0)$ is the right exterior, $(U>0,V>0)$ the black-hole interior, $(U>0,V<0)$ the left exterior, and $(U<0,V<0)$ the white-hole interior. The null lines $U=0$ and $V=0$ are horizons. The boundary $UV=1$ corresponds to $r=0$: its positive-sign branch is a future singularity, and its negative-sign branch a past singularity. In the axes below, radial light has slope $\pm1$.`,tex:s`T_K=\frac{V+U}{2},\qquad X_K=\frac{V-U}{2},\qquad dU\,dV=dT_K^2-dX_K^2.`,reason:'The singularity is a spacelike boundary, not a stationary object drawn at the center of a spatial funnel.'},
   {title:'Compress infinity while keeping null rays straight',body:s`Set $p=\arctan U$ and $q_c=\arctan V$, both in $(-\pi/2,\pi/2)$. Their derivatives are positive, so increasing null coordinates still means the same future direction. Define $T_c=(q_c+p)/2$ and $X_c=(q_c-p)/2$. Curves with constant $U$ or $V$ remain lines at $45$ degrees. Infinite coordinate values become limiting edges; those edges are not nearby physical walls.`,tex:s`dU\,dV=\sec^2p\,\sec^2q_c\,(dT_c^2-dX_c^2).`,reason:'The multiplying factor is positive at interior points. It changes scale but preserves which radial directions are null, timelike, and spacelike.'}
  ],
  formal:s`In the right exterior, future null infinity $\mathscr I^+$ is approached by $V\to+\infty$ with fixed finite $U<0$: escaping outgoing light reaches the boundary $q_c=\pi/2$. Timelike and spacelike infinity are different limiting destinations. Each point of the radial diagram represents a symmetry two-sphere, with the angular directions suppressed. The four-region map describes **maximally extended eternal Schwarzschild**. It contains a white-hole region and a second exterior. A black hole formed by stellar collapse has a matter interior and a different past causal structure; it need not contain either of those extra regions. No future causal route crosses the eternal bridge from one exterior to the other: from the right exterior, $V$ cannot decrease to the negative values of the left exterior.`,
  requires:[{label:'Horizon-penetrating coordinates',href:'chapter-17.html#17-3-repairing-the-horizon-with-eddington-finkelstein-coordinates'},{label:'Elementary derivatives',href:'chapter-0.html#0-1-a-derivative-is-a-local-prediction'}],
  practice:{prompt:s`What survives the compression of a causal diagram?`,choices:[{text:s`The possible causal directions and the order in which a signal can connect events.`,correct:true,feedback:s`Yes. Monotone changes of the null coordinates and positive interior conformal factors preserve the causal cones.`},{text:s`The numerical proper time between any pair of events.`,correct:false,feedback:s`Proper time depends on the metric’s scale, which the conformal drawing does not preserve.`},{text:s`A guarantee that a collapsing star produces all four eternal Schwarzschild regions.`,correct:false,feedback:s`The global spacetime must include its formation history. The eternal extension is a different idealized spacetime.`}],hint:s`The prefactor in the final metric expression changes lengths while leaving the zero of a null interval unchanged.`},
  transfer:{prompt:s`An event has $\arctan U=-\pi/6$ and $\arctan V=\pi/3$. What is its compressed time $T_c$, expressed as a multiple of $\pi$? Enter the coefficient.`,answer:1/12,tolerance:0.0005,unit:s`coefficient of $\pi$`,hint:s`Use $T_c=(\arctan V+\arctan U)/2$.`,solution:s`$T_c=[\pi/3-\pi/6]/2=\pi/12$, so the coefficient is $1/12\simeq0.083333$. This is a coordinate value, not a reading in seconds.`},
  sources:[blackHoles],takeaway:'A causal map preserves signal routes; its boundaries and extra regions must be interpreted for the spacetime actually specified.'
 },
 {
  id:'oriented-stokes',chapter:21,
  after:'21.2 Differential forms: antisymmetry earns its keep',
  title:'Calculate both sides of Stokes’ theorem',
  question:'Why can a measurement around an edge equal an accumulation over its interior?',
  intuition:s`Tile a region with little squares and walk around each square counterclockwise. Every shared edge is traversed twice in opposite directions, so its contributions cancel. Only the outer boundary remains. Differential forms organize the signed measurements needed to turn that picture into a calculation.`,
  visual:null,
  steps:[
   {title:'Make a one-form into a measurable path integral',body:s`Use dimensionless coordinates on a rectangle $0\le x\le a$, $0\le y\le b$. Let $\alpha=x^2dy$. Along a path $s\mapsto(x(s),y(s))$, this means integrate $x(s)^2y'(s)\,ds$. Reversing the path reverses the sign. Horizontal segments contribute zero because $dy=0$.`,tex:s`\int_\gamma\alpha=\int_{s_0}^{s_1}x(s)^2\frac{dy}{ds}\,ds.`,reason:'A one-form acts on the path’s tangent at each point; an ordinary single-variable integral adds those local readings.'},
   {title:'Walk the four edges',body:s`Choose counterclockwise orientation. The bottom edge has $dy=0$. The right edge has $x=a$ and $y:0\to b$, contributing $a^2b$. The top is horizontal. The left has $x=0$, so it contributes zero even though it is traversed downward.`,tex:s`\oint_{\partial\Omega}\alpha=0+\int_0^b a^2\,dy+0+\int_b^0 0^2\,dy=a^2b.`,reason:'The boundary’s direction matters. Clockwise traversal would negate the answer.'},
   {title:'Measure oriented area with a determinant',body:s`For two arrows $V=(V^x,V^y)$ and $W=(W^x,W^y)$, define $(dx\wedge dy)(V,W)=V^xW^y-V^yW^x$. It is their signed area. Swapping the arrows flips the sign, so $dy\wedge dx=-dx\wedge dy$. Here $d\alpha=d(x^2)\wedge dy=2x\,dx\wedge dy$.`,tex:s`\int_\Omega d\alpha=\int_0^a\!\int_0^b2x\,dy\,dx=a^2b.`,reason:'We choose dx wedge dy as the positive orientation. The compatible boundary traversal is counterclockwise.'},
   {title:'Recover the general planar rule',body:s`For $\alpha=P\,dx+Q\,dy$, differentiate the coefficients. Terms with $dx\wedge dx$ or $dy\wedge dy$ vanish; the reversed pair contributes a minus sign. This gives the signed interior density whose integral equals the counterclockwise boundary integral.`,tex:s`d\alpha=(\partial_xQ-\partial_yP)\,dx\wedge dy,\qquad \int_\Omega d\alpha=\oint_{\partial\Omega}\alpha.`,reason:'Oppositely traversed internal edges cancel. The difference of neighboring edge readings becomes a derivative as the tiles shrink.'}
  ],
  formal:s`The general theorem needs an oriented manifold with boundary, a sufficiently smooth form of the appropriate degree, and the boundary orientation induced by the interior. On a compact oriented surface, $\alpha$ is a one-form and $d\alpha$ a two-form. In $n$ dimensions, one integrates an $(n-1)$-form on the boundary and its exterior derivative on the interior. Singularities and omitted points matter: a form undefined at a puncture cannot be passed through that puncture by invoking Stokes’ theorem. The remaining text develops the algebra that makes the same calculation independent of the chosen coordinates.`,
  requires:[{label:'Integrals add local measurements',href:'chapter-0.html#0-3-an-integral-adds-local-measurements'},{label:'Covectors and differential measurements',href:'chapter-2.html'}],
  practice:{prompt:s`If we reverse both the chosen surface orientation and its induced boundary direction, what happens?`,choices:[{text:s`Both integrals change sign, and they remain equal.`,correct:true,feedback:s`Yes. Orientation records which order of directions counts as positive. Stokes’ theorem uses compatible orientations on both sides.`},{text:s`Only the boundary integral changes sign.`,correct:false,feedback:s`An integral of a differential form over an oriented surface also changes sign when the surface orientation is reversed.`},{text:s`Neither changes sign because geometric area is positive.`,correct:false,feedback:s`A differential form measures oriented area. It is not an unsigned area density.`}],hint:s`The wedge product changes sign when its two input directions are exchanged.`},
  transfer:{prompt:s`For $\alpha=xy\,dy$, integrate counterclockwise around the dimensionless rectangle $0\le x\le2$, $0\le y\le3$.`,answer:9,tolerance:0.001,unit:'dimensionless',hint:s`Either integrate along the right edge, or use $d\alpha=y\,dx\wedge dy$.`,solution:s`Only the right edge contributes: $\int_0^3 2y\,dy=9$. The interior gives $\int_0^2\int_0^3 y\,dy\,dx=9$ as well.`},
  sources:[stokes],takeaway:'Orientation makes neighboring boundary contributions cancel; Stokes’ theorem records the resulting equality.'
 },
 {
  id:'temperature-and-quantum-input',chapter:22,
  after:'22.7 A horizon gets a temperature',
  title:'Separate the geometry from the quantum assumption',
  question:'Which part of black-hole temperature can we derive with calculus, and what new physics must we import?',
  intuition:s`A formula involving temperature needs more than a metric. We need to say what temperature means, how quantum states evolve, and why thermal equilibrium can be represented using imaginary time. We can check the algebra of that connection here while keeping its physical assumptions visible.`,
  visual:null,
  steps:[
   {title:'Give temperature and entropy operational jobs',body:s`For a reversible change with the other thermodynamic work variables fixed, the first law reads $dE=T\,dS$. Energy $E$ is measured in joules, temperature $T$ in kelvin, and entropy $S$ in joules per kelvin. Thus $1/T=dS/dE$ along this family of equilibrium states. In quantum statistical mechanics, a state of energy $E$ has thermal weight proportional to $e^{-E/(k_BT)}$, where Boltzmann’s constant $k_B$ converts temperature to an energy scale. This thermal-weight rule is new physical input.`,tex:s`dE=T\,dS,\qquad w(E)\propto e^{-E/(k_BT)}.`,reason:'A thermal weight is not derived from Einstein’s equation. Specifying the thermodynamic ensemble and its constraints is part of using it.'},
   {title:'Compare a quantum phase with a thermal weight',body:s`A stationary quantum state of energy $E$ evolves with phase $e^{-iEt/\hbar}$, where $\hbar$ is the reduced Planck constant. Formally substitute $t=-i\tau_E$; this is an analytic continuation, not a clock traveling into an imaginary physical direction. Since $(-i)(-i)=-1$, the phase becomes $e^{-E\tau_E/\hbar}$. Matching it to the thermal weight gives the imaginary-time interval $\Delta\tau_E=\hbar/(k_BT)$.`,tex:s`e^{-iEt/\hbar}\ \xrightarrow{\ t=-i\tau_E\ }\ e^{-E\tau_E/\hbar},\qquad \Delta\tau_E=\frac{\hbar}{k_BT}.`,reason:'The algebra explains the length of the thermal interval. The full periodicity statement comes from the thermal trace and quantum correlation functions; it is not established by this substitution alone.'},
   {title:'Let regular geometry determine that interval',body:s`The near-horizon calculation in this section puts the Euclidean radial-time metric into polar form $d\varrho^2+\varrho^2d\theta_E^2$, with $\theta_E=c\tau_E/(2r_s)$. A smooth plane requires angular period $2\pi$; a different period produces a conical tip. Therefore $\Delta\tau_E=4\pi r_s/c$. Equating this geometric period to the thermal interval gives the Schwarzschild temperature at infinity.`,tex:s`T_H=\frac{\hbar c}{4\pi r_sk_B}=\frac{\hbar c^3}{8\pi G_NMk_B}.`,reason:'Smooth Euclidean geometry fixes a period. Quantum statistical mechanics supplies its interpretation as a temperature.'},
   {title:'Check what the first law then predicts',body:s`For the nonrotating, uncharged equilibrium family, use $E=Mc^2$. Substituting $T_H$ in $dS=dE/T_H$ gives a term proportional to $M\,dM$. Integrating produces an entropy proportional to $M^2$. Because $A=4\pi r_s^2=16\pi G_N^2M^2/c^4$, it is also proportional to horizon area. The integration leaves an arbitrary additive constant $S_0$.`,tex:s`dS=\frac{8\pi k_BG_NM}{\hbar c}\,dM,\qquad S=\frac{k_BAc^3}{4\hbar G_N}+S_0.`,reason:'The first law fixes entropy differences. The conventional additive normalization does not emerge from this integration.'}
  ],
  formal:s`The stationary Euclidean construction is an equilibrium argument. For bosonic fields, the corresponding thermal correlation functions are periodic in imaginary time; fermionic fields have the associated antiperiodic condition. A collapse spacetime’s outgoing Hawking flux requires a quantum-field calculation with a specified state and boundary conditions. It yields the same asymptotic temperature scale, while scattering by the spacetime modifies the observed spectrum. This is **semiclassical physics**: quantum fields on a classical background, with controlled treatment of backreaction where applicable. It does not derive a microscopic count of black-hole states, explain the final stage of evaporation, or establish a complete quantum theory of gravity. Those are open tasks, not consequences hidden in the elementary algebra.`,
  requires:[{label:'Thermal probabilities and entropy',href:'chapter-22.html#probability-temperature-and-entropy'},{label:'Quantum states and reduced information',href:'chapter-22.html#quantum-states-and-reduced-information'},{label:'Energy and the mechanics vocabulary',href:'chapter-0.html#0-5-the-mechanics-we-will-use'},{label:'Real waves and optional complex notation',href:'chapter-18.html#waves-and-retarded-time'},{label:'Regular and singular black-hole surfaces',href:'chapter-17.html#17-2-two-alarming-radii-two-very-different-problems'}],
  practice:{prompt:s`Which statement correctly identifies the extra physical input in the Euclidean argument?`,choices:[{text:s`Quantum statistical mechanics relates an imaginary-time interval to temperature.`,correct:true,feedback:s`Yes. Geometry determines the interval required for regularity; quantum thermal physics provides the relation to temperature.`},{text:s`Einstein’s classical equation alone derives the thermal Boltzmann weights.`,correct:false,feedback:s`The Boltzmann weights and quantum phase evolution are additional physical principles, not results of classical GR.`},{text:s`Imaginary time is the proper time recorded by an observer inside the horizon.`,correct:false,feedback:s`Imaginary time is an analytic-continuation tool. It is not the real proper time of a traveler.`}],hint:s`Locate the first appearance of both $\hbar$ and $k_B$ in the chain of reasoning.`},
  transfer:{prompt:s`Compare two nonrotating, uncharged black holes with masses $M$ and $3M$. Using the conventional $S_0=0$, what is $S(3M)/S(M)$?`,answer:9,tolerance:0.001,unit:'dimensionless',hint:s`The radius is proportional to mass, and the entropy is proportional to the horizon area.`,solution:s`$r_s(3M)=3r_s(M)$, so the area and entropy each increase by $3^2=9$. The temperature instead falls to one third.`},
  sources:[thermodynamics,thermalTime],takeaway:'The temperature calculation joins regular geometry to explicitly stated quantum and thermodynamic input.'
 }
];
