const s=String.raw;
const gr={title:'David Tong · General relativity',url:'https://www.davidtong.org/teaching/general-relativity/'};
const units={title:'BIPM · The International System of Units',url:'https://www.bipm.org/en/publications/si-brochure'};
const ode={title:'MIT · Differential equations and initial data',url:'https://ocw.mit.edu/courses/18-03sc-differential-equations-fall-2011/resources/lecture-notes/'};
const em={title:'David Tong · Electromagnetism',url:'https://www.davidtong.org/teaching/electromagnetism/'};
const thermal={title:'David Tong · Statistical physics',url:'https://www.davidtong.org/teaching/statistical-physics/'};
const quantum={title:'David Tong · Quantum mechanics',url:'https://www.davidtong.org/teaching/quantum-mechanics/'};
const ref=(label,chapter,id)=>({label,href:`chapter-${chapter}.html#${id}`});
const step=(title,body,tex,reason)=>({title,body,tex,reason});
const choice=(text,correct,feedback)=>({text,correct,feedback});
const number=(id,prompt,answer,unit,hint,solution,tolerance=.001)=>({id,prompt,answer,unit,hint,solution,tolerance,version:1});

export const foundationLessons=[
{
 id:'measurements-and-units',chapter:0,after:'0.1 A derivative is a local prediction',title:'One distance, two ways to count it',question:'A table is 2 metres long, or 200 centimetres long. What changed when the number changed?',provides:['measurement-units'],
 intuition:s`The table stayed the same. A centimetre is a smaller measuring step, so it takes more of them to span the table. A measurement needs both a number and a unit. Keeping those two parts together will help us read every physical equation in this book.`,
 steps:[
 step('Convert the unit and keep the length',s`One metre contains 100 centimetres. Multiply by a ratio equal to one, written with the new unit on top and the old unit below. The old unit cancels.`,s`2\,\mathrm m\;\frac{100\,\mathrm{cm}}{1\,\mathrm m}=200\,\mathrm{cm}.`,'Changing the unit changes the number used to describe a fixed length.'),
 step('Give a rate its two units',s`If a cart travels 2 metres in 4 seconds, its average speed is distance divided by elapsed time. Using centimetres gives a different number for the same average speed.`,s`\frac{2\,\mathrm m}{4\,\mathrm s}=0.5\,\mathrm{m/s}=50\,\mathrm{cm/s}.`,'Metres per second and centimetres per second describe the same kind of quantity: length divided by time.'),
 step('Count area in two directions',s`A square 2 metres on each side has area 4 square metres. Each side is also 200 centimetres, giving 40,000 square centimetres. Converting a squared length squares the conversion factor.`,s`1\,\mathrm{m^2}=(100\,\mathrm{cm})^2=10{,}000\,\mathrm{cm^2}.`,'An area contains one length factor from each direction, so both factors must be converted.')],
 formal:s`A dimension records the kind of quantity independently of the chosen unit. Write $L$ for the dimension of length and $T$ for time. Then $[x]=L$, $[v]=L/T$, and $[a]=L/T^2$; square brackets here mean “the dimensions of.” If $x=At^2$, matching dimensions gives $[A]=L/T^2$. Dimensional agreement is necessary but does not establish an equation: both $x=At^2$ and $x=2At^2$ have consistent dimensions, but they predict different distances for the same $A$ and $t$. Measurements or other physical reasoning must determine the numerical factor.`,
 requires:[],practice:{prompt:'A cart’s speed is reported as 0.5 metres per second and 50 centimetres per second. Which statement is justified?',choices:[choice('These can be two descriptions of the same speed.',true,'There are 100 centimetres in one metre; both the number and the unit changed together.'),choice('The second speed must be 100 times faster.',false,'Compare quantities in the same unit before comparing their numbers.'),choice('A speed needs only a number, because the units cancel.',false,'Dividing a length by a time leaves length-per-time units.')],hint:'Express both distances in centimetres while keeping the second unchanged.'},
 transfer:number('original',s`A rectangle is 2 metres long and 30 centimetres wide. What is its area in square metres?`,.6,s`$\mathrm{m^2}$`,'Convert the width to metres before multiplying.',s`$30\,\mathrm{cm}=0.30\,\mathrm m$, so the area is $(2\,\mathrm m)(0.30\,\mathrm m)=0.60\,\mathrm{m^2}$.`),
 variants:[number('area-in-centimetres',s`A square has sides of length 0.5 metres. What is its area in square centimetres?`,2500,s`$\mathrm{cm^2}$`,'Convert each side to centimetres, then multiply the two side lengths.',s`Each side is $50\,\mathrm{cm}$, so the area is $(50\,\mathrm{cm})^2=2500\,\mathrm{cm^2}$.`)],sources:[units],takeaway:'A physical measurement is a number with a unit. Convert both together before comparing quantities.'
},
{
 id:'dimensions-before-symbols',chapter:4,after:'4.5 A complete metric calculation in flat polar coordinates',title:'Units belong to coordinates, too',question:'When we replace seconds by the distance light travels in those seconds, how does the interval formula keep giving the same answer?',provides:['coordinate-dimensions'],
 intuition:s`A coordinate is a label with a chosen unit. You can label a journey by elapsed seconds $t$ or by the distance $X=ct$ that light travels in that time. These are two labels for the same events. Write the units before interpreting a coefficient: a dimensionless angle is different from a distance even when both are called coordinates.`,
 steps:[
 step('Require each term to measure the same thing',s`Take the spacetime interval $ds^2=-c^2dt^2+dx^2$, where $x$ is in metres and $t$ in seconds. Each term has units of square metres. The minus sign distinguishes time from space; it does not change the dimensional check.`,s`[g_{tt}]=\mathrm{m^2/s^2},\qquad [g_{xx}]=1.`, 'Terms can be added only when their dimensions agree.'),
 step('Relabel time without changing the interval',s`Set $X=ct$, so $dX=c\,dt$. Substitution gives $ds^2=-dX^2+dx^2$. Now $g_{XX}=-1$. This coefficient changed because its coordinate unit changed. The measured interval did not.`,s`g_{XX}=g_{tt}\left(\frac{dt}{dX}\right)^2=-c^2\frac1{c^2}=-1.`, 'The differential and the metric coefficient transform together.'),
 step('Check a curving coordinate grid',s`On an ordinary Euclidean plane, a tiny angular change $d\theta$ at radius $r$ sweeps length $r\,d\theta$. Pythagoras gives $dl^2=dr^2+r^2d\theta^2$. Thus $g_{\theta\theta}=r^2$ carries length squared, even though $g_{rr}=1$.`,s`[g_{ab}]=\frac{\mathrm{length}^2}{[x^a][x^b]}.`, 'Metric components inherit the units of the chosen labels.'),
 ],
 formal:s`In $ds^2=g_{ab}\,dx^a dx^b$, the whole expression has dimensions of length squared. Thus $[g_{ab}]=L^2/([x^a][x^b])$, where square brackets mean dimensions. Mixed terms follow the same rule. For example, keep $t$ and replace $x$ by $y=x-vt$ for constant speed $v$. Then $dx=dy+v\,dt$ and $ds^2=(v^2-c^2)dt^2+2v\,dt\,dy+dy^2$. The mixed coefficient $g_{ty}=g_{yt}=v$ has speed units; the factor two comes from the two equal terms in the sum. Different component units are consistent because every complete term has square-length units. Setting $c=1$ chooses compatible time and length units; it does not make all coordinates, such as angles, lengths.`,
 requires:[ref('Measurements and units',0,'measurements-and-units'),ref('The spacetime interval',3,'3-3-the-interval-the-quantity-that-refuses-to-change'),ref('Metric and polar lengths',4,'a-metric-converts-labels-into-lengths')],practice:{prompt:s`If $X=ct$, what happens to a fixed pair of events when you replace $t$ by $X$?`,choices:[choice('Their time labels change; the interval is unchanged.',true,'The coordinate differential and metric coefficient compensate exactly.'),choice('Their physical separation grows by a factor of c.',false,'A unit conversion changes a numerical label, not the physical events.'),choice('All metric coefficients become dimensionless in every chart.',false,'Angular coordinates already provide a counterexample: the polar angular coefficient has length squared.')],hint:'Substitute dX = c dt into the interval.'},
 transfer:number('original',s`In $dl^2=dr^2+r^2d\theta^2$, $r=3\,\mathrm m$. What is $g_{\theta\theta}$, in square metres?`,9,s`$\mathrm{m^2}$`,'Read the coefficient multiplying the square of the angular differential.',s`$g_{\theta\theta}=3^2=9\,\mathrm{m^2}$.`),
 variants:[number('rescaled-angle',s`Define $q=2\theta$. At $r=3\,\mathrm m$, what coefficient multiplies $dq^2$ in $dl^2$?`,2.25,s`$\mathrm{m^2}$`,s`Use $d\theta=dq/2$.`,s`$g_{qq}=r^2/4=9/4\,\mathrm{m^2}$. The factor is squared.`)],sources:[gr],takeaway:'A component means nothing until you know the coordinate units and the measurement it participates in.'
},
{
 id:'initial-data-and-oscillations',chapter:0,after:'0.4 A differential equation needs starting measurements',title:'A law needs a starting state',question:'What is missing when someone hands you an equation of motion?',provides:['ode-initial-data'],
 intuition:s`A rule for change is not one particular history. Two identical swings obey the same equation but start at different positions and speeds. A solution must pass two tests: it must obey the differential equation everywhere in its domain, and it must match the stated initial measurements.`,
 steps:[
 step('Solve proportional growth',s`For $dy/dt=ky$, the exponential $y(t)=Ae^{kt}$ works because differentiating it multiplies it by $k$. Initial data $y(0)=y_0$ fix $A=y_0$. Positive $k$ means growth, negative $k$ decay. The product $kt$ must be dimensionless.`,s`y(t)=y_0e^{kt}.`, 'Differentiate the proposed solution and then check the starting value.'),
 step('Build an oscillator from two independent solutions',s`A dot means a time derivative: $\dot x=dx/dt$ and $\ddot x=d^2x/dt^2$. Let $\omega>0$ be a constant with units of inverse time. The oscillator equation $\ddot x+\omega^2x=0$ says that acceleration points toward $x=0$ and grows with displacement. Both $\cos(\omega t)$ and $\sin(\omega t)$ return minus $\omega^2$ times themselves after two derivatives. The constants multiplying them are fixed by $x(0)=x_0$ and $\dot x(0)=v_0$.`,s`x(t)=x_0\cos(\omega t)+\frac{v_0}{\omega}\sin(\omega t),\qquad \omega>0.`, 'The position and velocity supply the two constants in a second-order equation.'),
 step('Rewrite second order as a system',s`Introduce a second variable $v=\dot x$. The pair $\dot x=v$, $\dot v=-\omega^2x$ advances the state $(x,v)$. A numerical method approximates this advance in small time steps; it must be checked against an exact solution and an error estimate.`,s`\frac{d}{dt}\begin{pmatrix}x\\v\end{pmatrix}=\begin{pmatrix}0&1\\-\omega^2&0\end{pmatrix}\begin{pmatrix}x\\v\end{pmatrix}.`, 'Adding a state variable changes the packaging, not the equation.'),
 step('Recognize rotating components',s`The transport system $\dot A=-\Omega B$, $\dot B=\Omega A$ has solution $A=A_0\cos\Omega t-B_0\sin\Omega t$, $B=A_0\sin\Omega t+B_0\cos\Omega t$. Differentiate and verify both equations. Also differentiate $A^2+B^2$: the cross terms cancel.`,s`\frac{d}{dt}(A^2+B^2)=0.`, 'Components can change while the length of the represented arrow stays fixed.')],
 formal:s`Initial and boundary data answer different questions. For $\ddot x+\omega^2x=0$, prescribing $x(0)$ and $\dot x(0)$ determines one solution. Prescribing $x(0)=x(\pi/\omega)=0$ leaves any $x=B\sin\omega t$, so this boundary-value problem is not unique. Existence and uniqueness of a first-order system are local under suitable smoothness conditions on its right-hand side; a solution can still become unbounded in finite time. For example, $\dot y=y^2$ with dimensionless $t$ and $y(0)=1$ gives $y=1/(1-t)$, valid until $t=1$. Always state the interval on which you use it.`,
 requires:[ref('Derivatives',0,'0-1-a-derivative-is-a-local-prediction')],practice:{prompt:s`A particle obeys $\ddot x=-4x$. You know only $x(0)=0$. Is its history determined?`,choices:[choice('No: its initial velocity is still free.',true,'The coefficient of sin(2t) is not fixed by the initial position.'),choice('Yes: it stays at the origin.',false,'That solution requires zero initial velocity too.'),choice('No solution exists at the origin.',false,'Both the stationary solution and moving oscillator solutions can pass through the origin.')],hint:'Try a sine wave with an arbitrary amplitude.'},
 transfer:number('original',s`Use seconds and metres. For $\ddot x+4x=0$, $x(0)=0$, $\dot x(0)=6$, find $x(\pi/4)$.`,3,s`$\mathrm m$`,s`Here $\omega=2\,\mathrm{s^{-1}}$.`,s`$x=3\sin(2t)$, so $x(\pi/4)=3\,\mathrm m$.`),
 variants:[number('turning-point',s`For $\ddot x+9x=0$, $x(0)=2\,\mathrm m$ and $\dot x(0)=0$, find $x(\pi/3\,\mathrm s)$.`,-2,s`$\mathrm m$`,s`The frequency is $3\,\mathrm{s^{-1}}$.`,s`$x=2\cos(3t)$; at this time its phase is $\pi$, so $x=-2\,\mathrm m$.`)],sources:[ode],takeaway:'Check a proposed history by substitution and initial data; neither check replaces the other.'
},
{
 id:'mechanics-energy-and-pressure',chapter:0,after:'0.5 The mechanics we will use',title:'Motion, stored energy, and pressure work',question:'How can a force exchange energy without making energy disappear?',provides:['mechanics-energy'],
 intuition:s`Force measures how momentum changes. Work measures how much energy that force transfers while its point of application moves. A book held motionless can experience a force without receiving mechanical work. These statements concern an ideal point particle or a specified mechanical system; your muscles can consume chemical energy while holding the book.`,
 steps:[
 step('Differentiate kinetic energy',s`For constant mass $m$, momentum is $\mathbf p=m\mathbf v$ and Newton's law is $\dot{\mathbf p}=\mathbf F$. Dot with velocity and use the product rule. Integrating relates work to kinetic-energy change.`,s`\frac{d}{dt}\left(\frac12m v^2\right)=\mathbf F\cdot\mathbf v,\qquad \Delta K=\int\mathbf F\cdot d\mathbf x.`, 'Only the force component along the instantaneous displacement contributes to work.'),
 step('Introduce potential energy with its sign',s`For a time-independent potential $U(\mathbf x)$, define $\mathbf F=-\nabla U$. Along a trajectory the chain rule gives $\dot U=\nabla U\cdot\mathbf v$. Therefore $K+U$ is constant. Near Earth $U=mgz$ predicts downward force $F_z=-mg$.`,s`\frac{d}{dt}(K+U)=0.`, 'A loss of potential energy balances a gain of kinetic energy under the stated conservative force.'),
 step('Use a piston to define pressure work',s`Pressure $p$ is normal force per unit area. A gas pushes a piston of area $A$ outward by $dx$. It does work $pA\,dx=p\,dV$ on the surroundings. In an insulated expansion there is no heat transfer. Assume the piston moves slowly enough for the gas to pass through near-equilibrium states, with negligible friction; this is the quasistatic limit used here. Its internal energy $E$, the energy stored in its microscopic motion and interactions, decreases by the work done. Heat supplied to the gas, called $\delta Q$, changes the bookkeeping.`,s`dE=\delta Q-p\,dV.`, 'The sign follows which system does the work; pressure has the same dimensions as energy density.')],
 formal:s`Potential energy has an arbitrary zero. Replacing $U$ by $U+C$ for constant $C$ leaves $\mathbf F=-\nabla U$ unchanged and preserves every energy difference. It changes the bookkeeping reference, not the motion. Pressure work also provides a useful unit check: $1\,\mathrm{Pa}=1\,\mathrm{N/m^2}=1\,\mathrm{J/m^3}$. Thus pressure times a volume change has energy units. “Insulated” means no heat transfer; it does not prevent work through a moving boundary. The symbol $\delta Q$ denotes energy transferred as heat during a process, while $dE$ is the change in the system's stored energy. Heat is a transfer, not an extra stored quantity to add to $E$.`,
 requires:[ref('Chain rule',0,'0-2-partial-derivatives-change-one-input-at-a-time')],practice:{prompt:'In an insulated quasistatic expansion against positive pressure, what happens to the gas’s internal energy?',choices:[choice('It decreases because the gas does work.',true,'With no heat supplied, dE = −p dV and dV is positive.'),choice('It increases because its volume increases.',false,'Volume is not energy. The sign follows the direction of energy transfer.'),choice('It is constant because insulation prevents all transfers.',false,'Insulation blocks heat transfer; mechanical work can still cross the boundary.')],hint:'Choose the gas as the system and track where the piston’s work comes from.'},
 transfer:number('original',s`A $2\,\mathrm{kg}$ particle falls from rest through $5\,\mathrm m$ in constant $g=10\,\mathrm{m/s^2}$, without drag. Find its final speed.`,10,s`$\mathrm{m/s}$`,s`Set the lost $mgh$ equal to the gained $mv^2/2$.`,s`$v=\sqrt{2gh}=\sqrt{100}=10\,\mathrm{m/s}$. The mass cancels.`),
 variants:[number('pressure-work',s`An insulated gas expands quasistatically by $0.03\,\mathrm{m^3}$ against constant pressure $200\,\mathrm{Pa}$. Find its internal-energy change.`,-6,s`$\mathrm J$`,s`Use $\Delta E=-p\Delta V$.`,s`$\Delta E=-200(0.03)=-6\,\mathrm J$.`)],sources:[gr,thermal],takeaway:'Conservation laws become useful when the system, force law, and direction of energy transfer are explicit.'
},
{
 id:'hyperbolas-and-rapidity',chapter:3,after:'3.3 The spacetime interval',title:'Build a boost from exponentials',question:'Can we combine two changes of moving observer by adding a single parameter?',provides:['hyperbolic-functions'],
 intuition:s`Circular functions parameterize $x^2+y^2=1$. A boost preserves a difference of squares, so its natural curve is a hyperbola. We can construct the needed functions from exponentials rather than memorize another family of mysterious names.`,
 steps:[
 step('Define the functions',s`For a dimensionless real number $\eta$, define $\cosh\eta=(e^\eta+e^{-\eta})/2$ and $\sinh\eta=(e^\eta-e^{-\eta})/2$. Squaring and subtracting cancels the growing and decaying terms.`,s`\cosh^2\eta-\sinh^2\eta=1.`, 'The identity is an algebraic consequence of the definitions.'),
 step('Differentiate and form the velocity ratio',s`Differentiating the exponentials gives $(\sinh\eta)'=\cosh\eta$ and $(\cosh\eta)'=\sinh\eta$. Define $\tanh\eta=\sinh\eta/\cosh\eta$. For real finite $\eta$ its magnitude is below one. Write $\beta=v/c$ for velocity in units of light speed; the parameter $\eta$ with $\beta=\tanh\eta$ is called rapidity.`,s`\beta=\tanh\eta,\qquad \gamma=\cosh\eta,\qquad \gamma\beta=\sinh\eta.`, 'The hyperbola identity yields γ²(1−β²)=1 with the positive future-directed branch.'),
 step('Transform an event',s`For a primed frame moving at $v=\beta c$ in the positive $x$ direction, use $ct'=ct\cosh\eta-x\sinh\eta$ and $x'=x\cosh\eta-ct\sinh\eta$. Expand $-(ct')^2+(x')^2$: the cross terms cancel and the original interval remains.`,s`\begin{pmatrix}ct'\\x'\end{pmatrix}=\begin{pmatrix}\cosh\eta&-\sinh\eta\\-\sinh\eta&\cosh\eta\end{pmatrix}\begin{pmatrix}ct\\x\end{pmatrix}.`, 'The transformation is chosen to preserve the spacetime interval and the stated frame direction.'),
 step('Invert when a measurement gives the velocity',s`Solving $\beta=(e^{2\eta}-1)/(e^{2\eta}+1)$ gives $\eta=\tfrac12\ln[(1+\beta)/(1-\beta)]$. This is $\operatorname{artanh}\beta$. Similarly, solving $y=\sinh\eta$ yields $\operatorname{arsinh}y=\ln(y+\sqrt{1+y^2})$. Its derivative is $1/\sqrt{1+y^2}$, which will evaluate a light-delay integral.`,s`\frac{d}{dy}\operatorname{arsinh}y=\frac1{\sqrt{1+y^2}}.`, 'An inverse function answers which parameter produced a measured value.')],
 formal:s`Multiply two collinear boost matrices and use the exponential definitions to obtain the addition formulas: their rapidities add. Velocities therefore combine as $(\beta_1+\beta_2)/(1+\beta_1\beta_2)$, not by ordinary addition. This simple additive parameter applies to collinear boosts. Noncollinear boosts also produce a spatial rotation; treating all boosts as commuting is a different and incorrect generalization.`,
 requires:[ref('Exponentials and initial data',0,'initial-data-and-oscillations'),ref('Lorentz transformations',3,'3-2-deriving-a-lorentz-boost-without-pulling-a-rabbit-from-a-matrix')],practice:{prompt:'What does adding two collinear rapidities accomplish?',choices:[choice('It composes the boosts while keeping subluminal speeds subluminal.',true,'The hyperbolic tangent addition formula gives relativistic velocity addition.'),choice('It adds the two ordinary speeds.',false,'Rapidity and speed are different parameters.'),choice('It implies every pair of boosts commutes.',false,'Different spatial directions introduce rotations; the collinear assumption matters.')],hint:'Write velocity as c times tanh of the rapidity.'},
 transfer:number('original',s`If $e^\eta=2$, calculate $v/c=\tanh\eta$.`,.6,'',s`Use $e^{-\eta}=1/2$ in the definitions.`,s`$\tanh\eta=(2-1/2)/(2+1/2)=3/5$.`),
 variants:[number('compose-boosts',s`Compose two boosts in the same direction, each with $v/c=3/5$. Find the resulting velocity divided by $c$.`,15/17,'',s`Use $(\beta_1+\beta_2)/(1+\beta_1\beta_2)$.`,s`$(6/5)/(34/25)=15/17\simeq0.88235$.`)],sources:[gr],takeaway:'Rapidity adds for collinear boosts because it is the parameter of a hyperbola-preserving transformation.'
},
{
 id:'flows-that-do-not-commute',chapter:7,after:"7.2 Two requirements that select ordinary GR's connection",title:'Do the two moves in the other order',question:'If moving right changes how fast you can move upward, does the order of the moves matter?',provides:['lie-bracket'],
 intuition:s`Let $X$ say “move right at unit speed” and $Y$ say “move upward at a speed equal to your x coordinate.” Moving right first changes the speed of the upward move. Reversing the order reaches a different point. This is a property of the two vector fields, even on a flat plane.`,
 steps:[
 step('Treat a vector field as differentiation',s`For a scalar function $f$, write $Xf=X^a\partial_af$. Define the bracket by the difference between two ordered derivatives. Expanding with the product rule cancels the terms with second derivatives of $f$.`,s`[X,Y]f=X(Yf)-Y(Xf),\quad [X,Y]^a=X^b\partial_bY^a-Y^b\partial_bX^a.`, 'Ordinary mixed partial derivatives of a smooth scalar commute in a coordinate chart.'),
 step('Calculate the simplest nonzero example',s`On a plane with dimensionless labels, take $X=\partial_x$ and $Y=x\partial_y$. Only the x derivative of Y’s y component is nonzero.`,s`[\partial_x,x\partial_y]=\partial_y.`, 'The coefficient x changes when X moves you.'),
 step('Check it by actually composing moves',s`Starting at $(x,y)$, move along $X$ for parameter $\epsilon$, then along $Y$ for $\epsilon$. The endpoint is $(x+\epsilon,y+\epsilon x+\epsilon^2)$. Reversing these two moves gives $(x+\epsilon,y+\epsilon x)$. Their difference is $\epsilon^2\partial_y$.`,s`\Delta y=\epsilon^2.`, 'The endpoint comparison fixes the sign; a differently ordered closed commutator loop may carry the opposite sign.'),
 ],
 formal:s`Coordinate basis fields satisfy $[\partial_a,\partial_b]=0$; an arbitrary frame need not. The torsion of a connection is $T(X,Y)=\nabla_XY-\nabla_YX-[X,Y]$. Torsion-free means this expression vanishes. It does not mean the bracket of every pair of fields vanishes.`,
 requires:[ref('Directional derivatives',2,'coordinates-change-measurements-do-not')],practice:{prompt:s`On a flat plane, does $[\partial_x,x\partial_y]\ne0$ prove curvature?`,choices:[choice('No. The field coefficient changes across the plane.',true,'Noncommuting chosen flows occur in flat geometry; curvature requires the covariant comparison including the bracket correction.'),choice('Yes. Every noncommuting operation is curvature.',false,'This example uses only ordinary derivatives on the Euclidean plane.'),choice('It proves torsion even without choosing a connection.',false,'Torsion is defined using a connection as well as the bracket.')],hint:'Which geometrical structure has actually been specified?'},
 transfer:number('original',s`For $X=\partial_x$ and $Y=x^2\partial_y$, find the y component of $[X,Y]$ at $x=3$.`,6,'',s`Differentiate $x^2$ with respect to $x$.`,s`$[X,Y]=2x\partial_y$, so the component is 6.`),
 variants:[number('reverse-fields',s`For $X=3x\partial_y$ and $Y=\partial_x$, find the y component of $[X,Y]$.`,-3,'',s`The nonzero term now comes from $-Y^b\partial_bX^a$.`,s`$[X,Y]=-3\partial_y$. Reversing field order reverses the bracket.`)],sources:[gr],takeaway:'A noncommuting frame is not automatically curved or torsionful; calculate the appropriate geometric object.'
},
{
 id:'fields-carry-energy',chapter:11,after:'11.6 Two field examples: scalar waves and electromagnetism',title:'A field has motion and stored energy at every point',question:'Where is energy while a wave crosses an otherwise empty region?',provides:['field-energy'],
 intuition:s`A classical scalar field assigns one number to each event: $\phi(t,\mathbf x)$. A stretched string is a useful one-dimensional model. Its displacement changes with time, and neighboring points can have different displacements. Motion stores kinetic energy; spatial variation stores elastic energy. A field replaces a finite list of particle coordinates by a value at each position. In the following calculation, subscripts denote partial derivatives: $\phi_t=\partial\phi/\partial t$ and $\phi_x=\partial\phi/\partial x$.`,
 steps:[
 step('Turn a string into a field model',s`For small transverse slopes on a string with constant tension $\mathcal T$ and mass per length $\mu$, a segment has kinetic energy per length $\mu\phi_t^2/2$. Expanding its length $\sqrt{1+\phi_x^2}\,dx$ gives extra length $\phi_x^2dx/2$ and elastic energy per length $\mathcal T\phi_x^2/2$. The vertical tension components at the segment’s ends differ by $\mathcal T[\phi_x(x+dx)-\phi_x(x)]\simeq\mathcal T\phi_{xx}dx$. Equating this force to mass $\mu\,dx$ times acceleration $\phi_{tt}$ gives $\mu\phi_{tt}=\mathcal T\phi_{xx}$.`,s`e=\frac\mu2\phi_t^2+\frac{\mathcal T}2\phi_x^2,\qquad c_s^2=\mathcal T/\mu.`, 'The approximation requires small slopes; this wave speed is a property of the string.'),
 step('Derive the energy current',s`Differentiate $e$ with respect to time and substitute the string equation. The two terms combine into an x derivative. Define flux $j=-\mathcal T\phi_t\phi_x$ so local energy conservation reads $\partial_te+\partial_xj=0$.`,s`\partial_te=\mathcal T\partial_x(\phi_t\phi_x),\qquad j=-\mathcal T\phi_t\phi_x.`, 'Energy lost from a short segment leaves through its ends; local conservation is a flux balance.'),
 step('Meet electric and magnetic fields',s`An electric field $\mathbf E$ supplies force per charge on a stationary test charge $q$. A magnetic field $\mathbf B$ contributes $q\mathbf v\times\mathbf B$ to a moving charge’s force. The cross product $\times$ gives a vector perpendicular to its inputs, with magnitude equal to the product of their lengths times the sine of their angle; its direction follows the right-hand rule. Maxwell’s theory supplies a separate physical model for these fields. In SI vacuum it assigns energy density $u=\epsilon_0 E^2/2+B^2/(2\mu_0)$ and energy-flux vector $\mathbf S=\mathbf E\times\mathbf B/\mu_0$. Here $\epsilon_0,\mu_0$ are the vacuum electromagnetic constants and $c^2=1/(\epsilon_0\mu_0)$.`,s`\partial_tu+\nabla\cdot\mathbf S=-\mathbf J\cdot\mathbf E.`, 'The charge-current density J measures charge crossing unit area per time, in amperes per square metre. The right side is minus the power per volume delivered to this current; energy transferred to matter leaves the field.')],
 formal:s`For a plane electromagnetic wave in vacuum, $\mathbf E\perp\mathbf B$, $B=E/c$, and both fields are perpendicular to the propagation direction. Substituting gives $u=\epsilon_0E^2$ and $|\mathbf S|=cu$. The two equal terms in $u$ are electric and magnetic contributions. In a local orthonormal frame using $x^0=ct$, $T^{00}=u$ and $T^{0i}=S_i/c$. Chapter 13 develops the field action and its variations. The Maxwell action below is a preview of that construction; the energy/flux interpretation now has a direct definition. The string’s $c_s$ need not equal the invariant light speed $c$.`,
 requires:[ref('Work and energy',0,'mechanics-energy-and-pressure'),ref('Flux and divergence',0,'0-7-flux-and-divergence-with-a-box-before-a-theorem')],practice:{prompt:'Why does a traveling string wave transport energy?',choices:[choice('The local energy change is balanced by flux through neighboring points.',true,'The wave equation gives an explicit continuity equation and energy current.'),choice('Because the same piece of string travels the whole distance.',false,'Material points oscillate; the disturbance and energy propagate along the string.'),choice('Because every wave in every medium travels at c.',false,'The string wave speed depends on tension and mass per length.')],hint:'Distinguish the motion of the disturbance from the motion of the material.'},
 transfer:number('original',s`A vacuum plane electromagnetic wave has electric energy density $2\,\mathrm{J/m^3}$. Find its total instantaneous energy density.`,4,s`$\mathrm{J/m^3}$`,'Include the equal magnetic contribution.',s`$u=u_E+u_B=2+2=4\,\mathrm{J/m^3}$.`),
 variants:[number('string-flux',s`For a string with $\mathcal T=10\,\mathrm N$, at one event $\phi_t=2\,\mathrm{m/s}$ and $\phi_x=-0.1$. Find the energy flux toward positive x.`,2,s`$\mathrm W$`,s`Use $j=-\mathcal T\phi_t\phi_x$.`,s`$j=-10(2)(-0.1)=2\,\mathrm W$.`)],sources:[em],takeaway:'A stress tensor includes energy density and energy flow; empty of particles does not mean empty of fields.'
},
{
 id:'poisson-from-a-flux',chapter:12,after:'12.4 Matching Newtonian gravity',title:'Find the source by enclosing it',question:'How can a field have zero divergence outside a star and still reveal the star’s mass?',provides:['poisson-sources'],
 intuition:s`The gravitational field outside a spherical mass weakens as area grows. The outward flux of its inward-pointing acceleration stays negative and constant on every enclosing sphere. A local equation must reproduce that integral fact, including at a source that is too small to resolve.`,
 steps:[
 step('Fix the normalization on a sphere',s`For point mass $M$ at the origin, Newtonian acceleration is $\mathbf g=-G_NM\mathbf e_r/r^2$. A sphere has area $4\pi r^2$ and outward normal $\mathbf e_r$. Its flux is independent of radius.`,s`\oint\mathbf g\cdot d\mathbf A=-4\pi G_NM.`, 'The inverse-square falloff cancels the growth of sphere area.'),
 step('Pass from total mass to density',s`For smooth mass density $\rho$, enclose a volume $V$ and write $M_V=\int_V\rho\,d^3x$. The divergence theorem replaces the boundary flux by $\int_V\nabla\cdot\mathbf g\,d^3x$. Since arbitrary volumes must agree, $\nabla\cdot\mathbf g=-4\pi G_N\rho$. With $\mathbf g=-\nabla\Phi$, obtain Poisson’s equation.`,s`\nabla^2\Phi=4\pi G_N\rho.`, 'A relation for every small volume determines the local density relation.'),
 step('Keep the point source',s`For $\Phi=-G_NM/r$, direct differentiation gives $\nabla^2\Phi=0$ at $r>0$. That calculation excludes the origin. Define the three-dimensional delta distribution by $\int\delta^{(3)}(\mathbf x)f(\mathbf x)d^3x=f(0)$ for smooth compactly supported test functions. The source has mass density $M\delta^{(3)}(\mathbf x)$.`,s`\nabla^2\frac1r=-4\pi\delta^{(3)}(\mathbf x).`, 'The distribution records the missing flux at the puncture; it is not an ordinary function of infinite height.')],
 formal:s`For a smooth localized density and the isolated boundary condition $\Phi\to0$ at infinity, superpose point-source potentials: $\Phi(\mathbf x)=-G_N\int\rho(\mathbf x')/|\mathbf x-\mathbf x'|\,d^3x'$. Applying the distributional Laplacian collapses the integral to $4\pi G_N\rho(\mathbf x)$. The inverse-distance kernel is a Green function for this boundary problem. Different boundaries can require an additional harmonic function with $\nabla^2\Phi_h=0$; the differential equation alone does not choose it.`,
 requires:[ref('Flux and divergence',0,'0-7-flux-and-divergence-with-a-box-before-a-theorem'),ref('Mechanics',0,'mechanics-energy-and-pressure')],practice:{prompt:s`You find $\nabla^2(-G_NM/r)=0$ for $r>0$. What can you conclude?`,choices:[choice('The region away from the origin is vacuum.',true,'The computation excludes the singular source, whose mass is recovered by enclosing flux.'),choice('There is no mass anywhere.',false,'The omitted origin carries a distributional source.'),choice('The inverse-square field violates Poisson’s equation.',false,'Its distributional Laplacian has exactly the point-source normalization.')],hint:'Ask which points were in the domain of the differentiation.'},
 transfer:number('original',s`Inside a uniform-density ball, write $\Phi=ar^2+b$. Since $\nabla^2r^2=6$, what is $a/(\pi G_N\rho)$?`,2/3,'',s`Set $6a=4\pi G_N\rho$.`,s`$a=2\pi G_N\rho/3$, so the requested ratio is $2/3$.`),
 variants:[number('enclosed-fraction',s`A uniform-density ball has total radius $R$ and mass $M$. What fraction of $M$ is enclosed at radius $R/2$?`,.125,'',s`Mass is proportional to volume, hence radius cubed.`,s`$M(R/2)/M=(1/2)^3=1/8$. This enclosed mass determines the spherical Newtonian acceleration there.`)],sources:[gr,em],takeaway:'Vacuum at a point and the total source enclosed by a surface are different statements.'
},
{
 id:'variations-and-boundary-data',chapter:13,after:'13.1 From an ordinary derivative to a variation',title:'Say what is allowed to move',question:'Why is a boundary condition part of a variational problem, rather than a footnote?',provides:['admissible-variations'],
 intuition:s`To ask whether a quantity is stationary, first say which changes are allowed. The lowest point in a room and the lowest point on a particular staircase answer different questions. A variation of a path is a small change of the whole function, with specified restrictions at its endpoints.`,
 steps:[
 step('Perturb an entire path',s`For $S[x]=\int_{t_0}^{t_1}(m\dot x^2/2-U(x))dt$, consider $x_\epsilon=x+\epsilon\eta$. Here $\eta(t)$ is any smooth allowed displacement and $\delta S$ means $dS[x_\epsilon]/d\epsilon$ at zero. Differentiate the integrand and integrate the kinetic term by parts.`,s`\delta S=[m\dot x\eta]_{t_0}^{t_1}-\int_{t_0}^{t_1}(m\ddot x+U'(x))\eta\,dt.`, 'Integration by parts separates a bulk equation from the endpoint contribution.'),
 step('Use fixed endpoints honestly',s`If both endpoint positions are fixed, $\eta(t_0)=\eta(t_1)=0$. Arbitrary interior variations then require $m\ddot x+U'=0$. If an endpoint position is free, its variation need not vanish: the boundary term gives a separate condition.`,s`\eta(t_0)=\eta(t_1)=0\quad\not\Rightarrow\quad\dot\eta(t_0)=\dot\eta(t_1)=0.`, 'A function can vanish at an endpoint while its derivative there is nonzero.'),
 step('Constrain a variation geometrically',s`To make $f(x,y)=x+y$ stationary on the unit circle, allowed displacements satisfy $x\delta x+y\delta y=0$. Thus $\nabla f$ must be parallel to the normal $(x,y)$. Introduce a multiplier $\lambda$ and solve $\nabla[f-\lambda(x^2+y^2-1)]=0$ together with the constraint.`,s`1=2\lambda x,\qquad1=2\lambda y,\qquad x^2+y^2=1.`, 'The multiplier enforces stationarity only along the permitted tangent directions.')],
 formal:s`The constrained example gives $x=y=\pm1/\sqrt2$, with maximum and minimum values $\pm\sqrt2$. Stationary does not select the minimum automatically. A boundary term added to an action can change the admissible boundary problem without changing its bulk Euler–Lagrange equation. This becomes essential for the Einstein–Hilbert action, whose variation contains derivatives of the metric variation. Fixing the metric at the boundary alone does not set those derivatives to zero. Chapter 14 develops the required geometric boundary term.`,
 requires:[ref('Energy and forces',0,'mechanics-energy-and-pressure'),ref('Oscillator',0,'initial-data-and-oscillations')],practice:{prompt:s`A variation satisfies $\eta(0)=\eta(1)=0$. Must $\eta'(0)$ vanish?`,choices:[choice(s`No: $\eta=t(1-t)$ is a counterexample.`,true,'This function vanishes at both endpoints and has derivative 1 at zero.'),choice('Yes, because the endpoint is fixed.',false,'Fixing a function value does not also fix its slope.'),choice('Only if the action is gravitational.',false,'This is already a statement about ordinary differentiable functions.')],hint:'Try the simplest polynomial with zeros at both endpoints.'},
 transfer:number('original',s`For $L=m\dot x^2/2-kx^2/2$, take $m=2\,\mathrm{kg}$, $k=8\,\mathrm{N/m}$ and $x=3\,\mathrm m$. Find $\ddot x$.`,-12,s`$\mathrm{m/s^2}$`,s`The Euler–Lagrange equation is $m\ddot x+kx=0$.`,s`$\ddot x=-(8/2)3=-12\,\mathrm{m/s^2}$.`),
 variants:[number('endpoint-derivative',s`For $\eta(t)=2t(1-t)$ with dimensionless t, calculate $\eta'(1)$.`,-2,'',s`Differentiate before substituting the endpoint.`,s`$\eta'=2-4t$, so $\eta'(1)=-2$ despite $\eta(1)=0$.`)],sources:[gr],takeaway:'Stationarity means no first-order change along the allowed variations; the allowed variations are part of the problem.'
},
{
 id:'waves-modes-and-green-functions',chapter:18,after:"18.5 Retarded solutions: the field receives yesterday's news",title:'From an initial ripple to a retarded field',question:'Which mathematical step chooses a wave arriving from the source, rather than one arriving from the future?',provides:['wave-initial-data'],
 intuition:s`A wave equation tells disturbances how to propagate, but does not decide which disturbance occurred. Initial data specify an initial displacement and velocity. A Green function instead builds a response from an elementary source. The retarded choice says that the response occurs after the source.`,
 steps:[
 step('Propagate initial data in one space dimension',s`The equation $u_{tt}=c^2u_{xx}$ admits right-moving $F(x-ct)$ and left-moving $G(x+ct)$. With $u(x,0)=f(x)$ and $u_t(x,0)=g(x)$ on the whole line, solving for their sums and derivatives gives d’Alembert’s formula.`,s`u(x,t)=\frac{f(x-ct)+f(x+ct)}2+\frac1{2c}\int_{x-ct}^{x+ct}g(s)\,ds.`, 'Differentiation checks the equation and both initial conditions; the integration interval exposes finite propagation speed.'),
 step('Package oscillations with complex numbers',s`Define $i^2=-1$ and $e^{i\theta}=\cos\theta+i\sin\theta$. The real part of $Ae^{i(kx-\omega t)}$ is a real wave. Substitution gives $\omega^2=c^2k^2$. Linear combinations also solve the linear equation, so a packet can be assembled from many wave numbers k.`,s`u=\operatorname{Re}\!\int a(k)e^{i[kx-\omega(k)t]}dk.`, 'Complex notation packages phase; the physical field in this example is real.'),
 step('Specify the kernel and its boundary condition',s`In three flat spatial dimensions let $L=\nabla^2-c^{-2}\partial_t^2$ and $L\psi=-4\pi f$. Its retarded point-source kernel is $G_{\rm ret}=\delta(t-t'-R/c)/R$, with $R=|\mathbf x-\mathbf x'|$ and $LG_{\rm ret}=-4\pi\delta(t-t')\delta^{(3)}(\mathbf x-\mathbf x')$. Integrating it against the source collapses the time integral.`,s`\psi(t,\mathbf x)=\int\frac{f(t-R/c,\mathbf x')}{R}\,d^3x'.`, 'The kernel normalization and retarded support specify which inverse of the differential operator is meant.')],
 formal:s`The kernel identity is understood distributionally: integrate it against a smooth test function, integrate derivatives by parts, and the shrinking sphere around $R=0$ supplies the same $-4\pi$ normalization as the Poisson kernel. Away from the source, radial propagation makes $R\psi$ obey a one-dimensional wave equation. A homogeneous solution can still be added; “retarded solution” here specifies the sourced response without an independently supplied incoming wave. In a dispersive medium $\omega(k)$ need not equal $c|k|$; phase velocity $\omega/k$ and narrow-packet group velocity $d\omega/dk$ differ. Neither alone universally determines front or signal speed. Curved-spacetime Green functions can also have support inside the light cone, so the flat-space formula must not be transplanted unchanged.`,
 requires:[ref('Initial data',0,'initial-data-and-oscillations'),ref('Point sources and Poisson',12,'poisson-from-a-flux'),ref('Field energy',11,'fields-carry-energy')],practice:{prompt:'Does the wave equation alone force every solution to be retarded?',choices:[choice('No. Initial or boundary conditions select the response.',true,'The differential operator allows homogeneous waves and other Green-function boundary conditions.'),choice('Yes. The word wave means retarded.',false,'The equation also admits advanced kernels and incoming homogeneous solutions mathematically.'),choice('No. All wave solutions transmit information instantaneously.',false,'Finite propagation and the choice of sourced response are separate issues.')],hint:'Try adding a free wave to a particular sourced solution.'},
 transfer:number('original',s`In dimensionless units $c=1$, take $f(x)=x^2$ and $g(x)=0$. Use d’Alembert’s formula to find $u(0,2)$.`,4,'',s`Average $f(-2)$ and $f(2)$.`,s`$u(0,2)=(4+4)/2=4$. The solution is $u=x^2+t^2$ and satisfies $u_{tt}=u_{xx}=2$.`),
 variants:[number('initial-velocity',s`With dimensionless $c=1$, $f(x)=0$, and $g(x)=3$ on the line, find $u(0,2)$.`,6,'',s`Only the integral of initial velocity remains.`,s`$u(0,2)=\tfrac12\int_{-2}^{2}3\,ds=6$.`)],sources:[em,ode],takeaway:'The operator, source normalization, and initial or boundary conditions jointly define a wave prediction.'
},
{
 id:'causal-domains',chapter:17,after:'17.6 An event horizon knows about the future',title:'Which initial data can determine this event?',question:'Why does a local light cone not settle every question about predictability?',provides:['global-causality'],
 intuition:s`Suppose you know all the initial measurements only on a finite interval. You can predict an event only if every possible incoming causal influence traces back to that interval. Following one convenient light ray is not enough; an unaccounted path could carry missing information.`,
 steps:[
 step('Separate timelike and causal reachability',s`The chronological future $I^+(p)$ consists of events reached from p by future-directed timelike curves. The causal future $J^+(p)$ also allows null curves (and conventionally p itself). In ordinary Minkowski spacetime these are the interior and the closed interior of the future light cone. Time orientation means we have consistently chosen which half-cone is future.`,s`I^+(p)\subseteq J^+(p).`, 'A massive traveler follows a timelike path; a light signal can run along the boundary.'),
 step('Draw the domain of an interval',s`Use $c=1$ and an initial segment $S=\{t=0,-L\le x\le L\}$ in 1+1 Minkowski spacetime. An event with $0\le t\le L$ has past-null intersections $x-t$ and $x+t$ with the initial line. Both must remain inside the segment.`,s`D^+(S)=\{(t,x):0\le t\le L,\ |x|\le L-t\}.`, 'Every past-inextendible causal curve from a point in this triangle must meet the initial segment.'),
 step('State the global requirement',s`An inextendible causal curve cannot be continued further as a causal curve in the spacetime under discussion. A Cauchy surface meets every inextendible causal curve exactly once. A spacetime admitting such a surface is globally hyperbolic, using the equivalent standard characterization for smooth time-oriented Lorentzian spacetimes. An achronal set contains no two points joined by a timelike curve; achronal does not by itself mean Cauchy.`,s`D(S)=D^+(S)\cup D^-(S).`, 'Cauchy data must intercept every possible causal history, not merely form a visually level slice.')],
 formal:s`The future domain of dependence $D^+(S)$ is defined by **every past-inextendible causal curve** through the event meeting S. This quantifier is essential. A puncture removed from spacetime can create causal curves that end at the missing point relative to the remaining manifold, reducing the domain. Geodesic completeness is another definition: an affinely parameterized geodesic can be continued to arbitrary parameter values. For timelike geodesics proper time supplies an affine parameter up to a constant scale. Finite affine length of an inextendible geodesic is incompleteness; it need not be diagnosed by a divergent scalar curvature. These are the concepts needed before Chapter 22’s theorem discussion.`,
 requires:[ref('Causal maps',17,'kruskal-and-causal-maps')],practice:{prompt:'A spacelike slice is drawn on a causal diagram. Does its spacelike character prove it is Cauchy?',choices:[choice('No. It must meet every inextendible causal curve exactly once.',true,'A finite piece of a spacelike slice already fails to intercept histories outside its domain.'),choice('Yes. Spacelike and Cauchy mean the same thing.',false,'Spacelike is a local geometric property; the Cauchy condition is global.'),choice('Only if the coordinate time on it is zero.',false,'A coordinate label does not decide whether all causal histories cross the slice.')],hint:'Try a finite segment of the t = 0 line.'},
 transfer:number('original',s`For initial data on $[-5,5]$ at $t=0$ with $c=1$, what is the half-width in x of $D^+(S)$ at $t=2$?`,3,'',s`Each inward null boundary moves one unit per unit time.`,s`$L-t=5-2=3$. The available interval is $[-3,3]$.`),
 variants:[number('latest-prediction',s`For initial data on $[-8,8]$ with $c=1$, at what latest future time is the event at $x=3$ still in $D^+(S)$?`,5,'',s`Require $|x|\le L-t$.`,s`$3\le8-t$ gives $t\le5$.`)],sources:[gr],takeaway:'Predictability requires control of every possible incoming causal history.'
},
{
 id:'probability-temperature-and-entropy',chapter:22,after:'22.7 A horizon gets a temperature',title:'What temperature adds to a theory',question:'What does a thermal probability distribution know that a spacetime metric alone does not?',provides:['thermal-states'],
 intuition:s`A macrostate specifies coarse measurements such as energy and volume. A microstate specifies the finer physical configuration. A probability distribution assigns nonnegative numbers $p_i$ to the allowed microstates with $\sum_i p_i=1$. An average measurement of a quantity $A_i$ is $\langle A\rangle=\sum_i p_iA_i$. The distribution is extra physical information.`,
 steps:[
 step('Measure uncertainty with entropy',s`For probabilities $p_i$, define $S=-k_B\sum_i p_i\ln p_i$, with $0\ln0$ interpreted by continuity as zero. $k_B$ converts dimensionless logarithmic uncertainty into entropy units. For N equally likely states, substitution gives $S=k_B\ln N$.`,s`p_i=1/N\quad\Longrightarrow\quad S=k_B\ln N.`, 'Entropy depends on the probabilities and the chosen description of states.'),
 step('Find the canonical distribution',s`Maximize $S/k_B$ with fixed normalization and mean energy. Multipliers give $-\ln p_i-1-\alpha-\beta E_i=0$, hence $p_i=e^{-\beta E_i}/Z$, where $Z=\sum_j e^{-\beta E_j}$ normalizes the probabilities. For an equilibrium heat reservoir, $\beta=1/(k_BT)$.`,s`p_i=\frac{e^{-E_i/(k_BT)}}Z,\qquad \frac{p_j}{p_i}=e^{-(E_j-E_i)/(k_BT)}.`, 'The energy difference relative to the thermal energy kBT sets the population ratio.'),
 step('Relate entropy to energy transfer',s`Reversible heat exchange obeys $dS=\delta Q_{\rm rev}/T$. With fixed particle number, pressure work gives $dE=T\,dS-p\,dV$. Irreversible heat transfer does not justify replacing the full entropy balance by $\delta Q/T$ with an arbitrary system temperature.`,s`\left(\frac{\partial S}{\partial E}\right)_{V,N}=\frac1T.`, 'Thermodynamic derivatives specify what is held fixed.')],
 formal:s`For two states with energies 0 and $\Delta>0$, $Z=1+e^{-\Delta/(k_BT)}$. At high positive temperature their probabilities approach one half; at low positive temperature the lower state dominates. Classical thermodynamics and probability do not by themselves imply that a black hole emits particles. The Hawking calculation additionally uses quantum fields, a choice of state, and a regularity or collapse condition. Euclidean periodicity supplies a consistency relation between a candidate thermal state and the near-horizon geometry; it is not the entire flux calculation.`,
 requires:[ref('Pressure work',0,'mechanics-energy-and-pressure'),ref('Constrained variations',13,'variations-and-boundary-data')],practice:{prompt:'Does a metric by itself specify a quantum field’s thermal population?',choices:[choice('No. The field theory and state are additional information.',true,'The same geometry can support distinct physical states with different observations.'),choice('Yes. Geometry replaces the probability distribution.',false,'Geometrical regularity can constrain a state, but does not erase the need to specify one.'),choice('Temperature is simply another coordinate time.',false,'Temperature controls energy populations; a coordinate labels events.')],hint:'Separate the arena, dynamical law, and state.'},
 transfer:number('original',s`A system has four equally likely states. Find $S/(k_B\ln2)$.`,2,'',s`Use $S=k_B\ln4$.`,s`$\ln4/\ln2=2$.`),
 variants:[number('thermal-populations',s`Two energy levels differ by $\Delta=k_BT\ln3$. Find the higher-energy population divided by the lower-energy population.`,1/3,'',s`Use $e^{-\Delta/(k_BT)}$.`,s`$e^{-\ln3}=1/3$.`)],sources:[thermal],takeaway:'Temperature is a property of a specified physical state, and entropy depends on the information retained.'
},
{
 id:'quantum-states-and-reduced-information',chapter:22,after:'22.7 A horizon gets a temperature',title:'A pure whole can have an uncertain part',question:'How can losing access to one subsystem create entropy without destroying the whole quantum state?',provides:['quantum-states'],
 intuition:s`A finite quantum system is described by a normalized vector of complex amplitudes. In an orthonormal basis $|i\rangle$, write $|\psi\rangle=\sum_i a_i|i\rangle$ with $\sum_i|a_i|^2=1$. The probability of basis outcome i is $|a_i|^2$. This is a postulate of quantum mechanics, separate from GR. The notation $\langle\psi|$ means the conjugate transpose of $|\psi\rangle$.`,
 steps:[
 step('Turn a vector into a density matrix',s`For a known pure state, $\varrho=|\psi\rangle\langle\psi|$. For a mixture of preparations $|\psi_j\rangle$ with probabilities $p_j$, use $\varrho=\sum_jp_j|\psi_j\rangle\langle\psi_j|$. This positive matrix has trace one. An observable is a Hermitian matrix A; its mean is $\operatorname{tr}(\varrho A)$.`,s`S=-k_B\operatorname{tr}(\varrho\ln\varrho).`, 'Diagonalizing the density matrix reduces the entropy formula to the classical probability formula for its eigenvalues.'),
 step('Trace over what is inaccessible',s`For two two-state systems, take $|\Psi\rangle=(|00\rangle+|11\rangle)/\sqrt2$. The full density matrix is pure and has entropy zero. If only the first system is accessible, define $\varrho_A=\sum_{b=0,1}\langle b|\varrho_{AB}|b\rangle$, where the inner products act on the second system. The cross terms vanish because $\langle0|1\rangle=0$.`,s`\varrho_A=\frac12\begin{pmatrix}1&0\\0&1\end{pmatrix},\qquad S_A=k_B\ln2.`, 'A partial trace keeps exactly the information needed for measurements on the accessible subsystem.'),
 step('Keep evolution separate from restriction',s`A closed system evolves by a unitary matrix $U$, with $U^\dagger U=I$ and $\varrho\mapsto U\varrho U^\dagger$. This preserves its eigenvalues and therefore its entropy. Restricting to a subsystem is a different operation and can change the entropy you assign to that subsystem.`,s`\operatorname{tr}[(U\varrho U^\dagger)^2]=\operatorname{tr}(\varrho^2).`, 'Unitary similarity preserves spectra; a partial trace does not preserve the full state’s spectrum.')],
 formal:s`A free field can be decomposed into normal modes; in a chosen stationary background each mode behaves as a quantum oscillator with energies $E_n=\hbar\omega(n+1/2)$. Summing the canonical geometric series gives mean occupation $\langle n\rangle=1/(e^{\hbar\omega/(k_BT)}-1)$ for bosonic modes with zero chemical potential. The oscillator spectrum and field quantization are additional quantum inputs; this short preparation does not derive them from classical geometry. In curved spacetime different choices of positive-frequency modes can define different vacuum states. A full Hawking-flux derivation must specify those modes, the state, and transmission through the exterior curvature potential. The finite example above explains why an exterior thermal description alone is not proof that global evolution destroyed information.`,
 requires:[ref('Complex modes',18,'waves-modes-and-green-functions'),ref('Probabilities and entropy',22,'probability-temperature-and-entropy')],practice:{prompt:'A subsystem has a mixed density matrix. Must the full system also be mixed?',choices:[choice('No. An entangled pure state can have a mixed reduced state.',true,'The two-system example has zero total entropy and a nonzero reduced entropy.'),choice('Yes. Pure states have pure parts.',false,'Entanglement is precisely why this inference fails.'),choice('A mixed reduced state proves nonunitary evolution.',false,'Partial tracing is not the same operation as evolving the full closed system.')],hint:'Calculate the partial trace of the explicitly supplied two-system state.'},
 transfer:number('original',s`For $\varrho_A=I_2/2$, calculate the purity $\operatorname{tr}(\varrho_A^2)$.`,.5,'',s`Square the two diagonal entries and add.`,s`$1/4+1/4=1/2$. A normalized pure state instead has purity 1.`),
 variants:[number('unequal-reduction',s`For $|\Psi\rangle=\sqrt{3/4}|00\rangle+\sqrt{1/4}|11\rangle$, find the purity of the first subsystem.`,.625,'',s`Its reduced eigenvalues are 3/4 and 1/4.`,s`$(3/4)^2+(1/4)^2=10/16=5/8$.`)],sources:[quantum,thermal],takeaway:'Mixed information about a part and loss of information in the whole are distinct claims.'
},
];
