// Original guided examples. Markdown is rendered by the book's existing math pipeline.
// Keep coordinate conventions synchronized with book.md and the visual lesson modules.
const m = String.raw;
const tong2 = {title:'David Tong · Differential geometry, §§2.1–2.3',url:'https://davidtong.org/pdfs/teaching/general-relativity/gr2.pdf'};
const tong3 = {title:'David Tong · Metrics, connections, and transport, §§3.1–3.3',url:'https://davidtong.org/pdfs/teaching/general-relativity/gr3.pdf'};
const projection = {title:'University of Mannheim · Metrics and connections, induced connection',url:'https://www.wim.uni-mannheim.de/media/Lehrstuehle/wim/schmidt/FSS2024/Riemannian_Geometry/Web/RGch3.html'};
const needham = {title:'Tristan Needham · Visual Differential Geometry and Forms',url:'https://www.vdgf.space/'};

export const geometryLessons = [
  {
    id:'coordinates-change-measurements-do-not', chapter:2,
    after:'2.4 Changing coordinates with the chain rule',
    title:'Change the coordinates. Keep the measurement.',
    question:'If both the vector components and the measuring rule change, how can their answer stay the same?',
    intuition:m`A moving sensor follows one path through a scalar field. One map uses $(x,y)$; another uses $u=x$ and $v=y+x^2$. The second map bends its coordinate grid, but it cannot change the sensor reading. We will calculate the same rate of change twice. All coordinates, the path parameter $\lambda$, and the scalar reading in this example are dimensionless.`,
    visual:null,
    steps:[
      {title:'Give the experiment a point and a direction',body:m`At $(x,y)=(1,2)$, let the path have tangent components $V=(dx/d\lambda,dy/d\lambda)=(2,-1)$. The scalar field is $f=3x-y$. Its differential $df$ is the covector that measures the first-order change along any tangent.`,tex:m`df(V)=3(2)-(-1)=7.`,reason:'The multivariable chain rule multiplies each partial derivative by the corresponding coordinate rate.'},
      {title:'Convert the tangent using the local map',body:m`The new address is $(u,v)=(1,3)$. Differentiate the coordinate change at the original point. The Jacobian is the matrix of these derivatives; it acts on the tangent, not on the point itself.`,tex:m`J=\frac{\partial(u,v)}{\partial(x,y)}=\begin{pmatrix}1&0\\2x&1\end{pmatrix},\qquad V'=\left.J\right|_{x=1}\begin{pmatrix}2\\-1\end{pmatrix}=\begin{pmatrix}2\\3\end{pmatrix}.`,reason:'The first new coordinate has the original horizontal rate. The second also includes the derivative of the squared horizontal coordinate.'},
      {title:'Convert the measuring rule using the inverse map',body:m`Solve for the old coordinates: $x=u$, $y=v-u^2$. The same scalar field now has the formula $f'=3u-v+u^2$. At $u=1$ its partial derivatives are $(5,-1)$.`,tex:m`df=3\,dx-dy=(3+2u)\,du-dv.`,reason:'A scalar keeps its value at each point. Substituting the inverse coordinate map gives its new formula before differentiating.'},
      {title:'Let the two changes cancel',body:m`Pair the new covector components with the new tangent components. The lists changed; the measured rate did not. No lengths or angles entered this calculation.`,tex:m`df(V)=5(2)-1(3)=7.`,reason:'Vector and covector transformation laws compensate because they describe the same directional derivative.'}
    ],
    formal:m`With vector components written as a column and covector components as a row, the transformation is $V'=JV$ and $\omega'=\omega J^{-1}$. Thus $\omega'V'=\omega J^{-1}JV=\omega V$. If you store covectors as columns instead, the rule is $\omega'=(J^{-1})^{\mathsf T}\omega$; the transpose comes from that storage convention. This is an exact algebraic proof for any invertible Jacobian. Here the inverse map exists on all of $\mathbb R^2$ and $\det J=1$ everywhere. The coordinate change is nonlinear even though its action on each tangent space is linear.`,
    requires:[{label:'Partial derivatives along a path',href:'chapter-0.html#0-2-partial-derivatives-change-one-input-at-a-time'},{label:'Covectors and their pairing',href:'chapter-2.html#2-3-covectors-questions-you-can-ask-a-vector'}],
    practice:{prompt:m`A classmate transforms the column of covector components with $J$, just as for a vector, and obtains a different sensor rate. What needs repairing?`,choices:[{text:m`Use the inverse transpose for covector columns.`,correct:true,feedback:m`Yes. A covector consumes a vector; its transformation must undo the vector's transformation inside the pairing.`},{text:m`Multiply the final rate by $\det J$.`,correct:false,feedback:m`A directional derivative is a scalar, not a coordinate area. In this example $\det J=1$, so this would not even repair the error.`},{text:m`Accept the new rate: a nonlinear map changes the physical experiment.`,correct:false,feedback:m`This is a change of labels for the same path and field. An active physical deformation would be a different experiment.`}],hint:m`Write the desired identity $\omega'V'=\omega V$, then substitute $V'=JV$.`},
    transfer:{prompt:m`Keep $u=x$, $v=y+x^2$, but use $f=x+2y$. At $x=2$, a path has $(dx/d\lambda,dy/d\lambda)=(3,-2)$. Find $df/d\lambda$ using the new coordinates.`,answer:-1,tolerance:1e-8,unit:'',hint:m`First obtain $V'=(3,10)$. Rewrite $f$ in terms of $u,v$ before finding its derivatives.`,solution:m`The new formula is $f'=u+2v-2u^2$. At $u=2$, $df=(-7)\,du+2\,dv$, so $df/d\lambda=(-7)(3)+2(10)=-1$. Directly, $1(3)+2(-2)=-1$ as well.`},
    sources:[tong2],
    takeaway:'A vector and a covector change their component lists together so that the measurement they make together stays fixed.'
  },
  {
    id:'two-maps-one-sphere', chapter:4,
    after:'4.1 A manifold is a place where local coordinates work',
    title:'Give one sphere two reliable addresses',
    question:'What should a map do when the place you want to visit is missing from it?',
    intuition:m`A chart is an invertible assignment of coordinates on an open patch. It need not cover the whole surface. On a unit sphere, two stereographic charts complement one another: the $(u,v)$ chart omits the north pole and the $(p,q)$ chart omits the south pole. Move the point and watch both addresses. A coordinate becoming large is a warning about that map, not evidence that the sphere is breaking.`,
    visual:'charts',
    steps:[
      {title:'Build an address by projecting from a pole',body:m`Write the sphere as $X^2+Y^2+Z^2=1$. A line from $N=(0,0,1)$ through a surface point meets the plane $Z=0$ at $(u,v,0)$. All quantities here are dimensionless.`,tex:m`u=\frac{X}{1-Z},\qquad v=\frac{Y}{1-Z}.`,reason:'Setting the height of the projection line to zero fixes the scale factor between the sphere coordinates and the plane coordinates.'},
      {title:'Recover the surface point before changing its address',body:m`Let $s=u^2+v^2$. The inverse below turns the sample address $(2,0)$ into $(4/5,0,3/5)$. It also shows why every finite address gives a point away from the north pole.`,tex:m`(X,Y,Z)=\left(\frac{2u}{1+s},\frac{2v}{1+s},\frac{s-1}{1+s}\right).`,reason:'Substitute the projection formulas into the sphere equation and select the solution away from the projection pole.'},
      {title:'Read the other chart at that same point',body:m`Project from the south pole instead: $p=X/(1+Z)$ and $q=Y/(1+Z)$. Substituting the inverse map gives the transition. The sample point has $(p,q)=(1/2,0)$.`,tex:m`(p,q)=\frac{(u,v)}{u^2+v^2},\qquad (u,v)\ne(0,0).`,reason:'The transition first recovers the sphere point and then reads the second address. Its excluded origin represents the south pole, outside the second chart.'},
      {title:'Check that a direction survives the change',body:m`Differentiate the transition at $(u,v)=(2,0)$. A tangent rate $(1,2)$ becomes $(-1/4,1/2)$. Negative entries can reverse coordinate directions; they do not tear or rotate the sphere.`,tex:m`\left.\frac{\partial(p,q)}{\partial(u,v)}\right|_{(2,0)}=\begin{pmatrix}-1/4&0\\0&1/4\end{pmatrix}.`,reason:'The Jacobian has nonzero determinant, so it does not collapse any infinitesimal direction.'}
    ],
    formal:m`The first chart maps $S^2\setminus\{N\}$ onto $\mathbb R^2$ and the second maps $S^2\setminus\{S\}$ onto $\mathbb R^2$. Their overlap corresponds to $\mathbb R^2\setminus\{(0,0)\}$. The transition is its own inverse and has determinant $-1/(u^2+v^2)^2$, which never vanishes on that overlap. This proves smooth compatibility of these two charts and constructs an atlas covering the sphere. We have not yet assigned distances to coordinate differences. This two-dimensional sphere embedded in three-dimensional space is a convenient construction here; the definition of a manifold does not require an embedding.`,
    requires:[{label:'Changing coordinates with a Jacobian',href:'chapter-2.html#2-4-the-chain-rule-already-knows-tensor-calculus'}],
    practice:{prompt:m`A point approaches the north pole while its $(u,v)$ coordinates grow without bound. What happens at the pole itself?`,choices:[{text:m`The $(u,v)$ chart has no address there; the $(p,q)$ chart assigns $(0,0)$.`,correct:true,feedback:m`Exactly. The second chart supplies a regular neighborhood of the point that the first chart excludes.`},{text:m`The north pole is an infinitely distant physical point.`,correct:false,feedback:m`We have discussed coordinate labels, not a distance measurement. The ordinary sphere is smooth at its north pole.`},{text:m`Both charts fail because any pole is a surface singularity.`,correct:false,feedback:m`The omitted poles are different. Each chart covers the point omitted by the other.`}],hint:m`Insert $X=Y=0$, $Z=1$ directly into the second chart.`},
    transfer:{prompt:m`At $(u,v)=(0,2)$, a path has tangent rates $(du/d\lambda,dv/d\lambda)=(3,4)$. What is $dp/d\lambda$ for $p=u/(u^2+v^2)$?`,answer:0.75,tolerance:1e-8,unit:'',hint:m`Differentiate the quotient along the path. Terms multiplied by $u$ vanish at this point.`,solution:m`At $(0,2)$, $\partial p/\partial u=1/4$ and $\partial p/\partial v=0$. Therefore $dp/d\lambda=(1/4)(3)+0(4)=3/4$. Transform the tangent locally; do not put its component list into the nonlinear point map.`},
    sources:[tong2,needham],
    takeaway:'An atlas covers a surface with compatible local maps, and a map can fail where the surface remains perfectly regular.'
  },
  {
    id:'a-metric-converts-labels-into-lengths', chapter:4,
    after:'4.5 A complete metric calculation in flat polar coordinates',
    title:'Teach a coordinate grid how to measure',
    question:'Why does the same angular change mean a longer trip when you are farther from the origin?',
    intuition:m`Take two nearby spokes on a flat plane. Walking across their separation at radius $r$ covers a circular arc of length $r\,\Delta\theta$. The coordinate difference $\Delta\theta$ alone is an angle, not a length. The metric supplies the missing conversion. In the figure, shrink the coordinate cell to distinguish an exact local measuring rule from an approximation for a finite step.`,
    visual:'metric',
    steps:[
      {title:'Differentiate the map, not the picture',body:m`For $x=r\cos\theta$ and $y=r\sin\theta$, a tangent change splits into a radial part and an angular part. The angle is measured in radians and $r$ in meters.`,tex:m`\begin{aligned}dx&=\cos\theta\,dr-r\sin\theta\,d\theta,\\dy&=\sin\theta\,dr+r\cos\theta\,d\theta.\end{aligned}`,reason:'The product rule and the derivatives of sine and cosine give the Cartesian components of the same local displacement.'},
      {title:'Apply the familiar measuring rule',body:m`Square the two expressions and add them. Their mixed terms cancel because the radial and angular directions are perpendicular.`,tex:m`ds^2=dx^2+dy^2=dr^2+r^2d\theta^2.`,reason:'The squared sine and cosine terms add to one, leaving one radial term and one angular term.'},
      {title:'Read the metric as two calibrated rulers',body:m`In the coordinate order $(r,\theta)$, the metric matrix is diagonal. At $r=3\,\mathrm m$, the local changes $dr=0.03\,\mathrm m$ and $d\theta=0.01$ contribute equal physical lengths.`,tex:m`g_{ij}=\begin{pmatrix}1&0\\0&r^2\end{pmatrix},\qquad ds=\sqrt{(0.03\,\mathrm m)^2+(0.03\,\mathrm m)^2}\approx0.04243\,\mathrm m.`,reason:'Multiply the angular increment by the radius before combining perpendicular physical lengths.'},
      {title:'Separate local vectors from finite journeys',body:m`For finite coordinate differences the preceding number estimates the straight distance between nearby endpoints. A path that first walks radially and then follows an arc is longer and has its own exact length. For a continuously specified path, the metric gives an exact instantaneous speed.`,tex:m`\frac{ds}{dt}=\sqrt{\left(\frac{dr}{dt}\right)^2+r(t)^2\left(\frac{d\theta}{dt}\right)^2}.`,reason:'The line element measures tangent vectors exactly. Integrating their lengths measures a chosen finite path.'}
    ],
    formal:m`For $r>0$ and an angular interval avoiding a seam, $g_{ij}$ is the matrix of inner products of the coordinate basis vectors. The radial basis has unit length; the angular basis has length $r$. Thus $g_{\theta\theta}$ has units of length squared, while $g_{rr}$ is dimensionless. These different units compensate for the units of the coordinates. At $r=0$ the polar chart ceases to distinguish angular directions; the Euclidean metric itself remains regular in Cartesian coordinates. This calculation proves the polar form of the flat metric. Position-dependent metric components alone do not prove curvature.`,
    requires:[{label:'The metric as a measuring operation',href:'chapter-4.html#4-4-the-metric-is-a-local-measuring-operation'},{label:'Partial derivatives',href:'chapter-0.html#0-2-partial-derivatives-change-one-input-at-a-time'}],
    practice:{prompt:m`Double $r$ while keeping a purely angular increment $d\theta$ fixed. How do its length and squared length change?`,choices:[{text:m`The length doubles; its contribution to $ds^2$ quadruples.`,correct:true,feedback:m`Yes: $ds=r|d\theta|$ for this tangent, so squaring produces the factor of four.`},{text:m`Both double.`,correct:false,feedback:m`The metric computes a squared length. The square of a doubled length is four times as large.`},{text:m`Neither changes because the coordinate increment is unchanged.`,correct:false,feedback:m`The angular coordinate counts radians. The metric tells us how many meters correspond to that increment at the chosen radius.`}],hint:m`Set $dr=0$ in the line element, then take its positive square root.`},
    transfer:{prompt:m`A particle has $r=4\,\mathrm m$, $dr/dt=3\,\mathrm{m\,s^{-1}}$, and $d\theta/dt=1\,\mathrm{s^{-1}}$. What is its instantaneous speed?`,answer:5,tolerance:1e-8,unit:m`$\mathrm{m/s}$`,hint:m`The angular part of the physical velocity has magnitude $r\,d\theta/dt$. Combine it with the radial part.`,solution:m`The perpendicular velocity components have magnitudes $3\,\mathrm{m\,s^{-1}}$ and $4\,\mathrm{m\,s^{-1}}$, so $ds/dt=\sqrt{3^2+4^2}=5\,\mathrm{m\,s^{-1}}$. This is exact at the specified instant; no small-time approximation is needed.`},
    sources:[tong3],
    takeaway:'A metric turns coordinate rates into physical measurements while keeping track of scale, direction, and units.'
  },
  {
    id:'differentiate-the-arrow-not-its-address', chapter:6,
    after:'6.2 What a derivative must be able to compare',
    title:'An unchanged arrow can have changing components',
    question:'Can a vector have a nonzero component derivative while the vector itself stays fixed?',
    intuition:m`Carry a little radial-and-angular frame around the flat plane. Keep a unit arrow pointing east in the fixed Cartesian picture. The frame rotates beneath it, so its two component readings change. A derivative of the whole arrow must include both changes: the component readings and the basis vectors that give those readings meaning.`,
    visual:'basis',
    steps:[
      {title:'Make the moving rulers explicit',body:m`The hats mark unit vectors. The angle $\theta$ is in radians, and these basis vectors are written in a fixed Cartesian frame. They are perpendicular and have length one.`,tex:m`\hat e_r=(\cos\theta,\sin\theta),\qquad\hat e_\theta=(-\sin\theta,\cos\theta).`,reason:'The radial unit vector points outward; rotating it by a right angle gives the angular unit vector.'},
      {title:'Describe the fixed eastward arrow',body:m`Take $V=(1,0)$ in the Cartesian frame. Dot products with the two unit rulers give its moving-frame components. At $\theta=\pi/2$, east is the negative angular direction.`,tex:m`V=\cos\theta\,\hat e_r-\sin\theta\,\hat e_\theta.`,reason:'In an orthonormal frame, each component is the dot product with its unit basis vector.'},
      {title:'Differentiate the basis as well as the numbers',body:m`Direct differentiation gives $d\hat e_r/d\theta=\hat e_\theta$ and $d\hat e_\theta/d\theta=-\hat e_r$. The product rule now contains four terms.`,tex:m`\frac{dV}{d\theta}=\underbrace{-\sin\theta\,\hat e_r-\cos\theta\,\hat e_\theta}_{\text{component change}}+\underbrace{\cos\theta\,\hat e_\theta+\sin\theta\,\hat e_r}_{\text{basis change}}=0.`,reason:'The apparent component change cancels exactly against the change of the moving rulers.'},
      {title:'Recognize the correction a connection must supply',body:m`For any vector with unit-frame components $V^{\hat r}$ and $V^{\hat\theta}$, the corrected derivative includes the same basis terms. Our eastward arrow makes both corrected components zero.`,tex:m`\left(\nabla_{\partial_\theta}V\right)^{\hat r}=\partial_\theta V^{\hat r}-V^{\hat\theta},\qquad\left(\nabla_{\partial_\theta}V\right)^{\hat\theta}=\partial_\theta V^{\hat\theta}+V^{\hat r}.`,reason:'Collect the product-rule terms along each unit basis vector. This is the flat-plane connection written in a moving frame.'}
    ],
    formal:m`These are **orthonormal-frame** components, not polar coordinate components. The coordinate basis satisfies $\partial_r=\hat e_r$ and $\partial_\theta=r\hat e_\theta$ for $r>0$, so $V^r=V^{\hat r}$ but $V^\theta=V^{\hat\theta}/r$. This scale factor matters when comparing the formulas with Christoffel symbols. The calculation above is an exact product-rule proof in the Euclidean plane. On a general manifold, a connection supplies the comparison between neighboring tangent spaces; an ambient Cartesian frame need not exist. A nonzero connection coefficient can describe changing rulers in a completely flat geometry. Curvature asks whether consistent local comparisons fail to agree around a loop.`,
    requires:[{label:'A vector and its basis',href:'chapter-2.html#2-1-a-vector-is-not-its-spreadsheet'},{label:'Polar metric and coordinate lengths',href:'chapter-4.html#4-5-a-complete-metric-calculation-in-flat-polar-coordinates'}],
    practice:{prompt:m`The eastward arrow is examined at $\theta=\pi/2$. Which description is correct?`,choices:[{text:m`Its unit-frame components are $(0,-1)$ and its geometric derivative is zero.`,correct:true,feedback:m`Exactly. At that position $\hat e_\theta$ points west, so the unchanged arrow has angular component $-1$. The changing basis cancels its component derivative.`},{text:m`Its components are $(1,0)$ because the arrow stayed fixed.`,correct:false,feedback:m`Those are its Cartesian components. The local radial-and-angular frame has rotated.`},{text:m`Its components are $(0,-1)$, proving that the vector field is turning.`,correct:false,feedback:m`A changing component list can come entirely from changing rulers. Include the basis derivative before concluding that the field changes.`}],hint:m`Evaluate both moving basis vectors at $\theta=\pi/2$, then express east using them.`},
    transfer:{prompt:m`At $r=3\,\mathrm m$ and $\theta=\pi/3$, a particle's Cartesian velocity is $(0,6)\,\mathrm{m\,s^{-1}}$. What is the coordinate rate $d\theta/dt$?`,answer:1,tolerance:1e-8,unit:m`$\mathrm{rad/s}$`,hint:m`Project onto $\hat e_\theta$ to obtain the physical angular velocity component, then divide by $r$.`,solution:m`The unit-frame component is $V^{\hat\theta}=6\cos(\pi/3)=3\,\mathrm{m\,s^{-1}}$. The coordinate component is $V^\theta=V^{\hat\theta}/r=1\,\mathrm{s^{-1}}$, or one radian per second. Mixing these two components would lose a factor of $r$.`},
    sources:[tong3],
    takeaway:'The covariant derivative combines changing components with the comparison of local bases so that an unchanged vector has zero derivative.'
  },
  {
    id:'carry-a-direction-without-turning-it', chapter:8,
    after:'8.3 Holonomy: geometry remembers your route',
    title:'Carry a direction home—and find it changed',
    question:'How can an arrow turn after a journey if you never turn it within the surface?',
    intuition:m`At one point of a sphere, a tangent arrow lies in a flat plane touching that point. At the next point, the tangent plane is different. Keeping the same three-dimensional arrow will generally make it stick out of the surface. The relevant rule is local: allow the change needed to remain tangent, but remove any turning **within** the surface. Then carry out that rule around a whole loop.`,
    visual:'transport',
    steps:[
      {title:'Split an ambient change into normal and tangent parts',body:m`Let $n$ be the outward unit normal. Any three-dimensional change $W$ has normal part $(W\cdot n)n$. Subtracting that part leaves its tangent projection $P W$.`,tex:m`P=I-nn^{\mathsf T},\qquad PW=W-(W\cdot n)n.`,reason:'The projection subtracts the component perpendicular to the tangent plane. Because the normal has unit length, the subtraction removes that component completely.'},
      {title:'State the local transport rule',body:m`For a tangent vector $V(s)$ along a path, require its derivative to have no tangent component. Here $s$ measures distance along the path. This is the Levi-Civita parallel-transport rule for the sphere with its usual induced metric.`,tex:m`\nabla_{\dot\gamma}V=P\frac{dV}{ds}=0.`,reason:'The remaining ambient change points normally to the surface. It adjusts tangency without adding an intrinsic turn.'},
      {title:'Verify one great-circle arc',body:m`For this unit-sphere calculation, measure lengths in units of the sphere radius, making $s$ dimensionless arc length. Take $\gamma(s)=(\cos s,0,\sin s)$ and carry its unit tangent $V=(-\sin s,0,\cos s)$. Its derivative is $-\gamma(s)$, entirely normal, so its tangent projection vanishes. The arrow changes in three-dimensional space while remaining parallel intrinsically.`,tex:m`\frac{dV}{ds}=(-\cos s,0,-\sin s)=-n,\qquad P\frac{dV}{ds}=0.`,reason:'A great circle bends toward the sphere center, with no left-or-right turn inside the tangent plane.'},
      {title:'Join three verified arcs without twisting at the corners',body:m`Follow $A=(1,0,0)$ to $N=(0,0,1)$, then to $B=(0,1,0)$, then back to $A$. Start with $V=(0,0,1)$. It reaches $N$ as $(-1,0,0)$, stays that same ambient vector on the second arc, and reaches $A$ as $(0,1,0)$ after the final arc. At a corner, keep the arrow continuous even though the path changes direction.`,tex:m`(0,0,1)\ \longrightarrow\ (-1,0,0)\ \longrightarrow\ (-1,0,0)\ \longrightarrow\ (0,1,0).`,reason:'Each arc obeys the tangent-projection rule. Initial and final vectors now share one tangent plane and differ by a right angle.'},
      {title:'Read the loop as a curvature experiment',body:m`The triangle occupies one octant of the sphere. On a sphere of radius $a$ its area is $\pi a^2/2$, and the rotation magnitude is $\pi/2$. Reversing the journey reverses the signed rotation.`,tex:m`|\Delta\psi|=\frac{\text{area}}{a^2}=\frac{\pi}{2}.`,reason:'The explicit transport calculation establishes the octant result. It compares vectors at the same endpoint, so the mismatch cannot be blamed on different endpoint coordinates.'}
    ],
    formal:m`The projection applies to the **derivative**. A single finite projection between distant tangent planes is not exact parallel transport and usually shortens an arrow. Repeated tiny projections approach the transport rule as the steps shrink. Norm preservation follows directly: $d(V\cdot V)/ds=2V\cdot dV/ds=0$, because a tangent vector is perpendicular to a normal derivative. The calculation proves the octant example. More generally, on an oriented surface a simple contractible loop has signed holonomy given, modulo a full turn and with an orientation convention, by the enclosed integral of Gaussian curvature. That general curvature–area theorem is stated here, not proved by one triangle. A spherical geodesic triangle's **angular excess** is its angle sum minus $\pi$; it equals its area divided by $a^2$. For small triangles that excess gives the rotation magnitude directly. For larger regions, angles differing by a full turn represent the same final arrow.`,
    requires:[{label:'Parallel transport as a differential equation',href:'chapter-7.html#7-1-parallel-transport-is-an-instruction-not-a-picture'},{label:'Metric compatibility',href:'chapter-7.html#7-2-two-requirements-that-select-ordinary-gr-s-connection'},{label:'Tangent spaces',href:'chapter-4.html#4-3-tangent-vectors-live-at-events'}],
    practice:{prompt:m`Could we reproduce this experiment by keeping the original ambient arrow fixed, moving it straight to the final point, and projecting once there?`,choices:[{text:m`No. That ignores the local tangent-plane comparison along the chosen route.`,correct:true,feedback:m`Right. At the end of this closed loop the tangent plane is the starting plane, so one final projection would return the original arrow and miss the holonomy.`},{text:m`Yes. Parallel transport depends only on the two endpoints.`,correct:false,feedback:m`Endpoint-only comparison is exactly what this loop disproves. The route matters in curved geometry.`},{text:m`Yes, provided the arrow is made longer before projection.`,correct:false,feedback:m`Rescaling can repair a length, but it cannot supply the missing route-dependent direction.`}],hint:m`The initial and final tangent planes are identical. What would a single projection at that final point do?`},
    transfer:{prompt:m`A small geodesic triangle on a sphere of radius $a=2\,\mathrm m$ encloses area $\pi/3\,\mathrm m^2$. What is the parallel-transport rotation magnitude in degrees?`,answer:15,tolerance:1e-8,unit:'degrees',hint:m`Divide area by $a^2$ to get radians, then multiply by $180/\pi$.`,solution:m`The rotation is $(\pi/3)/2^2=\pi/12$ radians, or $15^\circ$. The length units cancel. Doubling the sphere radius at fixed physical loop area reduces the rotation by a factor of four.`},
    sources:[projection,tong3,needham],
    takeaway:'Curvature can reveal itself as a mismatch after a direction is transported locally without turning and brought back to its starting tangent plane.'
  },
  {
    id:'measure-curvature-with-a-string', chapter:8,
    after:'8.6 A sphere computed from its own measurements',
    title:'Measure curvature without leaving the surface',
    question:'Could inhabitants of a sphere discover its curvature using only lengths measured on their world?',
    intuition:m`Fix one point and walk the same surface distance $\rho$ from it in every direction. The resulting **geodesic circle** consists of points at that distance from the center. Measure its circumference $C$. In a flat plane, $C=2\pi\rho$. On a sphere, the circumference is smaller. The comparison uses distances on the surface; no view from outside is needed to perform it.`,
    visual:null,
    steps:[
      {title:'Distinguish the two radii',body:m`Let $a$ be the sphere radius and put the chosen center at its north pole. A meridian distance $\rho$ subtends angle $\theta=\rho/a$. The circular latitude at that distance has ambient radius $a\sin\theta$. This ambient radius helps calculate the answer; the inhabitants measure $\rho$ along the surface.`,tex:m`C(\rho)=2\pi a\sin(\rho/a),\qquad 0<\rho<\pi a.`,reason:'Great-circle arc length is the sphere radius times the angular distance. The latitude circle instead uses the radius projected onto the equatorial plane.'},
      {title:'Compare with the flat prediction',body:m`For a small circle, use the Taylor expansion $\sin z=z-z^3/6+O(z^5)$. Here $O(z^5)$ collects terms no larger than a constant times $|z|^5$ as $z$ tends to zero. Divide by the flat circumference.`,tex:m`\frac{C(\rho)}{2\pi\rho}=1-\frac{\rho^2}{6a^2}+O\!\left(\frac{\rho^4}{a^4}\right).`,reason:'The leading term is the flat-plane result. The first correction measures a deficit that becomes easier to interpret as the circle shrinks.'},
      {title:'Extract a quantity that does not vanish with the circle',body:m`The relative deficit shrinks like $\rho^2$. Divide by that known scale before taking the limit. On the round sphere this gives its Gaussian curvature.`,tex:m`K=\lim_{\rho\to0}\frac{6}{\rho^2}\left(1-\frac{C(\rho)}{2\pi\rho}\right)=\frac{1}{a^2}.`,reason:'Dividing out the area scale isolates a local property of the surface instead of a property of the size of our measuring circle.'},
      {title:'Separate bending from intrinsic curvature',body:m`A sheet rolled into a cylinder without stretching has the same local length measurements as the sheet before rolling. A sufficiently small geodesic circle, contained in an unwrapped patch, still satisfies $C=2\pi\rho$. Its Gaussian curvature is zero, even though the cylinder bends in three-dimensional space.`,reason:'Unrolling preserves all distances inside the patch. The sphere’s circumference deficit cannot be removed by an equally distortion-free flattening.'}
    ],
    formal:m`This is an exact derivation of the round sphere's circumference and its small-circle limit. The theorem that the same limit equals Gaussian curvature on any smooth Riemannian surface is a broader local result; it is not proved here. For the sphere, the value $K=1/a^2$ agrees with the curvature tensor calculation in this section. Curvature has units of inverse length squared. Finite circles give an estimate whose corrections are controlled by $\rho/a$; a large circle should not be put into the limiting formula as if it were exact. This argument shows an intrinsic obstruction to flattening a spherical patch without changing lengths. It does not prove every part of Gauss's general intrinsic-curvature theorem or the global Gauss–Bonnet theorem.`,
    requires:[{label:'Local approximation',href:'chapter-0.html#0-8-approximation-is-a-skill-not-an-apology'},{label:'Intrinsic versus extrinsic geometry',href:'chapter-4.html#4-8-intrinsic-curvature-extrinsic-bending-and-laboratory-frames'},{label:'The polar metric',href:'chapter-4.html#4-5-a-complete-metric-calculation-in-flat-polar-coordinates'}],
    practice:{prompt:m`For the same small geodesic radius $\rho$, double the sphere radius $a$. What happens to the leading relative circumference deficit?`,choices:[{text:m`It becomes one quarter as large.`,correct:true,feedback:m`Yes. The leading deficit is $\rho^2/(6a^2)$. A larger sphere looks flatter over the same measured neighborhood.`},{text:m`It becomes half as large.`,correct:false,feedback:m`The effect depends on inverse radius squared. Curvature is measured per area scale, not per length scale.`},{text:m`It becomes four times as large.`,correct:false,feedback:m`The sphere bends more gently when its radius increases. At fixed $\rho$, the discrepancy from a flat circle decreases.`}],hint:m`Keep $\rho$ fixed in $1-C/(2\pi\rho)\approx\rho^2/(6a^2)$.`},
    transfer:{prompt:m`On an unknown round sphere, a geodesic circle has $\rho=0.12\,\mathrm m$ and measured ratio $C/(2\pi\rho)=0.9994001$. Use the leading small-circle formula to estimate the sphere radius $a$.`,answer:2,tolerance:0.003,unit:m`$\mathrm m$`,hint:m`Call the measured deficit $\delta$. Solve $\delta\approx\rho^2/(6a^2)$ for $a$ before inserting the numbers.`,solution:m`Here $\delta=0.0005999$, so $a\approx\rho/\sqrt{6\delta}\approx2.00017\,\mathrm m$, or about $2\,\mathrm m$. The inferred ratio $\rho/a\approx0.06$ is small, making the neglected next term consistent with this estimate.`},
    sources:[{title:'Andreas Kriegl · Riemannian Geometry, Theorem 11.1',url:'https://www.mat.univie.ac.at/~kriegl/Skripten/2018WSe.pdf#page=80'},tong3,needham],
    takeaway:'Intrinsic curvature can be detected by comparing a small circle’s measured circumference with the flat prediction for its measured radius.'
  }
];
