import {lessons,prerequisites,routes} from '../content/course.mjs';
import {icon} from './scenes.mjs';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function lessonHTML(l,render,reference=''){
 const r=s=>render(s,{id:l.id,chapter:l.chapter}).html;
 const inline=s=>r(s).replace(/^<p>|<\/p>\n?$/g,'');
 const id=l.id;
 return `<section class="guided-lesson" id="${id}" data-lesson="${id}" aria-labelledby="${id}-title">
 <div class="lesson-topline"><span class="eyebrow">A WORKED BRIDGE</span><button class="lesson-save" data-save-lesson="${id}" aria-label="Save ${esc(l.title)} to field notebook" title="Save to field notebook">${icon('Bookmark01Icon')}</button></div>
 <h4 id="${id}-title" class="lesson-title">${esc(l.title)}</h4><p class="lesson-question">${inline(l.question)}</p>
 <div class="lesson-prerequisites" data-no-narration><span>Builds on</span>${l.requires.map(p=>`<a data-prerequisite href="${esc(p.href)}">${esc(p.label)} ${icon('ArrowUpRight01Icon')}</a>`).join('')}</div>
 <div class="lesson-depths" role="tablist" aria-label="Explore ${esc(l.title)}">${[['intuition','See the idea'],['derive','Work it out'],['formal','Go deeper']].map(([key,label],i)=>`<button type="button" role="tab" id="${id}-tab-${key}" data-depth="${key}" aria-controls="${id}-${key}" aria-selected="${!i}" tabindex="${i?-1:0}">${label}</button>`).join('')}</div>
 <div class="lesson-panel" role="tabpanel" tabindex="0" id="${id}-intuition" data-depth="intuition" aria-labelledby="${id}-tab-intuition">${r(l.intuition)}</div>
 <div class="lesson-panel" role="tabpanel" tabindex="0" id="${id}-derive" data-depth="derive" aria-labelledby="${id}-tab-derive" hidden><ol class="derivation-steps">${l.steps.map((s,i)=>`<li id="${id}-step-${i+1}"><div class="step-number" aria-hidden="true">${String(i+1).padStart(2,'0')}</div><div><strong>${esc(s.title)}</strong>${r(s.body)}${s.tex?r(`$$${s.tex}$$`):''}<p class="step-reason"><span>Why this step works</span> ${esc(s.reason)}</p></div></li>`).join('')}</ol></div>
 <div class="lesson-panel" role="tabpanel" tabindex="0" id="${id}-formal" data-depth="formal" aria-labelledby="${id}-tab-formal" hidden>${r(l.formal)}<div class="lesson-sources" data-no-narration><span>Further reading</span>${l.sources.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.title)} ${icon('ArrowUpRight01Icon')}</a>`).join('')}</div></div>
 ${l.visual?`<div class="visual-lesson" data-visual-lesson="${l.visual}" data-lesson-id="${id}" aria-label="Interactive model: ${esc(l.title)}"><p class="visual-loading">The interactive model is loading. The worked calculation above also explains this example.</p></div>`:''}
 ${reference?`<details class="lesson-reference" data-no-narration><summary>Open the reference diagram</summary>${reference}</details>`:''}
 <details class="lesson-practice" data-no-narration><summary>Test the idea ${icon('ArrowRight01Icon')}</summary><div class="practice-body"><p class="practice-label">FIRST, PREDICT</p>${r(l.practice.prompt)}<div class="practice-choices" role="group" aria-label="Choose an answer">${l.practice.choices.map((c,i)=>`<button type="button" data-choice="${i}" aria-pressed="false">${inline(c.text)}</button>`).join('')}</div><div class="practice-feedback" role="status"></div><details><summary>A hint</summary>${r(l.practice.hint)}</details><div class="transfer-problem"><p class="practice-label">NOW CHANGE THE EXAMPLE</p>${r(l.transfer.prompt)}<form data-transfer><label for="${id}-answer">Your result ${inline(l.transfer.unit||'')}</label><div class="transfer-input"><input type="text" inputmode="decimal" autocomplete="off" id="${id}-answer" required aria-describedby="${id}-answer-format"><button type="submit">Check ${icon('ArrowRight01Icon')}</button></div><small id="${id}-answer-format">Enter a number. Scientific notation such as 1.2e3 is accepted.</small></form><div class="transfer-feedback" role="status"></div><details><summary>A hint</summary>${r(l.transfer.hint)}</details><details class="transfer-solution"><summary>Work through the solution</summary>${r(l.transfer.solution)}</details></div></div></details>
 <p class="lesson-takeaway">${esc(l.takeaway)}</p><div class="lesson-save-status" role="status" data-no-narration></div></section>`;
}
export function compassHTML(chapter,guides){
 if(chapter===undefined)return '';
 const n=+chapter,list=lessons.filter(l=>l.chapter===n);
 return `<div class="course-compass" data-no-narration><a href="course-map.html">${icon('Route01Icon')} Learning path</a><span data-route-next></span><a href="notebook.html">${icon('Notebook01Icon')} Field notebook</a></div><div class="return-to-lesson" hidden data-no-narration></div>${list.length?`<details class="chapter-bridges" data-no-narration><summary>${list.length} worked ${list.length===1?'bridge':'bridges'} in this chapter</summary><div>${list.map(l=>`<a href="#${l.id}">${esc(l.title)} ${icon('ArrowRight01Icon')}</a>`).join('')}</div></details>`:''}`;
}
export function courseMapHTML(guides){
 return `<article class="course-map"><header class="chapter-header"><span class="eyebrow">YOUR LEARNING PATH</span><h1>One idea opens<br><em>the next.</em></h1><p class="chapter-deck">Start with what you know. Follow the dependencies. Return to the exact point where a new idea becomes useful.</p></header><div class="course-route-picker" role="group" aria-label="Choose a learning route">${routes.map((r,i)=>`<button data-route="${r.id}" aria-pressed="${!i}"><strong>${r.title}</strong><span>${r.description}</span></button>`).join('')}</div><p class="route-status" role="status"></p><div class="course-map-list">${prerequisites.map((req,n)=>`<section class="course-node" data-chapter-node="${n}" style="--node-accent:var(--${n<6?'observer':n<11?'geometry':n<16?'curvature':n<20?'matter':'transport'})"><span class="course-node-number">${String(n).padStart(2,'0')}</span><div><a class="course-node-title" href="chapter-${n}.html">${esc(guides[n].title)} ${icon('ArrowUpRight01Icon')}</a><p>${esc(guides[n].payoff)}</p><div class="course-node-requires"><span>${req.length?'Builds on':'Starting point · basic calculus and linear algebra'}</span>${req.map(p=>`<a href="chapter-${p}.html" title="${esc(guides[p].title)}">${String(p).padStart(2,'0')} ${esc(guides[p].title)}</a>`).join('')}</div>${lessons.filter(l=>l.chapter===n).map(l=>`<a class="map-lesson" href="chapter-${n}.html#${l.id}"><span>${esc(l.title)}</span><small data-evidence-for="${l.id}">Explore & test</small></a>`).join('')}</div></section>`).join('')}</div><details class="course-conventions"><summary>Scope, notation, and how to use this route</summary><p>The core route reaches observations and cosmology. Chapters 20–23 are optional extensions. The black-hole route includes their geometric prerequisites before Chapter 22; Hawking radiation uses explicitly stated quantum input. A solved example is evidence for that particular skill, not a claim of mastery of a chapter.</p><p><a href="reading-guide.html">Reading guide & conventions</a> · <a href="visual-language.html">Color & notation</a> · <a href="chapter-24.html">Synthesis and further study</a></p></details></article>`;
}
export function notebookHTML(){return `<article class="field-notebook"><header class="chapter-header"><span class="eyebrow">YOUR FIELD NOTEBOOK</span><h1>Keep the ideas<br><em>you make yours.</em></h1><p class="chapter-deck">Saved lessons, your observations, and the problems to revisit. Stored in this browser, with an export you can keep.</p></header><div class="notebook-actions"><button data-export-notebook="json">Export notebook</button><button data-export-notebook="md">Export as Markdown</button><label class="notebook-import">Import notebook<input type="file" accept="application/json,.json" data-import-notebook></label></div><p class="notebook-status" role="status"></p><section class="review-queue"><h2>Return to an idea</h2><p class="notebook-help">Unfinished problems first; solved examples reappear after three days. Reading and listening are recorded separately by the reader.</p><div data-review-queue></div></section><section><h2>Your observations</h2><div data-notebook-entries></div></section></article>`;}
export function publicCourseData(render,guides={}){return {version:1,routes,prerequisites,chapterTitles:Object.fromEntries(Object.entries(guides).map(([chapter,guide])=>[chapter,guide.title])),lessons:lessons.map(l=>({...l,practice:{...l.practice,choices:l.practice.choices.map(c=>({...c,feedbackHTML:render(c.feedback,{id:l.id,chapter:l.chapter}).html}))}}))};}
