import {lessons,prerequisites,routes,skills,requirementsFor} from '../content/course.mjs';
import {icon} from './scenes.mjs';
import {visualFallback} from './visual-fallbacks.mjs';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function lessonHTML(l,render,reference=''){
 const r=s=>render(s,{id:l.id,chapter:l.chapter}).html;
 const inline=s=>r(s).replace(/^<p>|<\/p>\n?$/g,'');
 const id=l.id;
 return `<section class="guided-lesson" id="${id}" data-lesson="${id}" data-sequential="${l.placement==='section-start'}" aria-labelledby="${id}-title">
 <div class="lesson-topline"><span class="eyebrow">${l.placement==='section-start'?'PREPARATION FOR THIS SECTION':'A WORKED BRIDGE'}</span><button disabled class="lesson-save" data-save-lesson="${id}" aria-label="Save ${esc(l.title)} to field notebook" title="Save to field notebook">${icon('Bookmark01Icon')}</button></div>
 <h4 id="${id}-title" class="lesson-title">${esc(l.title)}</h4><p class="lesson-question">${inline(l.question)}</p>
 ${l.requires.length?`<div class="lesson-prerequisites" data-no-narration><span>Builds on</span>${l.requires.map(p=>`<a data-prerequisite href="${esc(p.href)}">${esc(p.label)} ${icon('ArrowUpRight01Icon')}</a>`).join('')}</div>`:''}
 <div class="lesson-depths" hidden role="tablist" aria-label="Explore ${esc(l.title)}">${[['intuition','See the idea'],['derive','Work it out'],['formal','Go deeper']].map(([key,label],i)=>`<button type="button" role="tab" id="${id}-tab-${key}" data-depth="${key}" aria-controls="${id}-${key}" aria-selected="${!i}" tabindex="${i?-1:0}">${label}</button>`).join('')}</div>
 <div class="lesson-panel" role="region" id="${id}-intuition" data-depth="intuition" aria-label="See the idea"><h5 class="lesson-depth-title" data-no-narration>See the idea</h5>${r(l.intuition)}</div>
 <div class="lesson-panel" role="region" id="${id}-derive" data-depth="derive" aria-label="Work it out"><h5 class="lesson-depth-title" data-no-narration>Work it out</h5><ol class="derivation-steps">${l.steps.map((s,i)=>`<li id="${id}-step-${i+1}"><div class="step-number" aria-hidden="true">${String(i+1).padStart(2,'0')}</div><div><strong>${esc(s.title)}</strong>${r(s.body)}${s.tex?r(`$$${s.tex}$$`):''}<p class="step-reason"><span>Why this step works</span> ${esc(s.reason)}</p></div></li>`).join('')}</ol></div>
 <div class="lesson-panel" role="region" id="${id}-formal" data-depth="formal" aria-label="Go deeper"><h5 class="lesson-depth-title" data-no-narration>Go deeper</h5>${r(l.formal)}<div class="lesson-sources" data-no-narration><span>Further reading</span>${l.sources.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.title)} ${icon('ArrowUpRight01Icon')}</a>`).join('')}</div></div>
 ${l.visual?`<div class="visual-lesson" data-visual-lesson="${l.visual}" data-lesson-id="${id}" aria-label="Interactive model: ${esc(l.title)}">${visualFallback(l.visual,inline)}</div>`:''}
 ${reference?`<details class="lesson-reference" data-no-narration><summary>Open the reference diagram</summary>${reference}</details>`:''}
 <details class="lesson-practice" data-no-narration><summary>Test the idea ${icon('ArrowRight01Icon')}</summary><div class="practice-body"><p class="practice-label">FIRST, PREDICT</p>${r(l.practice.prompt)}<div class="practice-choices" role="group" aria-label="Choose an answer">${l.practice.choices.map((c,i)=>`<button type="button" disabled data-choice="${i}" data-choice-id="${c.id}" aria-pressed="false">${inline(c.text)}</button>`).join('')}</div><div class="practice-feedback" role="status"></div><details class="practice-static"><summary>Compare the reasoning</summary>${l.practice.choices.map(c=>`<p><strong>${inline(c.text)}</strong></p>${r(c.feedback)}`).join('')}</details><details data-help="hint" data-help-kind="concept"><summary>A hint</summary>${r(l.practice.hint)}</details><div class="transfer-problem"><div class="transfer-heading"><p class="practice-label">NOW CHANGE THE EXAMPLE</p><span data-transfer-item-label></span></div><div data-transfer-prompt>${r(l.transfer.prompt)}</div><form data-transfer hidden><label for="${id}-answer">Your result <span data-transfer-unit>${inline(l.transfer.unit||'')}</span></label><div class="transfer-input"><input type="text" inputmode="decimal" autocomplete="off" id="${id}-answer" required aria-describedby="${id}-answer-format"><button type="submit">Check ${icon('ArrowRight01Icon')}</button></div><small id="${id}-answer-format">Enter a decimal, a fraction such as 1/12, or scientific notation such as 1.2e3.</small></form><div class="transfer-feedback" role="status"></div><details data-help="hint" data-help-kind="transfer"><summary>A hint</summary><div data-transfer-hint>${r(l.transfer.hint)}</div></details><details class="transfer-solution" data-help="solution" data-help-kind="transfer"><summary>Work through the solution</summary><div data-transfer-solution>${r(l.transfer.solution)}</div></details><div class="transfer-next" hidden><button type="button" data-new-example>Try a different example</button><span>Previous attempts stay in your notebook.</span></div></div></div></details>
 <p class="lesson-takeaway">${esc(l.takeaway)}</p><div class="lesson-save-status" role="status" data-no-narration></div></section>`;
}
export function compassHTML(chapter,guides){
 if(chapter===undefined)return '';
 const n=+chapter,list=lessons.filter(l=>l.chapter===n);
 return `<div class="course-compass" data-no-narration><a href="course-map.html">${icon('Route01Icon')} Learning path</a><span data-route-next></span><a href="notebook.html">${icon('Notebook01Icon')} Field notebook</a></div><div class="return-to-lesson" hidden data-no-narration></div>${list.length?`<details class="chapter-bridges" data-no-narration><summary>${list.length} worked ${list.length===1?'bridge':'bridges'} in this chapter</summary><div>${list.map(l=>`<a href="#${l.id}">${esc(l.title)} ${icon('ArrowRight01Icon')}</a>`).join('')}</div></details>`:''}`;
}
export function preparationHTML(chapter,render){
 const required=requirementsFor(chapter);
 return `<ul class="skill-preparation">${required.map(s=>`<li><a href="${s.href}">${esc(s.title)} ↗</a><span>${render(s.check,{id:s.id,chapter:s.chapter}).html.replace(/^<p>|<\/p>\s*$/g,'')}</span></li>`).join('')}</ul>`;
}
export function diagnosticsHTML(render){
 const candidates=lessons.filter(l=>l.provides?.length);
 const r=(l,source)=>render(source,{id:l.id,chapter:l.chapter}).html;
 return `<section class="entry-diagnostics"><h2>Find your starting point</h2><p>Try a calculation before reading its explanation. If it is familiar, continue; if it catches you, a short lesson is one click away. These checks suggest preparation, not a placement grade.</p><div class="diagnostic-grid">${candidates.map(l=>`<details data-diagnostic="${l.id}"><summary>${esc(l.title)}${l.chapter>=20?' · deeper trail':''}</summary>${r(l,l.transfer.prompt)}<form hidden data-diagnostic-form><label for="diagnostic-${l.id}">Your result ${r(l,l.transfer.unit||'').replace(/^<p>|<\/p>\s*$/g,'')}</label><div class="transfer-input"><input id="diagnostic-${l.id}" type="text" inputmode="decimal" required placeholder="Decimal or fraction"><button type="submit">Check</button></div></form><p data-diagnostic-feedback role="status"></p><details><summary>Compare your reasoning</summary>${r(l,l.transfer.solution)}</details><a class="diagnostic-return" href="chapter-${l.chapter}.html#${l.id}">Work through the method and a different example →</a></details>`).join('')}</div></section>`;
}
export function courseMapHTML(guides,render){
 return `<article class="course-map"><header class="chapter-header"><span class="eyebrow">YOUR LEARNING PATH</span><h1>One idea opens<br><em>the next.</em></h1><p class="chapter-deck">Start with what you know. Follow the dependencies. Return to the exact point where a new idea becomes useful.</p></header>${diagnosticsHTML(render)}<div class="course-route-picker" role="group" aria-label="Choose a learning route">${routes.map((r,i)=>`<button disabled data-route="${r.id}" aria-pressed="${!i}"><strong>${r.title}</strong><span>${r.description}</span></button>`).join('')}</div><p class="route-status" role="status"></p><div class="course-map-list">${prerequisites.map((req,n)=>`<section class="course-node" data-chapter-node="${n}" style="--node-accent:var(--${n<6?'observer':n<11?'geometry':n<16?'curvature':n<20?'matter':'transport'})"><span class="course-node-number">${String(n).padStart(2,'0')}</span><div><a class="course-node-title" href="chapter-${n}.html">${esc(guides[n].title)} ${icon('ArrowUpRight01Icon')}</a><p>${esc(guides[n].payoff)}</p><div class="course-node-requires"><span>${req.length?'Builds on':'Starting point · basic calculus and linear algebra'}</span>${req.map(p=>`<a href="chapter-${p}.html" title="${esc(guides[p].title)}">${String(p).padStart(2,'0')} ${esc(guides[p].title)}</a>`).join('')}</div>${preparationHTML(n,render)}${lessons.filter(l=>l.chapter===n).map(l=>`<a class="map-lesson" href="chapter-${n}.html#${l.id}"><span>${esc(l.title)}</span><small data-evidence-for="${l.id}">Explore & test</small></a>`).join('')}</div></section>`).join('')}</div><details class="course-conventions"><summary>Scope, notation, and how to use this route</summary><p>The core route reaches observations and cosmology. Chapters 20–23 are optional extensions. The black-hole route includes their geometric prerequisites before Chapter 22; Hawking radiation uses explicitly stated quantum input. A solved example is evidence for that particular skill, not a claim of mastery of a chapter.</p><p><a href="reading-guide.html">Reading guide & conventions</a> · <a href="visual-language.html">Color & notation</a> · <a href="chapter-24.html">Synthesis and further study</a></p></details></article>`;
}
export function notebookHTML(){return `<article class="field-notebook"><header class="chapter-header"><span class="eyebrow">YOUR FIELD NOTEBOOK</span><h1>Keep the ideas<br><em>you make yours.</em></h1><p class="chapter-deck">Saved lessons, your observations, and the problems to revisit. Stored in this browser, with an export you can keep.</p></header><div class="notebook-actions"><button data-export-notebook="json">Export notebook</button><button data-export-notebook="md">Export as Markdown</button><label class="notebook-import">Import notebook<input type="file" accept="application/json,.json" data-import-notebook></label></div><p class="notebook-status" role="status"></p><section class="notebook-import-preview" hidden aria-label="Review notebook import"><h2>Restore your notebook</h2><p data-import-summary></p><label>When observations conflict<select data-import-preference><option value="local">Keep this browser’s observations</option><option value="imported">Use the imported observations</option></select></label><p>Attempt histories are combined without duplicate entries. The backup restores its learning route and selected explanation layers.</p><div><button data-apply-import>Import this backup</button><button data-cancel-import>Cancel</button></div></section><section class="review-queue"><h2>Return to an idea</h2><p class="notebook-help">Unfinished problems first; solved examples reappear after three days. Reading and listening are recorded separately by the reader.</p><div data-review-queue></div></section><section><h2>Your observations</h2><div data-notebook-entries></div></section><section><h2>Your practice history</h2><p class="notebook-help">Each result belongs to one example and records the help opened before that attempt. An independent check is evidence about that example, not a claim of mastery.</p><div data-attempt-history></div></section></article>`;}
export function publicCourseData(render,guides={}){
 const rendered=(l,item)=>({...item,promptHTML:render(item.prompt,{id:l.id,chapter:l.chapter}).html,hintHTML:render(item.hint,{id:l.id,chapter:l.chapter}).html,solutionHTML:render(item.solution,{id:l.id,chapter:l.chapter}).html,unitHTML:render(item.unit||'',{id:l.id,chapter:l.chapter}).html.replace(/^<p>|<\/p>\s*$/g,'')});
 return {version:2,routes,prerequisites,skills,chapterTitles:Object.fromEntries(Object.entries(guides).map(([chapter,guide])=>[chapter,guide.title])),lessons:lessons.map(l=>({...l,transfer:rendered(l,l.transfer),variants:l.variants.map(item=>rendered(l,item)),practice:{...l.practice,choices:l.practice.choices.map(c=>({...c,feedbackHTML:render(c.feedback,{id:l.id,chapter:l.chapter}).html}))}}))};
}
