import fs from 'node:fs';
import {ENTRY_HALF_SIZE, INJECTION_INTERVAL, COHORTS, INITIAL_PHASE, rainRadius} from '../web/earth-flow.js';
import {math,inline} from './math-system.mjs';
import * as icons from '@hugeicons/core-free-icons';
const escape=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
export function icon(name,cls=''){const data=icons[name];if(!data)throw Error(`Missing Hugeicon ${name}`);return `<svg class="hugeicon ${cls}" width="24" height="24" viewBox="0 0 24 24" fill="none" aria-hidden="true">${data.map(([tag,attrs])=>`<${tag} ${Object.entries(attrs).filter(([k])=>k!=='key').map(([k,v])=>`${k.replace(/[A-Z]/g,c=>'-'+c.toLowerCase())}="${escape(v)}"`).join(' ')}/>`).join('')}</svg>`;}
export const scenes=[
 {id:'earth',chapter:1,figure:'tidal-eigenvalues',title:'Compare two falling objects',deck:'Follow the rose points as they fall toward Earth. Watch the gap between points on the same radial line, then compare points side by side.',equation:String.raw`\htmlClass{math-transport}{v_r}=-\sqrt{\frac{2GM}{r}}`,note:'The teal grid joins freely falling observers; rose points make their motion visible. This model treats Earth as a nonrotating sphere. Each observer has fallen from rest very far away and is already moving when it enters the picture. New points enter from beyond the view, and the motion stops at the surface. The grid lines simply join observers at the same time.'},
 {id:'covector',chapter:2,figure:'vector-covector',title:'An arrow meets a family of planes',deck:'A covector measures how many level intervals a displacement crosses. Rotate the scene to see that this is a pairing, not a length.',equation:String.raw`\begin{gathered}\omega=dx,\quad v=(3,2,1)\\\omega(v)=3\end{gathered}`,min:0,max:100,value:100,control:'Follow the displacement',low:'Start',high:'Three intervals',note:'The numbers label the level sets of $x$ in three-dimensional Euclidean space. Small rings mark the exact intersections the arrow has reached. The control follows $\\lambda v$ as the displacement fraction $\\lambda$ runs from zero to one. Starting at level zero, three level intervals give $dx(v)=3$; the ring count is not a Euclidean length. At full extent, the arrow ends at $(3,2,1)$.'},
 {id:'cone',chapter:3,figure:'light-cone',title:'The shape of a possible future',deck:'A light cone becomes a surface when we restore a second space direction. Change the speed and watch the observer’s worldline tilt.',equation:String.raw`ds^2=-c^2dt^2+dx^2+dy^2,\quad v<c`,min:0,max:95,value:55,control:'Observer speed',low:'At rest',high:'Near light speed',note:'Solid strokes show the side nearer the camera; dashed strokes show the far side and update as you orbit. The brighter upper half is the future cone. Its finite rim is only the edge of the drawing, not a physical boundary. Two space dimensions are shown; the third is suppressed. The cone is a causal boundary, not a physical surface.'},
 {id:'sphere',chapter:8,figure:'sphere-holonomy',title:'Carry a direction. Discover curvature.',deck:'Move an arrow around three great-circle arcs. It stays parallel within each local tangent plane, yet returns pointing a quarter-turn away.',equation:String.raw`\Delta\alpha=\frac{A}{a^2}=\frac{\pi}{2}`,min:0,max:300,value:0,control:'Journey around the loop',low:'Start at the pole',high:'Return to the pole',note:'A sphere is an analogy for intrinsic curvature, not a picture of four-dimensional spacetime. The octant loop encloses one eighth of its area.'},
 {id:'tides',chapter:10,figure:'tidal-eigenvalues',title:'Gravity changes a cloud’s shape',deck:'A small freely falling cloud stretches radially and squeezes in two independent sideways directions. Rotate to find the dimension a flat diagram hides.',equation:String.raw`\frac{\ddot\xi^i}{\xi^i}=\frac{GM}{r^3}(2,-1,-1)`,min:0,max:100,value:35,control:'Early-time deformation',low:'Spherical cloud',high:'Stretched cloud',note:'The faint dashed circles retain the initial spherical shape. The local orthonormal axes are radial $\\hat r$ and two transverse directions $\\hat\\theta,\\hat\\phi$; the three eigenvalues in the equation follow that order. In this local, early-time visualization with initially comoving particles, lengths change by $(1+2s,1-s,1-s)$. It preserves volume only to first order in the small parameter $s$.'},
 {id:'embedding',chapter:17,figure:'black-hole-radii',title:'The same interval. A longer ruler.',deck:'Keep two coordinate radii fixed. Increase the black hole’s mass and measure how much farther apart they become on this spatial slice.',equation:String.raw`\begin{gathered}r_s=\frac{2GM}{c^2},\quad\Delta r=0.25R\\\Delta\ell=\int_{0.75R}^{R}\frac{dr}{\sqrt{1-r_s/r}}\end{gathered}`,min:5,max:65,value:25,control:'Mass at a fixed reference radius',low:'Smaller horizon',high:'Larger horizon',note:'All displayed lengths use one fixed reference radius $R$. Increasing $r_s/R$ increases mass while the ruler endpoints stay at $0.75R$ and $R$, outside the horizon. The rose path measures proper radial distance; coordinate radius is defined by circumference, not by this ruler. This is Flamm’s embedding of an equatorial, constant Schwarzschild-time slice, with $z=2\\sqrt{r_s(r-r_s)}$ up to an additive constant. Height is auxiliary, not time or a force. The outer edge is the chosen viewing radius, not an edge of space.'},
 {id:'wave',chapter:18,figure:'wave-polarizations',title:'One wave. Two ways to stretch.',deck:'Watch one detector ring. Compare plus and cross polarization, then separate what strain and frequency change.',equation:String.raw`\begin{gathered}h_+=h_0\sin(\omega z/c-\phi)\\x=x_0(1+h_+/2)\\y=y_0(1-h_+/2)\end{gathered}`,min:0,max:200,value:50,control:'Phase at the middle detector',low:'Start of cycle',high:'One full cycle',note:'The brighter middle ring is one detector plane; the quieter rings show different positions along the wave. Plus and cross are linear polarizations with stretching axes rotated by $45^\\circ$. Guides mark fixed coordinates, not material arms. Amplitude $h_0$ is dimensionless strain and is exaggerated here; displacement is accurate only to first order in strain. Frequency is given in units $c/L_0$, where $L_0$ is the undeformed ring radius. Changing frequency changes wavelength as $\\lambda=2\\pi c/\\omega$; the wave speed stays $c$. Animation advances $0.8L_0/c$ of model time per displayed second. These test particles do not form a material medium carrying sound.'},
 {id:'expansion',chapter:19,figure:'cosmic-expansion',title:'More distance. The same cosmic grid.',deck:'Choose a scale factor. Every comoving separation grows together; no point in the grid becomes a preferred center of the expansion.',equation:String.raw`\begin{gathered}\ell(t)=a(t)\Delta\chi\\d\ell^2=a^2(t)(dx^2+dy^2+dz^2)\end{gathered}`,min:60,max:150,value:100,control:'Scale factor',low:'0.6',high:'1.5',note:'The highlighted segment measures the changing separation of two fixed comoving markers. This is a finite window into a spatially flat FLRW slice, not a universe with an outer edge. The control selects a scale factor; it does not specify a cosmological expansion history.'},
 {id:'slices',chapter:20,figure:'adm-slicing',title:'One step in time. Two different choices.',deck:'Lapse carries you along the normal. Shift slides the coordinate grid sideways. Rotate the slices to separate these two pieces.',equation:String.raw`\begin{gathered}\partial_t=\htmlClass{math-observer}{Nn}+\htmlClass{math-transport}{\beta}\\\beta=\beta^i\partial_i\end{gathered}`,min:-100,max:100,value:40,control:'Coordinate shift',low:'Negative shift',high:'Positive shift',note:'Two spatial dimensions are shown on each slice; the vertical direction represents time schematically. The Euclidean display is not a spacetime distance measurement.'},
];
function fallbackSVG(s){if(s.id==='earth')return earthFallback();let svg=fs.readFileSync(`assets/figures/${s.figure}.svg`,'utf8').replace('class="gr-figure"','class="gr-figure embedded"');svg=svg.replace(/id="([^"]+)"/g,(_,id)=>`id="fallback-${s.id}-${id}"`).replace(/url\(#([^\)]+)\)/g,(_,id)=>`url(#fallback-${s.id}-${id})`).replace(/aria-labelledby="([^"]+)"/g,(_,ids)=>`aria-labelledby="${ids.split(' ').map(id=>'fallback-'+s.id+'-'+id).join(' ')}"`);return svg;}
export function scenePanel(s,{hero=false,diagram=''}={}){
 const earth=s.id==='earth',paired=!!diagram&&!hero;
 const heading=hero&&earth?'':`<div class="scene-heading"><span class="eyebrow">${icon('CubeIcon')} SPACETIME LAB / ${String(scenes.indexOf(s)+1).padStart(2,'0')}</span>${hero?'':`<h2>${s.title}</h2><p>${s.deck}</p>`}</div>`;
 const switcher=paired?`<div class="scene-view-switch" role="group" aria-label="Choose a view of ${escape(s.title)}"><button type="button" data-scene-mode="3d" aria-pressed="true" aria-controls="scene-${s.id}-stage">${icon('CubeIcon')}<span>Explore</span></button><button type="button" data-scene-mode="diagram" aria-pressed="false" aria-controls="scene-${s.id}-stage">${icon('Image01Icon')}<span>Diagram</span></button></div>`:'';
 const cameraControls=earth?'':`<div class="scene-camera-tools" role="group" aria-label="Camera"><button type="button" data-view="left" aria-label="Rotate scene left" title="Rotate left">${icon('ArrowLeft01Icon')}</button><button type="button" data-view="right" aria-label="Rotate scene right" title="Rotate right">${icon('ArrowRight01Icon')}</button><button type="button" data-view="reset" aria-label="Reset 3D view" title="Reset view">${icon('RefreshIcon')}</button></div>`;
 const viewbar=hero?'':`<div class="scene-viewbar">${switcher||'<span></span>'}<div class="scene-actions">${cameraControls}</div></div>`;
 let controls=earth?'':`<div class="scene-controls"><div class="scene-parameter"><label for="scene-${s.id}-parameter">${s.control}</label><output for="scene-${s.id}-parameter"></output></div><input id="scene-${s.id}-parameter" type="range" min="${s.min}" max="${s.max}" value="${s.value}" step="1" aria-label="${escape(s.control)}"><div class="range-limits"><span>${s.low}</span><span>${s.high}</span></div></div>`;
 if(s.id==='wave'){
  const phase=controls.slice('<div class="scene-controls">'.length,-6);
  controls=`<div class="scene-controls"><div class="scene-experiment-bar"><button type="button" class="scene-play" data-wave-play aria-pressed="false" aria-label="Play wave"><span data-play-glyph="play">${icon('PlayIcon')}</span><span data-play-glyph="pause">${icon('PauseIcon')}</span><span data-wave-play-label>Play</span></button><div class="scene-polarization" role="group" aria-label="Wave polarization"><button type="button" data-wave-polarization="plus" aria-pressed="true">${math('+')}<span>Plus</span></button><button type="button" data-wave-polarization="cross" aria-pressed="false">${math(String.raw`\times`)}<span>Cross</span></button></div></div>${phase}<div class="scene-wave-parameters"><div><div class="scene-parameter"><label for="scene-wave-amplitude">Strain amplitude</label><output for="scene-wave-amplitude" data-wave-amplitude-value></output></div><input id="scene-wave-amplitude" data-wave-amplitude type="range" min="0" max="35" value="25" step="1" aria-label="Strain amplitude"><p class="scene-control-caption">Larger strain, larger deformation.</p></div><div><div class="scene-parameter"><label for="scene-wave-frequency">Angular frequency</label><output for="scene-wave-frequency" data-wave-frequency-value></output></div><input id="scene-wave-frequency" data-wave-frequency type="range" min="75" max="250" value="150" step="5" aria-label="Angular frequency"><p class="scene-control-caption" data-wave-wavelength></p></div></div></div>`;
 }
 if(s.id==='embedding')controls=controls.slice(0,-6)+`<div class="scene-measurement"><div><span>Proper length of the rose ruler</span><strong data-embedding-measure></strong></div><span data-embedding-ratio></span></div></div>`;
 return `<section class="spacetime-lab ${hero?'hero-scene':''}" id="scene-${s.id}" data-scene="${s.id}" data-active-view="3d">${heading}${viewbar}<div class="scene-stage" id="scene-${s.id}-stage" role="group" aria-label="Interactive 3D: ${escape(s.title)}"><div class="scene-fallback">${fallbackSVG(s)}<span>Interactive geometry is loading.</span></div>${paired?`<div class="scene-diagram" hidden>${diagram}</div>`:''}${earth?'':'<span class="scene-gesture-hint" aria-hidden="true">Drag to orbit · pinch to zoom</span>'}</div>${controls}${hero?'':`<div class="scene-equation equation" tabindex="0" role="region" aria-label="Equation">${s.id==='wave'?`<div data-wave-equation>${math(s.equation,true,s.chapter)}</div>`:math(s.equation,true,s.chapter)}</div><p class="scene-note"><strong>Read the scene.</strong> ${inline(s.note,s.chapter)}</p>${earth?earthExplanation():''}`}</section>`;
}

function earthFallback(){
 const paths=[];
 for(let cohort=0;cohort<COHORTS;cohort++)for(let axis=0;axis<2;axis++)for(const side of [-1,1]){
  let d='';
  for(let i=0;i<=160;i++){
   const p=axis===0?[side*ENTRY_HALF_SIZE,ENTRY_HALF_SIZE*(-1+i/80)]:[ENTRY_HALF_SIZE*(-1+i/80),side*ENTRY_HALF_SIZE],r0=Math.hypot(...p);
   const r=rainRadius(r0,cohort*INJECTION_INTERVAL+INITIAL_PHASE);
   if(r<1.04||r>4.7){d='';continue;}
   const x=450+p[0]*r/r0*47,y=225+p[1]*r/r0*47;
   if(d)paths.push(`<path d="${d} L${x.toFixed(2)} ${y.toFixed(2)}"/>`);
   d=`M${x.toFixed(2)} ${y.toFixed(2)}`;
  }
 }
 return `<svg class="gr-figure embedded" viewBox="0 0 900 480" role="img" aria-label="A static equatorial section of the falling grid: neighboring observers move inward and the connecting lines bend."><g fill="none" stroke="var(--geometry,#007c78)" opacity=".45">${paths.join('')}</g><circle cx="450" cy="225" r="47" fill="var(--figure-tint,#e2ece7)" stroke="var(--geometry,#007c78)"/><text x="450" y="231" text-anchor="middle" fill="var(--ink,#242931)" font-family="Manrope,sans-serif" font-size="18">Earth</text><text x="450" y="457" text-anchor="middle" fill="var(--muted,#646b72)" font-family="Manrope,sans-serif" font-size="16">A still moment in a freely falling reference grid</text></svg>`;
}
function earthExplanation(){return `<details class="flow-explanation"><summary>How this animation is calculated</summary><div><p>Each rose point follows the speed rule derived in §1.10. Integrating that rule tells us where to draw the point at a later time:</p><div class="equation">${math(String.raw`\begin{gathered}\frac{dr}{dt}=-\sqrt{\frac{2GM}{r}}\\r(t)=\left[r_0^{3/2}-\frac32\sqrt{2GM}\,t\right]^{2/3}\end{gathered}`,true,1)}</div><p>${inline('$r_0$ is the distance from Earth’s center when the point enters, and $t$ is the time since entry. $M$ is Earth’s mass; $G$ is Newton’s gravitational constant. The formula applies until the point reaches the surface.',1)}</p><p>The points show a continuous stream of falls with these starting conditions. The connecting lines help you compare their positions. They are neither material threads nor the paths of individual objects.</p><p>Motion is shown at 110 times real time. The model uses Earth’s mean radius and gravitational parameter, giving an incoming surface speed of about ${inline('$11.2\\,\\mathrm{km/s}$',1)}. It omits rotation, the atmosphere’s resistance, and Earth’s interior. The glow and lighting identify the globe; they carry no gravity data.</p><p>This speed rule also occurs in a useful relativistic description of spherical gravity. <a href="chapter-17.html">Chapter 17</a> develops the geometry needed to understand that description. The technical source is <a href="https://arxiv.org/abs/gr-qc/0411060">Hamilton and Lisle’s river model</a>.</p><p class="flow-credit">Presentation inspired by <a href="https://www.youtube.com/watch?v=wrwgIjBUYVc&amp;t=502s">ScienceClic’s visualization</a>. Earth texture: NASA, <a href="https://science.nasa.gov/earth/earth-observatory/blue-marble-next-generation/base-map/">Blue Marble: Next Generation</a>. <a href="credits.html">Sources and image rights ↗</a></p></div></details>`;}
