/* Original, event-driven geometric arguments. All visible mathematics is KaTeX. */
const active=new Map();
const storageKey='gr-visual-lessons:v1';
const PI=Math.PI;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const math=(tex,role='')=>`<span class="vl-math ${role?'math-'+role:''}">${window.katex.renderToString(tex,{throwOnError:true,strict:false})}</span>`;
const f=(n,d=3)=>Math.abs(n)<10**(-d)?'0':Number(n.toFixed(d)).toString();
const dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0);
const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
const scale=(v,s)=>v.map(x=>x*s);
const add=(a,b)=>a.map((x,i)=>x+b[i]);
const rotate=(v,n,t)=>add(add(scale(v,Math.cos(t)),scale(cross(n,v),Math.sin(t))),scale(n,dot(n,v)*(1-Math.cos(t))));
export function chartCoordinates(point){const [X,Y,Z]=point;return {north:Math.abs(1-Z)<1e-12?null:[X/(1-Z),Y/(1-Z)],south:Math.abs(1+Z)<1e-12?null:[X/(1+Z),Y/(1+Z)]};}
export function polarMeasurements(r,dr,dtheta){return {radial:dr,angular:r*dtheta,tangent:Math.hypot(dr,r*dtheta),chord:Math.sqrt(dr*dr+2*r*(r+dr)*(1-Math.cos(dtheta))) };}
export function polarBasis(theta){const er=[Math.cos(theta),Math.sin(theta)],et=[-Math.sin(theta),Math.cos(theta)],components=[Math.cos(theta),-Math.sin(theta)];return {er,et,components,vector:add(scale(er,components[0]),scale(et,components[1])),componentDerivative:add(scale(er,-Math.sin(theta)),scale(et,-Math.cos(theta))),basisDerivative:add(scale(et,components[0]),scale(er,-components[1]))};}
export const transportVertices=[[1,0,0],[0,0,1],[0,1,0],[1,0,0]];
export function transportedFrame(progress){const t=Math.max(0,Math.min(3,progress)),segment=Math.min(2,Math.floor(t)),angle=(t-segment)*PI/2;let vector=[0,0,1];for(let i=0;i<segment;i++)vector=rotate(vector,cross(transportVertices[i],transportVertices[i+1]),PI/2);const axis=cross(transportVertices[segment],transportVertices[segment+1]);return {point:rotate(transportVertices[segment],axis,angle),vector:rotate(vector,axis,angle)};}
export function radialNullDirections(rho){return {ingoing:-1,outgoing:(rho-1)/(rho+1)};}
const defaults={charts:{point:'example',chart:'north'},metric:{radius:3,scale:1},basis:{angle:45},transport:{step:0},horizon:{rho:3}};
const points={example:[.8,0,.6],oblique:[2/3,1/3,2/3],equator:[1,0,0],south:[.8,0,-.6],pole:[0,0,1]};
function validateState(type,stored){const state={...defaults[type]};if(type==='charts'){if(Object.hasOwn(points,stored.point))state.point=stored.point;if(['north','south'].includes(stored.chart))state.chart=stored.chart;}else if(type==='metric'){if([1,3,6].includes(stored.radius))state.radius=stored.radius;if([1,10,30].includes(stored.scale))state.scale=stored.scale;}else if(type==='basis'){if(Number.isFinite(stored.angle)&&stored.angle>=0&&stored.angle<=360)state.angle=stored.angle;}else if(type==='transport'){if([0,1,2,3].includes(stored.step))state.step=stored.step;}else if([.5,1,3].includes(stored.rho))state.rho=stored.rho;return state;}
function readState(id,type){let stored={};try{stored=JSON.parse(localStorage.getItem(storageKey)||'{}')[id]?.state||{};}catch{}return validateState(type,stored);}
export function restoreVisualLessonState(id,state){const instance=active.get(id);if(!instance||!state||typeof state!=='object')return false;Object.assign(instance.state,validateState(instance.type,state));instance.render({persist:true});return true;}
export function getVisualLessonState(){return [...active.values()].map(({id,type,state})=>({id,type,state:{...state}}));}
function save(instance){try{const all=JSON.parse(localStorage.getItem(storageKey)||'{}');all[instance.id]={type:instance.type,state:instance.state};localStorage.setItem(storageKey,JSON.stringify(all));}catch{}instance.el.dataset.visualState=JSON.stringify(instance.state);document.dispatchEvent(new CustomEvent('gr:visual-change',{detail:{id:instance.id,type:instance.type,state:{...instance.state}}}));}
const svgHead=(name)=>`<svg viewBox="0 0 520 360" role="img" aria-label="${esc(name)}" xmlns="http://www.w3.org/2000/svg"><defs><marker id="vl-arrow-${name.replace(/\W/g,'')}" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0 0L8 4L0 8Z" fill="context-stroke"/></marker></defs>`;
function path(points,role='geometry',extra=''){return `<path class="vl-stroke vl-${role}" d="${points.map(([x,y],i)=>`${i?'L':'M'}${f(x,4)},${f(y,4)}`).join(' ')}" ${extra}/>`;}
function line(a,b,role='geometry',extra=''){return path([a,b],role,extra);}
function circle(x,y,r,role='observer',extra=''){return `<circle class="vl-dot vl-${role}" cx="${x}" cy="${y}" r="${r}" ${extra}/>`;}
function label(tex,x,y,role='',extra=''){return `<span class="vl-label ${extra}" data-vl-x="${x}" data-vl-y="${y}" style="left:${x/5.2}%;top:${y/3.6}%">${math(tex,role)}</span>`;}
function arrow(a,b,role='observer',extra=''){const dx=b[0]-a[0],dy=b[1]-a[1],length=Math.hypot(dx,dy);if(length<.2)return '';const ux=dx/length,uy=dy/length,size=Math.min(10,length*.35);return line(a,b,role,extra)+`<path class="vl-fill vl-${role}" d="M${b}L${b[0]-size*ux+size*.48*uy},${b[1]-size*uy-size*.48*ux}L${b[0]-size*ux-size*.48*uy},${b[1]-size*uy+size*.48*ux}Z"/>`;}
function readout(labelText,value,role='geometry',detail=''){return `<div class="vl-readout"><span>${labelText}</span><strong>${math(value,role)}</strong>${detail?`<small>${detail}</small>`:''}</div>`;}
function choices(key,items,state){return `<div class="vl-choices" role="group" aria-label="${esc(key)}">${items.map(([value,text])=>`<button type="button" data-vl-choice="${key}" data-value="${value}" aria-pressed="${String(state[key])===String(value)}">${text}</button>`).join('')}</div>`;}
const titles={charts:'Two maps. One sphere.',metric:'A coordinate step is not yet a length.',basis:'The arrow stays. Its components change.',transport:'Carry a direction without turning it.',horizon:'Follow the future light can travel.'};
const descriptions={charts:'Two stereographic coordinate charts describe the same point on a unit sphere. The chart projected from the north pole excludes that pole; the other chart covers it.',metric:'The radial side of a polar cell has length delta r. Its angular side has length r times delta theta. Changing the radius changes the angular ruler.',basis:'A fixed Cartesian vector points east while the local orthonormal polar basis rotates. Changing components and changing basis vectors cancel exactly.',transport:'Project onto a tangent plane, then parallel transport a tangent vector around three great-circle arcs bounding one octant of a unit sphere. The vector returns rotated through a right angle.',horizon:'A radial causal diagram for stationary Schwarzschild spacetime in regular ingoing coordinates. Future time points upward. Both future radial light directions point toward smaller radius inside the horizon.'};
function chartView(state){const p=points[state.point],coords=chartCoordinates(p),north=state.chart==='north',current=north?coords.north:coords.south;
 const to=([x,y,z])=>[230+96*(Math.sqrt(3)*x/2-y/2),175+96*(x/4+Math.sqrt(3)*y/4-Math.sqrt(3)*z/2)],P=to(p),N=to([0,0,1]),S=to([0,0,-1]),target=current?to([current[0],current[1],0]):null;
 let drawing=svgHead('Sphere stereographic projection');
 for(let k=-3;k<=3;k++){drawing+=line(to([-1.4,k*.4,0]),to([2.2,k*.4,0]),'muted','opacity=".35"')+line(to([k*.4,-1.2,0]),to([k*.4,1.2,0]),'muted','opacity=".35"');}
 drawing+=`<circle class="vl-sphere-section" cx="230" cy="175" r="96"/>`;
 for(let j=1;j<8;j++){const t=j*PI/8;drawing+=path(Array.from({length:65},(_,i)=>to([Math.sin(t)*Math.cos(i*PI/32),Math.sin(t)*Math.sin(i*PI/32),Math.cos(t)])),'geometry','opacity=".3"');}
 for(let j=0;j<8;j++)drawing+=path(Array.from({length:65},(_,i)=>to([Math.sin(i*PI/32)*Math.cos(j*PI/8),Math.sin(i*PI/32)*Math.sin(j*PI/8),Math.cos(i*PI/32)])),'geometry','opacity=".3"');
 drawing+=line(N,S,'muted','stroke-dasharray="4 5"');if(target)drawing+=line(north?N:S,target,north?'transport':'geometry')+circle(...target,5,north?'transport':'geometry');drawing+=circle(...N,4,'muted')+circle(...S,4,'muted')+circle(...P,7,'observer')+'</svg>';
 drawing+=label('N',N[0]-15,N[1]-12)+label('S',S[0]-15,S[1]+12)+(state.point!=='pole'?label('P',P[0]+18,P[1]-14,'observer'):'');if(target)drawing+=label(north?'(u,v)':'(p,q)',target[0]+16,target[1]+18,north?'transport':'geometry');
 const pointTuple=state.point==='oblique'?String.raw`\left(\tfrac23,\tfrac13,\tfrac23\right)`:`(${f(p[0])},${f(p[1])},${f(p[2])})`;
 const pair=v=>v?String.raw`\left(${f(v[0])},\,${f(v[1])}\right)`:null;
 const readouts=`${readout('The point on the sphere',String.raw`(X,Y,Z)=${pointTuple}`,'observer')}
 <div class="vl-coordinate-pair"><div class="${north?'is-active':''}">${coords.north?readout('North-pole projection',String.raw`(u,v)=${pair(coords.north)}`,'transport'):readout('North-pole projection',String.raw`\text{not defined}`,'curvature','The excluded pole needs the other chart.')}</div><div class="${!north?'is-active':''}">${coords.south?readout('South-pole projection',String.raw`(p,q)=${pair(coords.south)}`,'geometry'):readout('South-pole projection',String.raw`\text{not defined}`,'curvature')}</div></div>
 <p class="vl-takeaway">${state.point==='pole'?'The point still exists. Only one coordinate description fails.':'Changing the chart changes the numbers assigned to the point. The point itself stays put.'}</p>`;
 const controls=`<div class="vl-control-row"><span>Point</span>${choices('point',[['example','Worked example'],['oblique','Two coordinates'],['equator','Equator'],['south','Southward'],['pole','North pole']],state)}</div><div class="vl-control-row"><span>Projection from</span>${choices('chart',[['north','North pole'],['south','South pole']],state)}</div>`;
 return {drawing,readouts,controls,note:`The sphere is shown in an orthographic diagram until the rotatable view is ready. ${math(String.raw`(p,q)=\dfrac{(u,v)}{u^2+v^2}`,'geometry')} on the overlap.`};}
function metricView(state){const r=state.radius,dr=.03*state.scale,dt=.01*state.scale,m=polarMeasurements(r,dr,dt);
 // A local magnification uses one shared scale for both physical directions.
 const localScale=180/Math.max(dr,r*dt),project=(R,T)=>[150+localScale*(R*Math.cos(T)-r),285-localScale*R*Math.sin(T)];
 const a=project(r,0),b=project(r+dr,0),c=project(r+dr,dt),d=project(r,dt),arc=Array.from({length:40},(_,i)=>project(r,dt*i/39)),outer=Array.from({length:40},(_,i)=>project(r+dr,dt*i/39));
 let drawing=svgHead('Polar cell with physical rulers');
 drawing+=`<path class="vl-cell-fill" d="M${a}L${b}${outer.slice(1).map(p=>'L'+p).join('')}L${d}${arc.slice().reverse().map(p=>'L'+p).join('')}Z"/>`;
 drawing+=path(arc,'transport','stroke-width="4"')+path(outer,'geometry','opacity=".4"')+line(a,b,'observer','stroke-width="4"')+line(d,c,'geometry','opacity=".4"')+line(a,c,'ink','stroke-dasharray="5 5"');
 const tangent=[a[0]+localScale*dr,a[1]-localScale*r*dt];drawing+=line(a,tangent,'curvature','stroke-width="2"')+circle(...a,5,'ink')+circle(...c,5,'ink');
 // The context inset is small, with the same two radii indicated.
 const o=[429,73],rr=44,aa=dt;drawing+=`<circle class="vl-context-circle" cx="${o[0]}" cy="${o[1]}" r="${rr}"/>`+line(o,[o[0]+rr,o[1]],'muted')+line(o,[o[0]+rr*Math.cos(aa),o[1]-rr*Math.sin(aa)],'muted')+path(Array.from({length:30},(_,i)=>[o[0]+rr*Math.cos(aa*i/29),o[1]-rr*Math.sin(aa*i/29)]),'transport','stroke-width="3"')+circle(...o,3,'muted');
 drawing+='</svg>'+label(String.raw`\Delta r`,(a[0]+b[0])/2,a[1]+26,'observer')+label(String.raw`r\,\Delta\theta`,Math.min(...arc.map(p=>p[0]))-35,(a[1]+d[1])/2,'transport')+label('r',449,97,'geometry');
 const readouts=`${readout('Radial ruler',String.raw`\Delta r=${f(dr)}\,\mathrm m`,'observer')}${readout('Angular ruler',String.raw`r\,\Delta\theta=${f(m.angular)}\,\mathrm m`,'transport')}${readout('Tangent prediction',String.raw`\ell_{\rm tan}=${f(m.tangent,5)}\,\mathrm m`,'curvature')}${readout('Actual endpoint distance',String.raw`\ell_{\rm end}=${f(m.chord,5)}\,\mathrm m`,'','Straight distance in the Euclidean plane.')}
 <p class="vl-takeaway">${state.scale===1?'Shrink the cell: the tangent prediction approaches the endpoint distance.':'A larger cell exposes the error. The metric predicts infinitesimal length, not an arbitrary finite diagonal.'}</p>`;
 const controls=`<div class="vl-control-row"><span>Radius</span>${choices('radius',[[1,math(String.raw`1\,\mathrm m`)],[3,math(String.raw`3\,\mathrm m`)],[6,math(String.raw`6\,\mathrm m`)]],state)}</div><div class="vl-control-row"><span>Coordinate steps</span>${choices('scale',[[30,'Large'],[10,'Smaller'],[1,'Tiny cell']],state)}</div>`;
 return {drawing,readouts,controls,note:`Each cell is magnified to fit, with the same scale in both directions. ${math(String.raw`\Delta\theta=${f(dt)}\,\mathrm{rad}`)}. Circular arc length is exactly ${math(String.raw`r\,\Delta\theta`,'transport')}; the tangent diagonal is an approximation for finite steps.`};}
function basisView(state){const theta=state.angle*PI/180,m=polarBasis(theta),o=[250,180],len=118,point=v=>[o[0]+len*v[0],o[1]-len*v[1]],east=point([1,0]),radial=point(scale(m.er,m.components[0]));
 let drawing=svgHead('Rotating polar basis and a fixed eastward arrow')+line([68,180],[448,180],'muted')+line([250,28],[250,331],'muted')+`<circle class="vl-context-circle" cx="250" cy="180" r="118"/>`;
 drawing+=line(o,radial,'transport','stroke-width="7" opacity=".27"')+line(radial,east,'geometry','stroke-width="7" opacity=".27"')+arrow(o,point(m.er),'transport')+arrow(o,point(m.et),'geometry')+arrow(o,east,'observer','stroke-width="4"')+circle(...o,4,'ink');
 const rotateLabel=(v,tex,role)=>label(tex,o[0]+145*v[0],o[1]-145*v[1],role);
 drawing+='</svg>'+rotateLabel(m.er,String.raw`\hat{\mathbf e}_r`,'transport')+rotateLabel(m.et,String.raw`\hat{\mathbf e}_\theta`,'geometry')+label(String.raw`\mathbf V`,394,203,'observer');
 const readouts=`${readout('Same vector, always',String.raw`\mathbf V=(1,0)`,'observer')}${readout('Radial component',String.raw`V^{\hat r}=\cos\theta=${f(m.components[0])}`,'transport')}${readout('Angular component',String.raw`V^{\hat\theta}=-\sin\theta=${f(m.components[1])}`,'geometry')}
 <div class="vl-identity">${math(String.raw`\begin{aligned}\frac{d\mathbf V}{d\theta}&=\frac{dV^{\hat a}}{d\theta}\hat{\mathbf e}_a+V^{\hat a}\frac{d\hat{\mathbf e}_a}{d\theta}\\&=(0,-1)+(0,1)=0\end{aligned}`)}</div><p class="vl-takeaway">Differentiating only the component numbers would invent a change in a vector that has not moved.</p>`;
 const controls=`<label class="vl-range"><span>Basis angle ${math(String.raw`\theta=${f(state.angle)}^\circ`,'geometry')}</span><input type="range" min="0" max="360" step="1" value="${state.angle}" aria-label="Polar basis angle" aria-valuetext="${state.angle} degrees"></label>${choices('angle',[[0,math(String.raw`0^\circ`)],[45,math(String.raw`45^\circ`)],[90,math(String.raw`90^\circ`)],[180,math(String.raw`180^\circ`)]],state)}`;
 return {drawing,readouts,controls,note:`The control displays degrees; derivatives use radians. The basis is orthonormal. In the coordinate basis, ${math(String.raw`V^\theta=-\sin\theta/r`)}; hats distinguish the unit-basis components.`};}
const transportSteps=['Tangent plane','First arc','Second arc','Closed loop'];
function projectSphere(p){return [255+112*(.78*p[0]-.67*p[1]),196+112*(.36*p[0]+.42*p[1]-.83*p[2])];}
function transportView(state){const step=state.step,frame=transportedFrame(step),P=projectSphere(frame.point),tip=projectSphere(add(frame.point,scale(frame.vector,.65)));
 let drawing=svgHead('Parallel transport around a sphere octant');for(let j=1;j<6;j++){const theta=j*PI/6;drawing+=path(Array.from({length:97},(_,i)=>projectSphere([Math.sin(theta)*Math.cos(i*PI/48),Math.sin(theta)*Math.sin(i*PI/48),Math.cos(theta)])),'muted','opacity=".4"');}for(let j=0;j<6;j++)drawing+=path(Array.from({length:97},(_,i)=>projectSphere([Math.sin(i*PI/48)*Math.cos(j*PI/6),Math.sin(i*PI/48)*Math.sin(j*PI/6),Math.cos(i*PI/48)])),'muted','opacity=".4"');
 for(let j=0;j<3;j++){const axis=cross(transportVertices[j],transportVertices[j+1]);drawing+=path(Array.from({length:40},(_,i)=>projectSphere(rotate(transportVertices[j],axis,i*PI/78))),j<step?'transport':'muted',j<step?'stroke-width="4"':'stroke-dasharray="4 5"');}
 if(step===0){const corners=[[-.45,-.45],[.45,-.45],[.45,.45],[-.45,.45]].map(([y,z])=>projectSphere([1,y,z]));drawing+=`<path class="vl-cell-fill" d="M${corners.join('L')}Z"/>`+arrow(P,projectSphere([1.48,0,.65]),'observer','stroke-width="2"')+arrow(P,projectSphere([1.45,0,0]),'geometry','stroke-width="2"');}
 drawing+=arrow(P,tip,'transport','stroke-width="4"');if(step===3)drawing+=arrow(P,projectSphere(add(frame.point,[0,0,.65])),'observer','stroke-width="3"');drawing+=circle(...P,6,'observer')+'</svg>';
 for(const [tex,p] of [['A',[1,0,0]],['N',[0,0,1]],['B',[0,1,0]]]){const q=projectSphere(p);drawing+=label(tex,q[0]+(tex==='B'?-22:20),q[1]+(tex==='N'?-15:17),'');}
 const readouts=[
 `${readout('Keep the tangential part',String.raw`\mathbf a_T=\mathbf a-(\mathbf a\cdot\mathbf n)\mathbf n`,'transport')}<p class="vl-takeaway">The sphere’s normal is perpendicular to the tangent plane. Remove the normal component to see the tangent vector. Transport applies this projection to the derivative along a path.</p>`,
 `${readout('Arrive at the north pole',String.raw`\mathbf V=(-1,0,0)`,'transport')}${readout('No intrinsic turn',String.raw`\nabla_{\dot\gamma}\mathbf V=0`,'geometry')}<p class="vl-takeaway">The ambient arrow changes direction as the tangent plane changes. Its change has no tangential part.</p>`,
 `${readout('Arrive at the equator',String.raw`\mathbf V=(-1,0,0)`,'transport')}<p class="vl-takeaway">Along this second arc, the arrow stays fixed even in the surrounding space: it is perpendicular to the great-circle plane.</p>`,
 `${readout('Return to the starting point',String.raw`\mathbf V_{\rm final}=(0,1,0)`,'transport')}${readout('Compare at the same tangent plane',String.raw`|\Delta\alpha|=\frac\pi2`,'curvature')}<p class="vl-takeaway">The starting and returning arrows live in the same tangent plane. Their right-angle mismatch records the curvature enclosed by the loop.</p>`
 ][step];
 return {drawing,readouts,controls:choices('step',transportSteps.map((s,i)=>[i,`<span class="vl-step-number">${i+1}</span>${s}`]),state),note:step===3?`For this unit sphere, ${math(String.raw`\left|\Delta\alpha\right|=\iint K\,dA=\pi/2`,'curvature')}. Orientation sets the sign.`:'The path follows great circles. Rotating the arrow with each great-circle arc gives exact parallel transport on a sphere.'};}
function horizonView(state){const rho=state.rho,directions=radialNullDirections(rho),unit=rho===3?90:rho===1?170:300,origin=[45,298],horizon=origin[0]+unit,event=[origin[0]+unit*rho,origin[1]],rise=Math.min(1.55,rho-.08,190/unit),inc=[event[0]-unit*rise,event[1]-unit*rise],out=[event[0]+unit*directions.outgoing*rise,event[1]-unit*rise];
 let drawing=svgHead('Future radial null directions near a Schwarzschild horizon');
 drawing+=`<rect class="vl-horizon-interior" x="45" y="30" width="${horizon-45}" height="300"/>`+line([horizon,28],[horizon,325],'curvature','stroke-dasharray="4 5"');
 drawing+=line([45,330],[484,330],'muted')+arrow([45,330],[45,27],'muted')+`<path class="vl-cone-fill" d="M${event}L${inc}L${out}Z"/>`+arrow(event,inc,'transport','stroke-width="3.5"')+arrow(event,out,'observer','stroke-width="3.5"')+circle(...event,6,'ink');
 const ticks=rho===3?[1,2,3,4]:rho===1?[.5,1,1.5,2]:[.25,.5,.75,1,1.25],times=rho===3?[0,1,2]:rho===1?[0,.5,1]:[0,.5];
 for(const x of ticks)drawing+=line([45+unit*x,326],[45+unit*x,334],'muted');for(const t of times)drawing+=line([41,298-unit*t],[49,298-unit*t],'muted');
 drawing+='</svg>'+label(String.raw`\rho`,490,346)+label(String.raw`\tau_{\rm plot}`,35,15);for(const x of ticks)drawing+=label(f(x),45+unit*x,348,x===1?'curvature':'');for(const t of times)drawing+=label(f(t),25,298-unit*t);
 const readouts=`${readout('Selected event',String.raw`\rho=${rho}`,'geometry')}${readout('Ingoing light',String.raw`\frac{d\rho}{d\tau_{\rm plot}}=-1`,'transport')}${readout('Outgoing light',String.raw`\frac{d\rho}{d\tau_{\rm plot}}=${rho===.5?String.raw`-\frac13`:rho===3?String.raw`\frac12`:'0'}`,'observer')}<p class="vl-takeaway">${rho>1?'Outside: outward light can move to larger radius. Massive particles have future directions strictly inside the cone.':rho===1?'On the horizon: outward light stays at the same radius. It still moves into the future.':'Inside: both future light directions have decreasing radius. Every future timelike direction lies between them.'}</p>`;
 return {drawing,readouts,controls:choices('rho',[[3,'Outside'],[1,'On the horizon'],[.5,'Inside']],state),note:`${math(String.raw`\rho=r/r_s,\quad\tau_{\rm plot}=cv/r_s-\rho`)}. Both axes are dimensionless and use equal unit scales. The window magnifies near the horizon; this is coordinate time, not proper time. These slopes describe local null directions. The event horizon is globally defined; a zero coordinate speed alone does not locate one.`};}
const views={charts:chartView,metric:metricView,basis:basisView,transport:transportView,horizon:horizonView};
function mount(el){const type=el.dataset.visualLesson,id=el.dataset.lessonId||el.id||type;if(!views[type]||active.has(id))return null;const narration=el.querySelector('.narration-script'),passageTools=el.querySelector('.passage-tools'),state=readState(id,type),abort=new AbortController();const instance={id,type,state,el};active.set(id,instance);
 el.innerHTML=`<div class="vl-topline"><span class="vl-kicker">Visual argument</span><span class="vl-spatial-hint" hidden>Drag to rotate</span></div><h4 class="vl-title">${titles[type]}</h4><p class="vl-description">${descriptions[type]}</p><div class="vl-layout"><div class="vl-drawing"><div class="vl-static"></div><div class="vl-spatial" hidden></div></div><div class="vl-readouts"></div></div><div class="vl-controls"></div><p class="vl-note"></p>`;
 if(narration)el.append(narration);if(passageTools)el.querySelector('.vl-topline').append(passageTools);
 const staticEl=el.querySelector('.vl-static'),readouts=el.querySelector('.vl-readouts'),controls=el.querySelector('.vl-controls'),note=el.querySelector('.vl-note');
 let spatial=null,disposed=false;
 function layoutLabels(){const rect=staticEl.getBoundingClientRect(),unit=Math.min(rect.width/520,rect.height/360),left=(rect.width-520*unit)/2,top=(rect.height-360*unit)/2;for(const l of staticEl.querySelectorAll('[data-vl-x]')){l.style.left=`${left+unit*l.dataset.vlX}px`;l.style.top=`${top+unit*l.dataset.vlY}px`;}}
 const labelResize=new ResizeObserver(layoutLabels);labelResize.observe(staticEl);
 function render({controlUpdate=true,persist=false}={}){const view=views[type](state);staticEl.innerHTML=view.drawing;layoutLabels();readouts.innerHTML=view.readouts;note.innerHTML=view.note;if(controlUpdate)controls.innerHTML=view.controls;else{const angleLabel=controls.querySelector('.vl-range>span');if(angleLabel)angleLabel.innerHTML=`Basis angle ${math(String.raw`\theta=${f(state.angle)}^\circ`,'geometry')}`;controls.querySelectorAll('[data-vl-choice]').forEach(b=>b.setAttribute('aria-pressed',String(String(state[b.dataset.vlChoice])===b.dataset.value)));}el.dataset.visualState=JSON.stringify(state);if(spatial&&type==='charts')note.innerHTML=`${math(String.raw`(p,q)=\dfrac{(u,v)}{u^2+v^2}`,'geometry')} on the overlap. The highlighted projection selects one chart; both coordinate descriptions remain visible.`;const range=controls.querySelector('input[type=range]');if(range)range.value=state.angle;spatial?.update();if(persist)save(instance);}
 controls.addEventListener('click',event=>{const button=event.target.closest('[data-vl-choice]');if(!button)return;state[button.dataset.vlChoice]=typeof defaults[type][button.dataset.vlChoice]==='number'?+button.dataset.value:button.dataset.value;render({controlUpdate:false,persist:true});},{signal:abort.signal});
 controls.addEventListener('input',event=>{if(event.target.matches('input[type=range]')){state.angle=+event.target.value;event.target.setAttribute('aria-valuetext',state.angle+' degrees');render({controlUpdate:false,persist:true});}},{signal:abort.signal});
 instance.render=render;render();el.dataset.visualReady='true';
 if(type==='charts'||type==='transport')initSpatial(instance).then(result=>{if(disposed){result?.dispose();return;}spatial=result;if(result){staticEl.hidden=true;el.querySelector('.vl-spatial').hidden=false;el.querySelector('.vl-spatial-hint').hidden=false;el.dataset.spatialReady='true';result.update();if(type==='charts')note.innerHTML=`${math(String.raw`(p,q)=\dfrac{(u,v)}{u^2+v^2}`,'geometry')} on the overlap. The highlighted projection selects one chart; both coordinate descriptions remain visible.`;}else el.dataset.spatialReady='fallback';}).catch(()=>{el.dataset.spatialReady='fallback';});
 return ()=>{disposed=true;abort.abort();labelResize.disconnect();spatial?.dispose();active.delete(id);el.removeAttribute('data-visual-ready');};}
async function initSpatial(instance){const {el,type,state}=instance;const [THREE,{OrbitControls}]=await Promise.all([import('three'),import('./assets/three/OrbitControls.js')]);const stage=el.querySelector('.vl-spatial');if(!stage?.isConnected)return null;let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'low-power'});}catch{return null;}renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,2));renderer.setClearColor(0,0);renderer.domElement.setAttribute('role','img');renderer.domElement.setAttribute('aria-label',descriptions[type]);stage.append(renderer.domElement);stage.tabIndex=0;stage.setAttribute('aria-label','Rotatable sphere. Use arrow keys to orbit. Press Home to reset.');
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(34,1,.1,100);camera.up.set(0,0,1);const target=type==='charts'?[.35,0,0]:[.08,.08,.12],initial=type==='charts'?[3.5,-5,2.9]:[3,3.8,2.8];camera.position.set(...initial);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(...target);controls.enableDamping=false;controls.enablePan=false;controls.enableZoom=false;controls.update();const root=new THREE.Group();scene.add(root);const base=new THREE.Group(),dynamic=new THREE.Group();root.add(base,dynamic);let visible=true,rendererAvailable=true;const materials=new Set();
 const V=a=>new THREE.Vector3(...a);
 function mat(role,opacity=1){const m=new THREE.MeshBasicMaterial({transparent:opacity<1,opacity,side:THREE.DoubleSide,depthWrite:opacity===1});m.userData.role=role;materials.add(m);return m;}
 function ln(points,role='geometry',opacity=.7,parent=base){const m=new THREE.LineBasicMaterial({transparent:opacity<1,opacity});m.userData.role=role;materials.add(m);const o=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points.map(V)),m);parent.add(o);return o;}
 function dot3(p,role='observer',size=.045,parent=dynamic){const o=new THREE.Mesh(new THREE.SphereGeometry(size,20,14),mat(role));o.position.copy(V(p));parent.add(o);return o;}
 function arrow3(p,v,role='transport',length=.68,parent=dynamic,opacity=1){const arrow=new THREE.ArrowHelper(V(v).normalize(),V(p),length,0xffffff,.12,.055);for(const o of [arrow.line,arrow.cone]){o.userData.sharedGeometry=true;o.material.userData.role=role;o.material.transparent=opacity<1;o.material.opacity=opacity;materials.add(o.material);}parent.add(arrow);return arrow;}
 scene.add(new THREE.HemisphereLight(0xffffff,0x65728a,1.9));const light=new THREE.DirectionalLight(0xffffff,1.5);light.position.set(2,-3,5);scene.add(light);const surface=new THREE.MeshStandardMaterial({roughness:.85,metalness:0,transparent:type==='charts',opacity:type==='charts'?.55:1,depthWrite:type!=='charts'});surface.userData.role='figure-tint';materials.add(surface);const sphere=new THREE.Mesh(new THREE.SphereGeometry(.995,56,40),surface);base.add(sphere);
 for(let j=1;j<12;j++){const t=j*PI/12;ln(Array.from({length:97},(_,i)=>[Math.sin(t)*Math.cos(i*PI/48),Math.sin(t)*Math.sin(i*PI/48),Math.cos(t)]),'geometry',.43);}for(let j=0;j<12;j++)ln(Array.from({length:97},(_,i)=>[Math.sin(i*PI/48)*Math.cos(j*PI/6),Math.sin(i*PI/48)*Math.sin(j*PI/6),Math.cos(i*PI/48)]),'geometry',.38);
 if(type==='charts'){for(let k=-4;k<=4;k++){ln([[-1.6,k*.4,0],[2.4,k*.4,0]],'line',.5);ln([[k*.4,-1.6,0],[k*.4,1.6,0]],'line',.5);}ln([[0,0,-1.25],[0,0,1.25]],'ink',.25);}
 const labels=document.createElement('div');labels.className='vl-spatial-labels';stage.append(labels);const labelEntries=[];
 function lbl(tex,p,role=''){const div=document.createElement('span');div.className='vl-label';div.innerHTML=math(tex,role);labels.append(div);labelEntries.push({div,p:V(p)});}
 function clear(){dynamic.traverse(o=>{if(!o.userData.sharedGeometry)o.geometry?.dispose();for(const m of (Array.isArray(o.material)?o.material:[o.material]).filter(Boolean)){materials.delete(m);m.dispose();}});dynamic.clear();labels.replaceChildren();labelEntries.length=0;}
 function theme(){const css=getComputedStyle(el);for(const m of materials)m.color.set(css.getPropertyValue('--'+m.userData.role).trim()||css.getPropertyValue('--ink').trim());render();}
 function render(){if(!visible||!rendererAvailable)return;renderer.render(scene,camera);const rect=stage.getBoundingClientRect();for(const l of labelEntries){const p=l.p.clone().project(camera);l.div.style.left=`${(p.x+1)*rect.width/2}px`;l.div.style.top=`${(1-p.y)*rect.height/2}px`;}}
 function update(){clear();if(type==='charts'){const p=points[state.point],coords=chartCoordinates(p),north=state.chart==='north',xy=north?coords.north:coords.south,pole=[0,0,north?1:-1];dot3([0,0,1],'ink',.035);dot3([0,0,-1],'ink',.035);lbl('N',[0,0,1.15]);lbl('S',[0,0,-1.15]);if(xy){ln([pole,[xy[0],xy[1],0]],north?'transport':'geometry',1,dynamic);dot3([xy[0],xy[1],0],north?'transport':'geometry');lbl(north?'(u,v)':'(p,q)',[xy[0]+.13,xy[1]-.1,-.13],north?'transport':'geometry');}dot3(p,'observer',.06);if(state.point!=='pole')lbl('P',add(p,[.08,0,.14]),'observer');}else{const step=state.step,frame=transportedFrame(step);for(let j=0;j<3;j++){const axis=cross(transportVertices[j],transportVertices[j+1]),pts=Array.from({length:49},(_,i)=>rotate(transportVertices[j],axis,i*PI/96).map(x=>x*1.007));if(j<step){const curve=new THREE.CatmullRomCurve3(pts.map(V)),mesh=new THREE.Mesh(new THREE.TubeGeometry(curve,64,.014,7,false),mat('transport'));dynamic.add(mesh);}else ln(pts,'ink',.15,dynamic);}
 const normal=V(frame.point),plane=new THREE.Mesh(new THREE.PlaneGeometry(1.05,1.05),mat('geometry',.1));plane.position.copy(normal.clone().multiplyScalar(1.009));plane.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),normal);dynamic.add(plane);arrow3(scale(frame.point,1.02),frame.vector);dot3(scale(frame.point,1.018),'observer');
 if(step===0){arrow3([1.02,0,0],[.7,0,1],'observer',.9,dynamic,.7);arrow3([1.02,0,0],[1,0,0],'geometry',.45);lbl(String.raw`\mathbf a_T`,[1.08,0,.82],'transport');}else if(step===3){arrow3([1.02,0,0],[0,0,1],'observer',.68);lbl(String.raw`\mathbf V_{\rm start}`,[1.12,0,.8],'observer');lbl(String.raw`\mathbf V_{\rm final}`,[1.12,.78,-.05],'transport');}else{const mid=transportedFrame(step-.5);arrow3(scale(mid.point,1.02),mid.vector,'transport',.48,dynamic,.4);}for(const [name,p]of [['A',[1.2,-.06,-.1]],['N',[0,0,1.18]],['B',[0,1.2,-.1]]])lbl(name,p);}
 theme();}
 function resize(){const rect=el.querySelector('.vl-drawing').getBoundingClientRect();if(!rect.width||!rect.height)return;camera.aspect=rect.width/rect.height;camera.zoom=Math.min(1,Math.max(.72,camera.aspect));camera.updateProjectionMatrix();renderer.setSize(rect.width,rect.height);render();}
 const ro=new ResizeObserver(resize);ro.observe(el.querySelector('.vl-drawing'));const mo=new MutationObserver(theme);mo.observe(document.documentElement,{attributes:true,attributeFilter:['data-theme']});const io=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;if(visible)render();},{rootMargin:'80px'});io.observe(el);const abort=new AbortController();controls.addEventListener('change',render);stage.addEventListener('keydown',event=>{if(event.target!==stage)return;if(event.key==='Home'){event.preventDefault();camera.position.set(...initial);controls.target.set(...target);controls.update();}else if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key)){event.preventDefault();const d=camera.position.clone().sub(controls.target);if(event.key==='ArrowLeft'||event.key==='ArrowRight')d.applyAxisAngle(new THREE.Vector3(0,0,1),event.key==='ArrowLeft'?.18:-.18);else{const axis=d.clone().cross(camera.up).normalize();d.applyAxisAngle(axis,event.key==='ArrowUp'?.12:-.12);}camera.position.copy(controls.target).add(d);controls.update();}},{signal:abort.signal});renderer.domElement.addEventListener('webglcontextlost',event=>{event.preventDefault();rendererAvailable=false;el.querySelector('.vl-static').hidden=false;stage.hidden=true;el.querySelector('.vl-spatial-hint').hidden=true;el.dataset.spatialReady='fallback';},{signal:abort.signal});resize();update();return {update,dispose(){abort.abort();ro.disconnect();mo.disconnect();io.disconnect();controls.dispose();scene.traverse(o=>{if(!o.userData.sharedGeometry)o.geometry?.dispose();});materials.forEach(m=>m.dispose());renderer.dispose();renderer.forceContextLoss();stage.replaceChildren();}};
}
export function initVisualLessons(){const cleanups=[...document.querySelectorAll('[data-visual-lesson]')].map(mount).filter(Boolean);return ()=>cleanups.forEach(cleanup=>cleanup());}
